### ISSUE TITLE
Bug when installing

### ISSUE THREAD

**Issue by alnutile** [aws/amazon-ssm-agent#102]
Though here is the real "problem" I am trying to install it our our docker guests that are running in a service on our AWS Cluster. My goal is to take advantage of SSM to report on inventory etc.
But maybe the tool was never meant for running on and Amazon Linux 2 Docker install

```
Running transaction
  Installing : amazon-ssm-agent-2.2.607.0-1.x86_64                          1/1
start: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
  Verifying  : amazon-ssm-agent-2.2.607.0-1.x86_64                          1/1

Installed:
  amazon-ssm-agent.x86_64 0:2.2.607.0-1
```

Here is the output of /etc/os-release
```
bash-4.2# more /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```

If not just tell me to stop now :) 

We are using it on Ec2 instances and of course that is going well. I was treating it as a hybrid install https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-managedinstances.html

I had it running once before on our Ubuntu Docker Guests but we moved to Amazon Docker. 

Thanks

**Comment by hiimtu** [comment]
Hi @alnutile, if I understand your use case, you are trying to use SSM inside containers. You are attempting to this by registering the agent as a managed instance (hybrid install).

If so, the agent currently is not fully supported for containers. We are working on getting SSM to work with containers, so look for this feature in the near future.

I'm going to close the issue, but feel free to open up a new one if you have any more question/concerns.
