### ISSUE TITLE
Error Codes and other Variables are not properly populated in _script.sh

### ISSUE THREAD

**Issue by pcolazurdo** [aws/amazon-ssm-agent#104]
# Error Codes and other Variables are not properly populated in _script.sh

## Steps to Reproduce
Running this command in multiple systems provide very weird results:
```
{
  "schemaVersion": "1.2",
  "description": "Upgrade packages managed by any package manager in Linux",
  "runtimeConfig": {
    "aws:runShellScript": {
      "properties": [
        {
          "id": "0.aws:runShellScript",
          "runCommand": [
            "#!/bin/bash",
            "if [ -z '$BASH_VERSION' ]",
            "then",
            "  echo running bash",
            "  exec bash '$0' '$@'",
            "else",
            "  echo already running bash",
            "fi",
            "which yum",
            "if [ $? -eq 0 ]",
            "  then PKG_MANAGER=yum",
            "  else PKG_MANAGER=apt-get",
            "fi",
            "echo Using: $PKG_MANAGER",
            "$PKG_MANAGER -y update",
            "$PKG_MANAGER -y upgrade"
          ]
        }
      ]
    }
  }
}
```

## Actual Results (include screenshots)
In a system without yum installed the corresponding _script is this:

```
#!/bin/bash
if [ -z '3.2.57(1)-release' ]
then
  echo running bash
  exec bash '-bash' ''
else
  echo already running bash
fi
which yum
if [ 255 -eq 0 ]
  then PKG_MANAGER=yum
  else PKG_MANAGER=apt-get
fi
echo Using: 
 -y update
 -y upgrade
```

## Expected Results (include screenshots)
* ```which yum``` returns 1 in a system without yum - **why is 255 in _script.sh?**
* based on this results (255 not equal to 0) PKG_MANAGER=apt-get / but in ```echo $PKG_MANAGER``` is empty - **why variables are not conserved?**
* running ```echo $BASH_VERSION``` in the system shows 4.3.48(1)-release / but in _script.sh version shows as _3.2.57(1)-release_ - **Where is bash this bash version coming from**

* Similar results appear in a system with yum installed:
```
#!/bin/bash
if [ -z '3.2.57(1)-release' ]
then
  echo running bash
  exec bash '-bash' ''
else
  echo already running bash
fi
which yum
if [ 255 -eq 0 ]
  then PKG_MANAGER=yum
  else PKG_MANAGER=apt-get
fi
echo Using: 
 -y update
 -y upgrade
```

**Comment by dimagermanov** [comment]
Thank you for submitting the issue.

Agent should not replace those variables at all in _script.sh.
To better understand the case can you answer the following questions:

How do you run the command? 

Are you creating an SSM document?

Do you use CLI or EC2 console website?
