### ISSUE TITLE
SSM agent not working with Amazon Linux 1

### ISSUE THREAD

**Issue by 88lexd** [aws/amazon-ssm-agent#107]
We are using the original Amazon Linux AMI, see os-release below

```
$ cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2016.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2016.03"
PRETTY_NAME="Amazon Linux AMI 2016.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2016.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```

I have installed the ssm agent by running the command:
`$ yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm`

From here I then attached the role "AmazonEC2RoleforSSM" to my instance and nothing happens... the instance does not appear in "Systems Manager > Managed instances" section..

I also notice that the installer puts files where systemd is located, however this OS does not support systemd from what I read..
```
$ rpm -qa | grep ssm
amazon-ssm-agent-2.2.800.0-1.x86_64
$ rpm -ql amazon-ssm-agent-2.2.800.0-1.x86_64
/etc/amazon/ssm/README.md
/etc/amazon/ssm/RELEASENOTES.md
/etc/amazon/ssm/amazon-ssm-agent.json.template
/etc/amazon/ssm/seelog.xml.template
/etc/init/amazon-ssm-agent.conf
/etc/systemd/system/amazon-ssm-agent.service
/usr/bin/amazon-ssm-agent
/usr/bin/ssm-cli
/usr/bin/ssm-document-worker
/var/lib/amazon/ssm
$ ls -l /etc/systemd/system
total 4
-rw-r--r-- 1 root root 241 Jun 26 08:39 amazon-ssm-agent.service
$ which systemctl
/usr/bin/which: no systemctl in (/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/aws/bin:/root/bin)
```

For us to upgrade and move everything from this server to a new instance is a lot of work right now and would be good if we can have SSM working.. I cant try older versions either because with previous version there was a bug which is only been fixed in version 2.2.800.0 (See https://github.com/aws/amazon-ssm-agent/issues/94)

**Comment by mmendonca3** [comment]
hello @88lexd, 

Thank you for posting here. Amazon Linux AMI does not support systemd. It does support upstart and SSM Agent will use upstart and run on the AMI. Also, SSM Agent is also installed on Amazon Linux by default. You might need to update it to use the most recent version. 

In case you need to use systemd, it is available on Amazon Linux 2, but you would need to change your instance type. 

I am closing this request, please feel free to reopen it if you have any other questions.
