### ISSUE TITLE
Usage guide for the latest version

### ISSUE THREAD

**Issue by bpradipt** [aws/amazon-ssm-agent#11]
Can you add an example of how to use this agent code for managed instances. The command line is different from the available documentation mentioned here  - https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/install-ssm-agent.html#install-managed-linux

This the new command line when built from source:
-httptest.serve string
 &nbsp;&nbsp;&nbsp;if non-empty, httptest.NewServer serves on this address and blocks
  -i string
 &nbsp;&nbsp;&nbsp;instance id
  -r string
  &nbsp;&nbsp;&nbsp;instance region
which is different that the one downloaded from S3
-register	register managed instance
&nbsp;&nbsp;&nbsp;-id	SSM activation ID    	(REQUIRED)
&nbsp;&nbsp;&nbsp;-code  SSM activation code	(REQUIRED)
&nbsp;&nbsp;&nbsp;-region  SSM region       	(REQUIRED)

**Comment by kirupani** [comment]
@bpradipt 
The source has been updated. The new command line flags can be seen [here](https://github.com/aws/amazon-ssm-agent/blob/master/agent/agent_parser.go#L76). Please try again and let us know if you encounter any issues.
