### ISSUE TITLE
Hybrid mode registration saves credentials in root home

### ISSUE THREAD

**Issue by ktravis** [aws/amazon-ssm-agent#115]
When registering a managed instance through hybrid mode, the amazon-ssm-agent stores temporary credentials returned by the SSM service in `/root/.aws/credentials`, with the profile name `default`. This can cause issues for other processes running as the root user. For example an EC2 instance (registered via hybrid mode) intending to use an instance profile for IAM permissions will pick up this default profile instead, leading to permissions issues.

Is this behavior intended? Is it being documented anywhere outside of the code? Is there a preferred method for changing the behavior? I see that setting `shareCreds` to false in the amazon-ssm-agent configuration file will disable this behavior [in one particular place](https://github.com/aws/amazon-ssm-agent/blob/master/agent/managedInstances/rolecreds/role_provider.go#L142), but I am also concerned about the implications of doing so. If the shared credentials are not written, does that mean no caching is done and credentials must be acquired for every operation? Would this happen on a per-"ping"/heartbeat frequency?

I have also experimented with setting the `AWS_SHARED_CREDENTIALS_FILE` environment variable, which seems to have the desired effect. Is this a reliable solution to the issue?

Furthermore, are there any additional files being created in the root user's home directory that might conflict with the operation of other programs?

Any help you can provide would be greatly appreciated.

**Comment by jasmineustc** [comment]
Hi @ktravis , I think someone also found this issue on Windows platform. Based on your description, maybe it's the same issue? https://github.com/aws/amazon-ssm-agent/issues/103
If it's the credential permission issue, I think they already fix it in the latest version. https://github.com/aws/amazon-ssm-agent/commit/6feb4afab0a0b3800987b04cb954f0581b7543b2

**Comment by ktravis** [comment]
The issues are related, but not really the same - in my case I *do not* want to overwrite the default credentials location for the root user. The fact that it is succeeding is what is causing a problem.

**Comment by darrencurtis** [comment]
We are experiencing the same issue, after following the AWS Blog "Centralized Management of Multiple Accounts and Cross-Platform EC2 Instances Using AWS Systems Manager:  https://aws.amazon.com/blogs/mt/centralized-management-of-multiple-accounts-and-cross-platform-ec2-instances-using-aws-systems-manager/

We rely on the instance profile for permissions and do not want root's .aws/credentials file populated by ssm with temporary credentials that break our processes.   ktravis would you mind explaining how you set the AWS_SHARED_CREDENTIALS_FILE as a work around?

I have set "ShareCreds" : false in the /etc/amazon/ssm/amazon-ssm-agent.json config file, which has stopped the behavior, but not sure of the consequences yet.

Thanks!

**Comment by ktravis** [comment]
@darrencurtis Setting the `AWS_SHARED_CREDENTIALS_FILE` to an alternate location (say, `/var/lib/amazon/ssm/credentials`) in the amazon-ssm-agent service/job file, as well as in any environment where you will be calling the agent directly (such as when registering) will keep the agent from saving credentials to `/root/.aws/credentials`.

> set "ShareCreds" : false in the /etc/amazon/ssm/amazon-ssm-agent.json ... not sure of the consequences yet

I am also very interested in knowing the consequence of this configuration, if any. Maybe someone on the project could weigh in?

**Comment by darrencurtis** [comment]
Thanks @ktravis .  We opened a support case with AWS and here are their insights. The SSM agent, when configured with an activation code, does not use the role on the instance. This is because activation codes, while we're using them for cross-account management right now, are primarily intended for use with resources outside of AWS (Hybrid / on-premises), in which case there is no instance role. This method of using SSM causes the agent to use the activation codes to fetch temporary credentials from a special, publicly accessible endpoint. The Instance roles are used by SSM agent when you're using SSM in the same account that the instance is in.  It is not necessary to set the ProfileName value in the json, as that appears to be used for something different, however it is recommended to set the ShareProfile to "ssm" so that root's default profile is not changed in the credentials file.

**Comment by AmyZhangAmz** [comment]
Hi @ktravis,

Thank you for posting here. I listed some information about your questions and hope it could help you a little bit. 

These credentials saved in root directory is the intended behavior of amazon-ssm-agent. Currently, we don’t provide alternatively location for saving credentials. Also, there is no additional files created in the root user directory for amazon-ssm-agent.

For "shareCreds" flag, if you set it to false, amazon-ssm-agent will stop updating the temporary token periodically, which will cause amazon-ssm-agent stop working properly. This “credentials” file contains temporary credentials and will expire in one hour after amazon-ssm-agent authenticates. Please refer to this AWS link. (https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html )

**Comment by kapilt** [comment]
The right place for ssm to store ITS credentials is to its own var directory, storing them to the root directory is going to cause all kinds of issues for other applications on the box that may be using aws creds.
