### ISSUE TITLE
Incorrect permissions on ssm-agent-users

### ISSUE THREAD

**Issue by lw-trectenwald** [aws/amazon-ssm-agent#117]
Version 2.3.50.0

The file `/etc/sudoers.d/ssm-agent-users` is being created without an explicit `os.Chown()`. Permissions for `/etc/sudoers.d` files need to be `0440`. Under my umask, it is `0644` which breaks `sudo` for that file.

Change would be in `agent/session/session_unix.go`

**Comment by PeteE** [comment]
This is a pain as it causes `visudo -s` to fail which breaks our puppet runs.

**Comment by munindradas** [comment]
We have a fix ready that will release with the next Agent update. Apologies for the inconvenience! In the meantime, if possible, you can change the permission on this file manually to remove the warning.

Thanks!
