### ISSUE TITLE
CreateControlChannel failed with error

### ISSUE THREAD

**Issue by timoteialbu** [aws/amazon-ssm-agent#120]
Hey,

We've been getting this error a lot 
```
ERROR [MessageGatewayService] Failed to get controlchannel token, error: CreateControlChannel failed with error: createControlChannel request failed: unexpected response from the service <BadRequest xmlns=""><message>Unable to process due to throttling.</message></BadRequest>
```
, so much so, that it made our syslog file so big that filled up our server. As such, we had to disable the ssm-agent. I tried looking for a similar error, but couldn't find anything online. Any ideas?

**Comment by fshankar** [comment]
This was a known issue and was recently fixed. Please update the agent version to 2.3.68.0 and let us know if you still encounter this problem.

**Comment by avinashgoud2000** [comment]
Hi @fshankar , I see after updating the ssm agent version to latest, the only fix I could see was the message frequency of error has reduced from several messages a minute to printing error once an hour bu the problem still persists.

**Comment by rajmj83** [comment]
I noticed the same issue with ssm agent on Amazon Linux V2. Upgrading ssm agent did not help.
I found solution here => https://docs.aws.amazon.com/systems-manager/latest/userguide/getting-started-add-permissions-to-existing-profile.html 

Hope this helps and good luck.
