### ISSUE TITLE
Building & Installing v2.3.68.0 From Source Has `Standard_Stream` Plugin Error

### ISSUE THREAD

**Issue by kylegoch** [aws/amazon-ssm-agent#122]
Howdy.
When building tag `2.3.68.0` from source using `make build-linux`, the agent returns this error when trying to start a Session Manager session from the console.

```
Sep 21 17:02:22 ip-10-10-32-11 amazon-ssm-agent: 2018-09-21 17:02:21 INFO [MessageGatewayService] Sending reply {
Sep 21 17:02:22 ip-10-10-32-11 amazon-ssm-agent: "SchemaVersion": 1,
Sep 21 17:02:22 ip-10-10-32-11 amazon-ssm-agent: "TaskId": "kgochenour-0a6f3f2d6579b9118",
Sep 21 17:02:22 ip-10-10-32-11 amazon-ssm-agent: "Topic": "agent_task_complete",
Sep 21 17:02:22 ip-10-10-32-11 amazon-ssm-agent: "FinalTaskStatus": "Failed",
Sep 21 17:02:22 ip-10-10-32-11 amazon-ssm-agent: "IsRoutingFailure": false,
Sep 21 17:02:22 ip-10-10-32-11 amazon-ssm-agent: "AwsAccountId": "",
Sep 21 17:02:22 ip-10-10-32-11 amazon-ssm-agent: "InstanceId": "<omitted>",
Sep 21 17:02:22 ip-10-10-32-11 amazon-ssm-agent: "Output": "Plugin with name Standard_Stream is not supported by this version of ssm agent, please update to latest version. Step name: Standard_Stream",
Sep 21 17:02:22 ip-10-10-32-11 amazon-ssm-agent: "S3Bucket": "",
Sep 21 17:02:22 ip-10-10-32-11 amazon-ssm-agent: "S3UrlSuffix": "",
Sep 21 17:02:22 ip-10-10-32-11 amazon-ssm-agent: "CwlGroup": "",
Sep 21 17:02:22 ip-10-10-32-11 amazon-ssm-agent: "CwlStream": ""
Sep 21 17:02:22 ip-10-10-32-11 amazon-ssm-agent: }
```

Nothing crazy with the agent, just building then calling `amazon-ssm-agent` to start. 

If I install the rpm provided by AWS Session Manager works fine. But building from source does not.

OS: CentOS 7

**Comment by nitikagoyal87** [comment]
When building agent source code using ‘make build’ command, multiple binaries are created in directory 'amazon-ssm-agent/bin/linux_amd64’ along with amazon-ssm-agent binary. We suspect possible root cause of error reported above is missing binaries ssm-ssesion-worker and ssm-session-logger from /usr/bin/ directory of target system. Could you please make sure these binaries are placed in /usr/bin/ directory and try running Session Manager scenario?

**Comment by hiimtu** [comment]
Hi are you still seeing this issue. @bdwyertech contributed a fix that might fix the problem and was merge in in this commit https://github.com/aws/amazon-ssm-agent/commit/bc7e78017a7802854fb9ddf313ca053a20e6a471 Please update the latest agent and see if this issue still occurs. Feel free to reopen a new issue if you are still running into the problem.
