### ISSUE TITLE
Raspberry Pi cannot find activation endpoint...

### ISSUE THREAD

**Issue by alexwbai** [aws/amazon-ssm-agent#125]
I'm really hoping this isn't me being stupid but I'm simply trying to register a raspberry pi and seem to keep running into this error:

2018-10-10 09:27:11 ERROR Registration failed due to error registering the instance with AWS SSM. RequestError: send request failed
caused by: Post https://ssm.%E2%80%9Cus-east-1%E2%80%9D.amazonaws.com/: dial tcp: lookup ssm.xn--us-east-1-9b0eua.amazonaws.com on 8.8.8.8:53: no such host

The raspberry pi has internet connectivity and it can resolve DNS fine.  I am also within the activation window.  Is ssm.xn--us-east-1-9b0eua.amazonaws.com a valid endpoint?  Am I forgetting something?

That error above is what is in the logs.
(Not sure if it makes any difference but we've disabled dhcpcd on the raspberry pi)

Thanks!

**Comment by alexwbai** [comment]
Figured it out.  This walkthrough guide has quotation marks in the command although when i removed them it worked.

https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-install-managed-linux.html

**Comment by mwilde345** [comment]
glad i found this

**Comment by YTvW** [comment]
Thanks, was getting really annoyed trying to figure out why it wasn't working

**Comment by 66string** [comment]
Thanks for that info. It worked on RHEL 7 box.
