### ISSUE TITLE
EC2AMAZ have thousands of TCP connections

### ISSUE THREAD

**Issue by ArturChe** [aws/amazon-ssm-agent#128]
Hi there,

I have run `netstat | FINDSTR EC2AMAZ` command on my Windows EC2 instance and can see EC2AMAZ established almost 8000 TCP connections.

I want just to clarify if it is a normal behavior, and which service EC2Config or SSMAgent produced such amount of connections?

**Comment by AmyZhangAmz** [comment]
Hi @ArturChe ， 

Thank you for posting here. AWS EC2 Windows instance hostname starts with “EC2AMAZ”. All the connections established by this machine will be marked from “EC2AMAZ”, not only the ones used by SSM agent.
