### ISSUE TITLE
Please update the snap packages

### ISSUE THREAD

**Issue by runningman84** [aws/amazon-ssm-agent#129]
In ubuntu you still get a quite old release:
```
snap list
Name              Version    Rev   Tracking  Publisher   Notes
amazon-ssm-agent  2.3.68.0   734   stable    aws✓        classic
```
I do not get why you update the deb packages but leave the snap packages outdated.

**Comment by nehalaws** [comment]
Thank you for posting the issue here, we will work on publishing agent versions to snap stable more frequent. Currently candidate branch is up to date.

**Comment by nehalaws** [comment]
I have also updated the agent version in stable branch, thank you again for posting the issue.
