### ISSUE TITLE
Agent does not automatically start on package install in Ubuntu 14.04

### ISSUE THREAD

**Issue by johnrengelman** [aws/amazon-ssm-agent#13]
This commit: https://github.com/aws/amazon-ssm-agent/commit/0625e94fd8d8f57d2390f100e0251d7f85090ae5 broke the package from automatically autostarting on install.

This is what is output on my Ubuntu 14.04 system for logical check:

```
# /sbin/init --version
init (upstart 1.12.1)
Copyright (C) 2006-2014 Canonical Ltd., 2011 Scott James Remnant

This is free software; see the source for copying conditions.  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Version:

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty
```

**Comment by mmendonca3** [comment]
Hello johnrengelman, 

Thank you for your comment. The team is investigating this issue.

**Comment by shihuazhang** [comment]
This issue has been addressed in the latest build

Feel free to reopen the issue if you have more question
