### ISSUE TITLE
Windows 2016 SSM agent fail during deployment

### ISSUE THREAD

**Issue by varun7447** [aws/amazon-ssm-agent#137]
SSM agent is failing during new version of application deployment. This is happening in elastic beanstalk with windows stack. Configured custom IIS logs section Under SSM plugin for cloudwatch. The configure_logstream.ps1 is failing script. Is there a way to configure cloudwatch custom logs and metrics in elastic beanstalk windows ? Looks like modifying the cloudwatch SSM plugin config json is causing this issue. How to resolve this issue?

Here is the error message 

[ERROR] Custom SSM awsCloudWatch plugin configuration files (AWS.EC2.Windows.CloudWatch.json) detected, failing deployment.

**Comment by dimaAmz** [comment]
Thank you for request, varun7447. For help with this issue please create a question in AWS Forum for Elastic Beanstalk - https://forums.aws.amazon.com/forum.jspa?forumID=86
