### ISSUE TITLE
Issue with latest agent on Raspbian & Ubuntu

### ISSUE THREAD

**Issue by besn0847** [aws/amazon-ssm-agent#143]
Trying to set-up AWS SSM agent on both Ubuntu and Raspbian. I use the latest SSM agent.

In both systems, i get the following error 👍 

2018-11-19 09:37:37 ERROR [processRegistration @ agent_parser.go.114] Registration failed due to error registering the instance with AWS SSM. RequestError: send request failed
caused by: Post https://ssm.%E2%80%9Ceu-west-3%E2%80%9D.amazonaws.com/: dial tcp: lookup ssm.xn--eu-west-3-9b0eua.amazonaws.com on 192.168.1.1:53: no such host

Instead of using the endpoint ssm.eu-west-3.amazonaws.com, it adds extra characters and the name resolution fails.

Is there a repo to download a previous version to test it ?

Cheers

**Comment by AmyZhangAmz** [comment]
Thank you for posting here. I have tried to register On-prem instance in eu-west-3 region on Ubuntu and Raspbian OS with latest SSM Agent version, both platform works fine.  
The reason you received this error message is that you used non-standard quotes in registration command.  If you use normal quote like this  " , the issue could be solved.
