### ISSUE TITLE
Session Manager - Feature Request - Allow read only user

### ISSUE THREAD

**Issue by akr257** [aws/amazon-ssm-agent#146]
Anyone who has access to session manager on a specific instance currently has sudo access (as the ssm user on the ec2 instance is part of the sudoers group). We have a use case where we would like to give users access to session manager to ssh onto an instance, but they shouldn't have sudo access (i.e, read only access). 
It would be great if session manager provides an option to support for read-only user access and sudo access based on IAM roles/policies.

**Comment by munindradas** [comment]
Thank you for the feedback!

You should be able to configure the user on specific instances to remove sudo/admin access following instructions in this doc - https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started-ssm-user-permissions.html. To do this across multiple instances, you can use RunCommand. 

Thanks!

**Comment by akr257** [comment]
Hi,
Thank you for the reply. However, my use case is different. The link you have provided either removes or grants sudo access to the ssm-user. 
My use case is I will have teams of users:
Application-Support-Team: Users belonging to this team cannot have sudo access to the server
Infrastructure-Support-Team: This team can have sudo access to the same server
Users will assume IAM roles and start a session via Session Manager. 
Hope I've clarified above. 
Thanks

**Comment by UAce** [comment]
I have a similar use case and it would be nice to hear some updates/news on this matter!
Thank you

**Comment by phene** [comment]
@akr257 Not saying this shouldn't be a feature, but you should consider different support instances that each have different IAM permissions associated with them to restrict access. Even if a read-only user can sudo on the read-only instance, there's very little they could do outside of the instance.

**Comment by akr257** [comment]
@phene Hi, I'm not sure if I understand you correctly. Can you explain further on what you mean by different IAM permissions? 

Perhaps I should explain what I meant in my request : I have two teams of users with two different IAM roles attached. 

These IAM roles currently provide users access to session manager. Any user assuming the role is now able to access an instance with sudo access. These instances are part of an Auto Scaling group. 

My request is that only users belonging to one IAM role can have sudo access on the instance. Users belonging to the other IAM role can only have read only access.

**Comment by phene** [comment]
Oh, I see what you mean -- My team doesn't give any non-admins users access to anything but a single administrative instance that provides scripts to probe services in the VPC and we control access from that host.

**Comment by yrsurya** [comment]
Seems to be we are facing the same issue, Here is the scenario.
We are having cloud engineer and developer IAM roles where it is configured through okta I like to get session manager to all the users belongs to both of roles but only cloud engineer should have allowed to root level ( sudo access ) where developer role should have not allowed to root level.

Will this can be achieved by updating policies attached to those IAM roles?

Please let me know if need more information

**Comment by hiimtu** [comment]
Hi everyone, the session manager team is working on a runAs feature that will allow you launch session with a custom user than the ssm user. Please keep an eye out for this feature. Thanks!

**Comment by jk2l** [comment]
@hiimtu why is this issue closed? it seem it is still a unresolved suggestion

**Comment by jkpdinesh** [comment]
Why this request is closed ? Do we have a solution for this use case? Please reopen this case as solution is not provided.

**Comment by M2SG** [comment]
@jk2l, is it possible with ssm-user for two IAM role one for Sudo and non sudo. 
and requested you all if there any other finding.

**Comment by jk2l** [comment]
> 
> 
> @jk2l, is it possible with ssm-user for two IAM role one for Sudo and non sudo.
> and requested you all if there any other finding.

i don't quite understand your question here

**Comment by ra7670** [comment]
I did not figure out how to write a policy that enforces the runAs parameter to a specific value.

Did anyone try / know if creating an own document for SSM would help:
```
{
  "schemaVersion": "2.2.0",
  "description": "Document to start a session as readonly user. User needs to be created as part of <<user_data>>",
  "parameters": {
    "runAs": {
      "type": "String",
      "default": "readonly",
      "description": "(Optional) The user to start the session as. TODO: need to figure out how to make that non-overwritable."
    }
  },
  "mainSteps": [
    {
      "action": "aws:runShellScript",
      "name": "runShellScript",
      "inputs": {
        "runCommand": ["echo Starting session as readonly user"]
      }
    }
  ]
}
```

And then through policy enforce using this new document:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "ssm:StartSession",
      "Resource": "arn:aws:ec2:region:account-id:instance/instance-id",
      "Condition": {
        "StringEquals": {
          "ssm:documentName": "arn:aws:ssm:region:account-id:document/Custom-StartSSHSession"
        }
      }
    },
    {
      "Effect": "Deny",
      "Action": "ssm:StartSession",
      "Resource": "arn:aws:ec2:region:account-id:instance/instance-id",
      "Condition": {
        "StringEquals": {
          "ssm:documentName": "arn:aws:ssm:region:account-id:document/AWS-StartSSHSession"
        }
      }
    }
  ]
}
```


aws ssm start-session --target instance-id --document-name Custom-StartSSHSession

**Comment by ra7670** [comment]
There seems to also be another way, by tagging users/IAM entities. But this then seems to apply for the user every time and not defined by which role he/she uses to sign in to the account:
https://docs.aws.amazon.com/systems-manager/latest/userguide/session-preferences-run-as.html
