### ISSUE TITLE
[Documentation] Provide Powershell Script for SSM Agent Uninstallation in Windows

### ISSUE THREAD

**Issue by lmayorga1980** [aws/amazon-ssm-agent#152]

**Comment by dimaAmz** [comment]
Thank you for your post, lmayorga1980,

You can uninstall the agent on Windows by running the following command:
wmic product where name="Amazon SSM Agent" call uninstall

And the following command when using powershell:
cmd.exe /c "wmic product where name=`"Amazon SSM Agent`" call uninstall"

**Comment by GreenRaccoon23** [comment]
> Thank you for your post, lmayorga1980,
> 
> You can uninstall the agent on Windows by running the following command: wmic product where name="Amazon SSM Agent" call uninstall
> 
> And the following command when using powershell: cmd.exe /c "wmic product where name=`"Amazon SSM Agent`" call uninstall"

The quotations are wrong. Use this instead:
```powershell
cmd.exe /c 'wmic product where name="Amazon SSM Agent" call uninstall'
```

I know this issue is closed, but this is the first Google result with a working answer for this question.
