### ISSUE TITLE
Session logs as implemented are useless for auditing/incident analysis

### ISSUE THREAD

**Issue by eriksw** [aws/amazon-ssm-agent#153]
If I open a session and run a malicious command that results in killing the ssm agent process hierarchy and removing the log file on disk, there's no durable record of what commands were run. **This makes the logging feature of Sessions completely useless for auditing or incident investigation purposes.**

The malicious command need not be particularly sophisticated; something like `find / -delete & systemctl poweroff --force` is sufficient to result in there not being a log of what was done. All I would know for sure is the information from CloudTrail re the opening of the session, and that the instance halted. That is not nearly enough to know whether data theft or other serious kinds of malicious activity might have happened or been attempted during the session.

Having the agent (or any other process on the instance) send the logs to CloudWatch on a more granular/frequent basis (#148) is not a solution for these concerns unless all input is buffered and not relayed to the tty/shell until _after_ it is committed to CloudWatch logs. While doing that would solve this concern, it would introduce unacceptable latency.

If the responsibility for recording and delivering the logs was moved to the service that relays input and output from the browser/cli session client to the agent process on the instance, that would completely address these concerns. (Ideally this would use the SSM service-linked role to deliver the logs, so that user and instance role permissions can be minimized.)

**Comment by Baalakay** [comment]
Just saw that the PFR for streaming from console to Cloudwatch was released yesterday.

**Comment by nitikaaws** [comment]
Session Manager logging capability is recommended to be used for debugging and troubleshooting purposes only. It now supports continuous streaming of logs to CloudWatch. More details can be found in below documentation. Please let us know in case of further queries.

https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-logging.html#session-manager-logging-cwl-streaming

**Comment by defsprite** [comment]
To save everyone some reading, the documentation states:

> Streaming session data is not supported for interactive commands.
