### ISSUE TITLE
SSM agent doesn't start when sysprep state is IMAGE_STATE_UNDEPLOYABLE

### ISSUE THREAD

**Issue by TheSkorm** [aws/amazon-ssm-agent#154]
We had a server that was otherwise operating fine where the sysprep state was in `IMAGE_STATE_UNDEPLOYABLE`. I believe this might occur if the instance has been sysprep'd 3 or more times. It doesn't appear to be preventing the server from otherwise functioning however it did cause SSM agent to not start with the error `Stopping SSM agent because sysprep hasn't completed`. 
https://github.com/aws/amazon-ssm-agent/blob/c7f64dd6682154ee2a710d0dccf0034d868c5037/agent/agent_windows.go#L21

I'm wondering if the ssm-agent should check a list of support values or possibly only have a list of values it's known NOT to work with.

As a workaround we changed the reg key on the server `IMAGE_STATE_COMPLETE`

**Comment by AmyZhangAmz** [comment]
Hi @TheSkorm 

Thank you for posting here. SSM Agent detects status of windows images before starting the agent. From MicroSoft official documents(https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-setup-states), “IMAGE_STATE _UNDEPLOYABLE” means the Windows Setup process is not yet complete. SSM Agent will start only after the windows images status become “IMAGE_STATE_COMPLETE”. We highly recommend  to use SSM Agent after sysPrep is done for better customer experience.

**Comment by TheSkorm** [comment]
The biggest problem is when the instance is stuck in this state (Microsoft lists two causes of this) which leaves you with an instance that can never be managed or troubleshooted through SSM.

**Comment by shihuazhang** [comment]
SSM Agent requires IMAGE_STATE_COMPLETE to be fully functional. 
I'm really sorry that we do not have any plan to check a list of support values for the SSM Agent.
