### ISSUE TITLE
Piping commands to start-session causes infinite loop of shell prompts.

### ISSUE THREAD

**Issue by phene** [aws/amazon-ssm-agent#155]
I'm attempting to write a wrapper script to start an ssm session in a bash prompt using the following:

`echo '/bin/bash' | aws ssm start-session --target $instance_id`

When I do this, I get an infinite loop of bash prompts and must terminate the process externally. The session is also left open and must be terminated manually with `aws ssm terminate-session` Similarly, if I pipe something like `echo hello`, I see "hello" printed, but then get the infinite loop of shell prompts.

Only `echo 'exit' | aws ssm start-session` doesn't exhibit this behavior, instead exiting immediately.

**Comment by blckct** [comment]
@phene The pipe is closed while ssm is not so that's causing problems. Luckily this works: https://stackoverflow.com/a/5852578/2115135 

`(echo '/bin/bash' && cat) |  aws ssm start-session --target $instance_id`

**Comment by phene** [comment]
FYI, that works great, just don't ever try to exit the shell with `ctrl+d`, otherwise you end up with the infinite loop of prompts that I described before.

**Comment by blckct** [comment]
@phene Yeah, that probably could be fixed by killing the aws cli on the client side after the cat command exits but I don't have a ready snippet for that one. Or you could try expect.

**Comment by phene** [comment]
This seems to work in the case of `ctrl-d`:

`(echo '/bin/bash' && cat && echo 'exit' && echo 'exit') | aws ssm start-session --target $instance_id`

Both exits are needed (1 for `/bin/bash`, the other for `/bin/sh`). The problem is other control commands are totally broken. If I run something like `top` after starting the session, exiting with `ctrl-c` gives me the infinite prompt issue again.

**Comment by sahirangaraju** [comment]
Thank you for the feedback! We will look into this.

**Comment by stephenl03** [comment]
I was able to get the `ctrl-c` stuff to work along with other items by adding `stty raw -echo` prior to the `(...)` and then after the `aws ssm start-session...` I add `; tty sane` to reset my `tty`. The only issue I am really running into is the `cat` command hanging and having to hit a key.

**Comment by ferkhat-aws** [comment]
You can now use Shell Profile to start in bash. https://aws.amazon.com/blogs/mt/bring-your-own-cli-session-manager-configurable-shell-profiles/
Closing.
