### ISSUE TITLE
UNIX Constants - Hardcoded Paths

### ISSUE THREAD

**Issue by bdwyertech** [aws/amazon-ssm-agent#158]
The Agent hardcodes a bunch of paths, these should be configurable:

https://github.com/aws/amazon-ssm-agent/blob/89e84f79ee287ca950344e5c8915034d5fc01ede/agent/appconfig/constants_unix.go#L96-L98

Use-case:
Building custom CoreOS AMI, where custom agents are supposed to be baked into OEM partition.  Building this package works fine, however running it with the binaries in different bin directory causes things to fail as they look for these paths.

**Comment by AmyZhangAmz** [comment]
Hi @bdwyertech , 

Thank you for bringing this to our attention.  We will have the team investigate this issue.

**Comment by StyleT** [comment]
Same issue here with CoreOS :(

**Comment by hiimtu** [comment]
Should be fixed with this: https://github.com/aws/amazon-ssm-agent/commit/bc7e78017a7802854fb9ddf313ca053a20e6a471
