### ISSUE TITLE
GPG key for rpm missing?

### ISSUE THREAD

**Issue by TobiasRoland** [aws/amazon-ssm-agent#161]
The aws cloudwatch unified agent provides a key at: `https://s3.amazonaws.com/amazoncloudwatch-agent/assets/amazon-cloudwatch-agent.gpg`. However, I am unable to find documentation of where the equivalent amazon-ssm-agent would be. 

I found this issue from 2016 in the closed state: https://github.com/aws/amazon-ssm-agent/issues/28

Does the ticket being closed mean that a gpg key has been published somewhere, or that it's been decided to not provide signing of the rpm? 

Either way, if there's a piece of documentation you could point me to regarding this, it would be much appreciated.

**Comment by dimaAmz** [comment]
Hello TobiasRoland, thank you for posting.

SSM agent rpm-s are currently not being signed.
