### ISSUE TITLE
Unable to upload command execution responses to S3 when Server Side Encryption is enforced

### ISSUE THREAD

**Issue by rvoitenko** [aws/amazon-ssm-agent#168]
Hi,

when I triggering ssm-agent to execute a command via "aws ssm send-command" and using S3 for upload command output it fails due to S3 has enforced Server Side Encryption policy.
For example with "aws s3 cp" it's enough to add "--sse" parameter to fix this issue.

How to enable SSE S3 upload for ssm-agent ?
I already see variable S3EncryptionEnabled in the code:
https://github.com/aws/amazon-ssm-agent/blob/master/agent/contracts/plugin.go#L72
But I guess it's not related to S3 upload.

Thank you.

**Comment by ranjrish** [comment]
This has been fixed with v3.0.502.0 onwards
