### ISSUE TITLE
SSM Agent Updated, and Re Ran Associated Documents

### ISSUE THREAD

**Issue by thefringeninja** [aws/amazon-ssm-agent#169]
Ran into an issue in production today. An update to the SSM Agent was pushed to one of our EC2 instances. This caused the documents associated with that instance to execute again. This is completely unexpected behavior, we assumed that the associated documents would run once when the instance starts up and no more. Is it possible to prevent this behavior in the future?

**Comment by hiimtu** [comment]
Hi, are you still seeing issues? This may occur if the document worker is interrupted by a restart or fails to mark the document as completed. Another reason is if you are running a document that requires reboot e.g. patching. The reboot documents set a flag file before executing the reboot, however if they fail to set the flag and reboot, the document will rerun from the start and execute another reboot.

Feel free to re-open if you are still seeing issues.
