### ISSUE TITLE
Links in commit messages not publicly viewable

### ISSUE THREAD

**Issue by cperciva** [aws/amazon-ssm-agent#17]
Many commit messages are simply links to https://cr.amazon.com/ .  Please don't do this -- it makes it impossible for non-Amazonian contributors to understand the thinking behind changes.

**Comment by shihuazhang** [comment]
Hi @cperciva 

We don't have a perfect solution for this at the moment. 
This issue will be resolved once the team move completely to GitHub.

Unfortunately, the team still need to work on projects internally from time to time

**Comment by cperciva** [comment]
Hi @shihuazhang 

I should have been clearer, sorry.  Links to Amazon's internal system are sensible of course when there's information there which other Amazonians will benefit from; my complaint is where they are the *only* information provided in the commit messages.  If you can copy and paste a few details into the commit message then the rest of us would have some understanding of the changes even though we can't access the system where they were originally discussed.

**Comment by shihuazhang** [comment]
Hi @cperciva 
That totally make sense, appreciated for your advice.
I'm really sorry that some of the commit message doesn't provide necessary information.
I will provide the feedback to the team :)
