### ISSUE TITLE
aws:downloadContent token-parameter-name regex

### ISSUE THREAD

**Issue by jacklin213** [aws/amazon-ssm-agent#180]
For the SSM plugin [aws:downloadContent](https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-plugins.html#aws-downloadContent) for the sourceType Github you need to provide Source Info with the following:
-  owner: The repository owner.
- repository: The name of the repository.
- path: The path to the file or directory you want to download.
- getOptions: Extra options to retrieve content from a different branch or a different commit. 
- tokenInfo: The Systems Manager parameter (a SecureString parameter) where you store your access token information.

For Systems Manager parameters the valid characters documented are as follows: Parameter names can consist of the following symbols and letters only: a-zA-Z0-9_.-/ 

However if the parameter name contains a "." (dot) it does not pass the regex check for tokenInfo and will error out.

**Example use case:**
When running AWS-RunRemoteScript and github is selected as the source following Step 6 of the guide [Run a Python Script from GitHub (Console)](https://docs.aws.amazon.com/systems-manager/latest/userguide/integration-remote-scripts.html#integration-github-python ) 
if you have a "." for the parameter name in tokenInfo eg)
` {{ ssm-secure:test.test }}`

You will get the following error:
----------ERROR-------
Format of specifying ssm parameter used for token-parameter-name is incorrect. Please specify parameter as '{{ ssm-secure:parameter-name }}'

**Comment by jacklin213** [comment]
Resolution Steps:
- Open to discussion but either allow the regex to include a "." (dot)
https://github.com/aws/amazon-ssm-agent/blob/a397287ea4e8c9451129cd4fdfc5f7955a628dc9/agent/plugins/downloadcontent/gitresource/privategithub/privategithub.go#L107 
or 
- Update documentation stating parameter names with "." specifically cannot be used here

**Comment by LiangChiAmzn** [comment]
Thanks for reaching out to us. We'll let our team investigate this bug and publish a fix soon.
