### ISSUE TITLE
amazon-ssm-agent.json

### ISSUE THREAD

**Issue by manuelh2410** [aws/amazon-ssm-agent#182]
Do we have configuration information for the  "amazon-ssm-agent.json" file ?
how does each of the settings in the json file affect the agent behavior ? 
what are valid values for the settings in the json file ?

**Comment by hiimtu** [comment]
Hi @manuelh2410 unfortunately I do not believe there is any documentation for the config values in the amazon-ssm-agent.json.

If there are any specific values you are curious about, please feel free to ask and I will get back to you on the functionality.

**Relevant package that does the config parsing:**
[appconfig.go](https://github.com/aws/amazon-ssm-agent/blob/master/agent/appconfig/appconfig.go)

Mds refers to run command
Mgs refers to session manager
Ssm refers to all other SSM functionalities

Hope this helps!

**Comment by manuelh2410** [comment]
HI @hiimtu , 
Not ideal ,but this certainly helps !
