### ISSUE TITLE
Question: is a SSH client on the roadmap?

### ISSUE THREAD

**Issue by johnnyplaydrums** [aws/amazon-ssm-agent#188]
Hey folks! In his initial blog post, Jeff Barr said that an actual SSH client was in the works. Can anyone on this project confirm? Any idea what is the ETA or prioritization of that feature? I've used session manager a LOT but have found that it's just not going to cut it as an SSH replacement until AWS supports an actual SSH client as a part of Session Manager. Any update would be appreciated.

p.s. I have a feeling that this is the wrong forum for this type of question. I'd love to hear your thoughts on the roadmap but also you can direct me to a better forum if needed 😊.

**Comment by omieomye** [comment]
Hi @johnnyplaydrums this is a definite ask from others as well, and we're actively working to see what it takes.  We'll aim to post an update when we have more news.

**Comment by johnnyplaydrums** [comment]
Cool thanks @omieomye 🙂. Can you be any more specific about the prioritization of this feature? I imagine a lot of folks are waiting for this before ditching their bastion hosts etc.

**Comment by brainstorm** [comment]
Looks like it's a done deal?: https://github.com/aws/amazon-ssm-agent/commit/fb5142432631fdbd29e00788f12b25e40411adef

**Comment by tdmalone** [comment]
Couple of relevant announcements today:
- https://aws.amazon.com/about-aws/whats-new/2019/07/session-manager-launches-tunneling-support-for-ssh-and-scp/
- https://aws.amazon.com/about-aws/whats-new/2019/07/session-manager-launches-run-as-to-start-interactive-sessions-with-your-own-operating-system-user-account/

**Comment by johnnyplaydrums** [comment]
Awesome! I am excited to try this out! I'll let you know how it goes. Closing this ticket, thanks for the help y'all
