### ISSUE TITLE
SSM package install fails with "Package (XYZ) is already in the process of other action"

### ISSUE THREAD

**Issue by muellerk22** [aws/amazon-ssm-agent#189]
Why would installing a package fail with "Package is already in the process of other action" when all previous commands have completed running.

the package fails with the same error either if the uninstall.sh or install.sh script runs.

checking documentation and internet is not turning up vary many answers.

I'm looking for what process should I follow to debug this.

This might be here:
https://github.com/aws/amazon-ssm-agent/blob/master/agent/plugins/configurepackage/localpackages/localpackages_lock.go

**Comment by mmendonca3** [comment]
Hi muellerk22, 

Thanks for using Distributor. This should not be the case, and the aws:configurePackage plugin should let go of the lock once the installation (or uninstallation) returns successfully or fails. 

At this point, if restarting SSMAgent is an option, that might be something that would fix this situation. 
If not, try to check what processes are currently running on your system and if there are any zombie processes that have the lock and you could kill it.

I will be closing this issue. Please reopen it if you have any other questions.
