### ISSUE TITLE
Package install expected completion time.

### ISSUE THREAD

**Issue by muellerk22** [aws/amazon-ssm-agent#190]
I'm learning to create my own distributor package.  To get things working I have a simple install that that starts a bash script in an infinite loop. 

The package gets installed and the little script loops away.  I know this by opening a session and visually inspecting the package install location.

My issue is the console states the run command is "In Progress" for a long time.  I'm trying various timeouts to try and understand what actual times are doing. 

What steps should a package install.sh complete to inform the run command the installations is complete?

Thanks

**Comment by mmendonca3** [comment]
Hi muellerk22, 

Thanks for your interest in Distributor. In order for Run Command to complete the request, the install script would need to return, which is not happening here on account of the infinite loop. 
Is there a specific reason you want to add the infinite loop? 

Systems Manager provides a way of scheduling installs by using associations. More information can be found here - https://docs.aws.amazon.com/systems-manager/latest/userguide/distributor-working-with-packages-deploy.html#distributor-smdeploy-pkg-cli (Using CLI) and https://docs.aws.amazon.com/systems-manager/latest/userguide/distributor-working-with-packages-deploy.html#distributor-deploy-sm-pkg-console (Using Console). 

We have also newly launched a Console only, simplified package creation feature, that might be of help to you - https://aws.amazon.com/about-aws/whats-new/2019/07/aws-systems-manager-distributor-makes-it-easier-to-create-distributable-software-packages/. 

Please reopen this issue if you have further questions.
