### ISSUE TITLE
start-session fails for users starting with "test"

### ISSUE THREAD

**Issue by jeremyhage** [aws/amazon-ssm-agent#193]
It seems that the command "aws ssm start-session" does not work for users starting with "test". It gives the error below. I made several tests with multiple users names (with the same administrator permissions) and all users beginning with "test" fail and not the other ones. 

> Starting session with SessionId: testuserssm-0d1a9d71fXXXXXXXX
> 
> 
> SessionId: testuserssm-0d1a9d71fXXXXXXXX :
> ----------ERROR-------
> Setting up data channel with id testuserssm-0d1a9d71fXXXXXXXX failed: failed to create websocket for datachannel with error: CreateDataChannel failed with no output or error: createDataChannel request failed: unexpected response from the service {"Output":{"__type":"com.amazon.coral.service#UnknownOperationException"},"Version":"1.0"}`

**Comment by cdechery** [comment]
Quite the unusual bug. Happens to me to.

**Comment by nitikagoyal87** [comment]
Thanks for reaching out. We are aware of this issue and actively working to deploy the fix. Could you please let us know the region your instances belong to?

**Comment by jeremyhage** [comment]
My instances belong to eu-west-1.

**Comment by nitikagoyal87** [comment]
This issue has been fixed for eu-west-1 region. Kindly let us know in case of any further issues.

**Comment by jeremyhage** [comment]
Thanks! It works fine.

**Comment by oorwinlabs** [comment]
Team, 

Mumbai region also same issue we are facing..please can you help on this ?

**Comment by oorwinlabs** [comment]
I am getting below issue while connecting to ssh agent

Your session has been terminated for the following reasons:  ----------ERROR------- Setting up data channel with id root-0fa7ec469462e8... failed: failed to create websocket for datachannel with error: CreateDataChannel failed with no output or error: createDataChannel request failed: failed to make http client call: Post https://ssmmessages.ap-south-1.amazonaws.com/v1/data-channel/root-0fa7ec469462e8..: dial tcp: lookup ssmmessages.ap-south-1.amazonaws.com: Temporary failure in name resolution

**Comment by vidhimultiqos** [comment]
for region us-east-2 same issue is happening

**Comment by youssouphSagna** [comment]
same issue in the Paris (eu-west-3) region
