### ISSUE TITLE
Build Fails & Build Process

### ISSUE THREAD

**Issue by AndrewNeudegg** [aws/amazon-ssm-agent#201]
## Description

The build process is broken in master. Following the instructions:
```sh
git clone https://github.com/aws/amazon-ssm-agent.git
make
```

Will result in:

```
± |master ✓| → make 
/.../amazon-ssm-agent/Tools/src/checkstyle.sh
Run checkstyle script
Run 'gofmt'
Error: Found files not formatted by gofmt
/.../amazon-ssm-agent/agent/agentlogstocloudwatch/cloudwatchlogspublisher/cloudwatchlogs_publisher_test.go
/.../amazon-ssm-agent/agent/rip/riputil.go
/.../amazon-ssm-agent/agent/s3util/riputil.go
/.../amazon-ssm-agent/agent/session/datachannel/datachannel.go
Please run 'gofmt -w' for files listed.
make: *** [checkstyle] Error 1
```

These errors are present in the latest tag also. We have mitigated for these problems by patching the make file so that the `checkstyle` block reads:

```
checkstyle::
#   Run checkstyle script
	$(BGO_SPACE)/Tools/src/checkstyle.sh || true
```

This modification should not be required.

## Proposed Changes

1. Linting errors should be resolved in the following files:
```
  1. `amazon-ssm-agent/agent/agentlogstocloudwatch/cloudwatchlogspublisher/cloudwatchlogs_publisher_test.go`
  2. `amazon-ssm-agent/agent/rip/riputil.go`
  3. `amazon-ssm-agent/agent/s3util/riputil.go`
  4. `amazon-ssm-agent/agent/session/datachannel/datachannel.go`
```
2. The build process should be tested prior merging into master, and commits should be tested before tagging.

## Why is this important?

We deploy our K8s clusters on CoreOS and build the SSM agent on node reboot. If the agent fails to build out of the box our nodes are not accessible through the AWS web interface.

## Important Information

Tested on `go1.12.5 darwin/amd64` and `go version go1.10 darwin/amd64`.

**Comment by AmyZhangAmz** [comment]
Hi @AndrewNeudegg , 
We're investigating this known issue. The failure might be caused by golang 1.9. Please track the update from this issue. https://github.com/aws/amazon-ssm-agent/issues/177 

Thanks
