### ISSUE TITLE
SSM agent in forever hibernating state

### ISSUE THREAD

**Issue by ppsdeng** [aws/amazon-ssm-agent#202]
I didn't attach the correct EC2 instance role at the first place, and replace it 2 days later with the correct one.

However, in the SSM agent log (/var/log/amazon/ssm/hibernate.log), it shows 5 attempt since my instance starts, at 0min, 30mins, 1h, 2h, and 3h, and never the instance never being able to be managed by SSM.

Is that a configuration requirement that I need to change some config file like in /etc/amazon/ssm/amazon-ssm-agent.json.template ? to make the attempts never stop forever.

or anything we can kick off or reset the SSM agent timer upon change of IAM policy ?

**Comment by hiimtu** [comment]
You can restart the agent to instantly retry the agent connection to SSM. The hibernation will do backoff starting a 5 minutes exponentially to 1 hour intervals. 

If you are on Windows, we have identify issues with hibernation that causes agent to get stuck (Missing Region or fingerprint does not match). We have bug fixed this and pushed out a new agent today.

If you are still experiencing hibernation problems please let us know after you update to the latest agent version [2.3.697.0] and open a new issue.

**Comment by gitcli** [comment]
Hi,

I’ve configured the instance to be no access that no way to login via key pair.

Once the instance is in hibernation state, I’ve no way to login back to restart the agent at all.

So one of the walk around would be disabling ssm agent from entering the hibernation stage, is that configurable by user like from a configuration file ?

**Comment by davisford** [comment]
@hiimtu I also very much would like to *disable* hibernate mode.  We want to get fast status updates on the device's status in the field.  We cannot wait 5m or 1h or more.  How can we disable hibernate mode like @gitcli asked?
