### ISSUE TITLE
Bad SSM agent published

### ISSUE THREAD

**Issue by Cyberax** [aws/amazon-ssm-agent#205]
It seems that the agent published at https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb does not correspond to any publicly available source code.

In particular, the version published on S3 fails to generate hardware fingerprint if either dmidecode or diskinfo fails. The latest available version in repository does NOT have this logic: https://github.com/aws/amazon-ssm-agent/blob/master/agent/fingerprint/hardwareInfo_unix.go

Please, roll back the published binary version immediately and please create a CoE.

**Comment by hiimtu** [comment]
Hi,

Please use binary to mitigate your registration of new managed instance for the time being:
https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/2.3.687.0/debian_amd64/amazon-ssm-agent.deb

Apologize for any inconvenience. We will work on fixing issue for the published binary version.

**Comment by hiimtu** [comment]
Hi,

We have updated the latest binary.

Apologize for the inconvenience.
