### ISSUE TITLE
The version of SSM Agent on this instance doesn't support Run As. Update to latest SSM Agent before continuing.

### ISSUE THREAD

**Issue by slaphead** [aws/amazon-ssm-agent#207]
I get this error when trying to start a session:

`The version of SSM Agent on this instance doesn't support Run As. Update to latest SSM Agent before continuing.`

It is on an ubuntu instance and it seems the session manager version is not the newest according to the console:
2.3.662.0

I am unable to update it to the latest version mentioned in this repo (https://github.com/aws/amazon-ssm-agent/tree/2.3.701.0) as the snap refresh shows this:
```
snap refresh amazon-ssm-agent
snap "amazon-ssm-agent" has no updates available
```
I tried removing the ssm agent and resinstalling it. It installed the same version again:
```
amazon-ssm-agent 2.3.662.0 from Amazon Web Services (aws✓) installed
```
I am unable to find any documentation on how to proceed with this. Please could I get some help or more info on how to either update the ssm version or get the session to start correctly.

**Comment by CameronBeeler** [comment]
@ of January 2021 (maybe before)
Navigate to AWS Systems Manager
Navigate to the 'Node Manager' drop down (Left navigation bar)
Select 'Fleet Manager'
Select the instance in question
Select the "Account Management" drop down (top right)
Select "Auto-Update SSM Agent"

This will rapidly update the SSM Agent ( and keep it updated ) and you will then be able to rapidly access your instances via SSM.

Good luck!
