### ISSUE TITLE
Feature request: Forward to remote port

### ISSUE THREAD

**Issue by sveniu** [aws/amazon-ssm-agent#208]
Add feature to forward to remote port, i.e. having the SSM agent connect to a remote host/IP rather than localhost. This would allow ssm session manager to use an instance as a TCP proxy to reach other instances or endpoints in the VPC, akin to `ssh -R local_port:remote_ip:remote_port`.

Forward to local port was added in fb514243, and it seems it would be fairly straight forward to add forwarding to remote port, too, using the same approach?

**Comment by jimilinuxguy** [comment]
@sveniu Would/Could ssh over ssm using ProxyCommand accomplish this?

**Comment by sveniu** [comment]
Good point, seems like it would indeed.

**Comment by jimilinuxguy** [comment]
@sveniu let me know if that doesn't work for you and i can brainstorm some options. It seems like you are making a bastion host with SSM correct?

**Comment by talawahtech** [comment]
I am interested in this feature as well. Would be useful for forwarding ports to RDS instances.

**Comment by waffie1** [comment]
+1 for me as well, to forward to RDS instances.  ProxyCommand works, but still requires a valid user/keypair for the tunneled ssh -L.   Ideally I would like to control access via IAM and not have to distribute keypairs.

**Comment by candrews** [comment]
First, I agree that this feature would be awesome.

> ProxyCommand works, but still requires a valid user/keypair for the tunneled ssh -L.

As a workaround, use this as your ProxyCommand: https://gist.githubusercontent.com/qoomon/fcf2c85194c55aee34b78ddcaa9e83a1/raw/59286cadad054018012fe22ed23379729cb893a9/aws-ssm-ec2-proxy-command.sh
It copies your public key to to the EC2 using SSM run commands, eliminating the need to manually manage/distribute keypairs.

**Comment by rdkls** [comment]
Agree
Another option, if your client is linux is ssm-tunnel https://github.com/mludvig/aws-ssm-tools

It requires you install the ssm-tunnel-agent on the ssm-managed host
and changes your client networking setup to forward traffic for AWS private CIDR over the tunnel

I've also had some luck with e.g. `socat -v TCP4-LISTEN:9999,fork,reuseaddr TCP4:172.16.8.56:80` on the ssm-managed host, then `aws ssm --document-name AWS-StartPortForwardingSession ...` to that
but it's not super-nice :)

I'd really like to get the source for the AWS-StartPortForwardingSession Document to see if I could easily wrap this method in such & distribute for easy use.

**Comment by clearwaterstream** [comment]
This would be very handy. When developing on local machine, I *could* install MySQL, locally. But so would tens of other developers. Alternatively, via SSM port forwarding, we can route our local 3306 port to some RDS instance, saving a bit of time for everyone. We can spin up a bastion per RDS, or have one bastion and forward different ports to different RDS instances ....

**Comment by rdisipio** [comment]
The StartPortForwardingSession command is awesome. However, I noticed that the tunnel gets closed if the connection drops, which in my case is an intended behaviour (I query a postgres db multiple times during the execution of a python script). Is there a way to prevent the tunnel to get closed, e.g. by adding a parameter?

```
  aws ssm start-session --target ${TARGET} --document-name AWS-StartPortForwardingSession --parameters '{"portNumber":["5432"],"localPortNumber":["5433"],:dropConnection":["False"]}'
```

**Comment by itchains** [comment]
Also interested. This is useful in case you have application running bound to private IP instead of localhost/loopback IP, in which case port forward

**Comment by allenatdecisiv** [comment]
Interested as well for the same reasons already presented.

**Comment by clearwaterstream** [comment]
I was able to do it (my workstation -> rds in a private subnet) using ssm! this is what @candrews mentioned in his answer.

https://medium.com/@clearwaterstream/recipe-connect-to-an-rds-database-in-a-private-subnet-from-your-workstation-over-https-c66db6ead9f0

I'm so far content with the solution, but yes if I did not have to do an SSH tunnel: event better!

**Comment by xrage** [comment]
I tried doing this way but no luck..
https://unix.stackexchange.com/questions/579173/timeout-when-connecting-aws-rds-instance-using-amazon-session-manager-with-ec2-i

**Comment by enriquemanuel** [comment]
So I did something like this and kind of worked for me.
I created the following [scripts](https://gist.github.com/enriquemanuel/1362607c815cd4c58db3109df0ee287e) 

so what they do is that the socksproxy.sh file you pass it with 2 arguments (your username) and your MFA token. it then gets an sts token, and then opens a ssh via ssm proxy command.

Then, you can use something like (dbeaver)[https://dbeaver.io/] and you can use proxy command and put 127.0.0.1 and port 2001 and simply point to your RDS without any problem.

Obviously you need the of the RDS to accept traffic from the SG of the SSM Proxy Instance(s)

Hopefully this helps someone, but this helped the team to do things like proxying to an RDS, EC2 instance and even Redshift (with limitations) and also allowed us to have a proxy to use with Foxy Proxy with the right config in the EC2 instance with some DNS servers

**Comment by clearwaterstream** [comment]
@xrage you need to use AWS-StartSSHSession instead (see one of my posts above).

**Comment by chefren** [comment]
This has been published recently by AWS also: [here](https://aws.amazon.com/premiumsupport/knowledge-center/systems-manager-ssh-vpc-resources/)

However, this feature is still required if creating instances without key pair, so you can use tunnels in bastions that are also only accessible via Session manager and not SSH

**Comment by seemantk** [comment]
+1 for this feature request.  I'd love to switch off sshd on instances entirely

**Comment by mwa21** [comment]
+1, right now need to use socat to bind RDS remote port to ssh step server. The solution with startSSHsession does not work for me since I want to use a SSO to connect to instances and not the pem files.

**Comment by lqueryvg** [comment]
This feature is definitely still needed.
We shouldn't require an EC2 key pair.

**Comment by nitikaaws** [comment]
Thanks for your feedback! We have noted your requests.

**Comment by chefren** [comment]
Hi @nitikaaws, was this closed because it's already released?

**Comment by sgsollie** [comment]
Hey @nitikaaws I see you've noted everyone's feedback and closed this issue but is this feature request actually being implemented?
This would really help us out. (forwarding to remote ports in a VPC, with no need to put keys on a bastion)

**Comment by ghost** [comment]
Need this feature as well as it will simplify accessing RDS.

**Comment by magJ** [comment]
I've opened PR #389 to implement support for this, it was actually really simple to do.
If you are willing to jump through some hoops(compiling your own ssm-agent, creating our own session documents), you could use it now.

**Comment by followben** [comment]
Why is this even closed?

**Comment by damonmaria** [comment]
The [latest release](https://github.com/aws/amazon-ssm-agent/releases/tag/3.1.1188.0) of SSM Agent mentions:
> Added support for port forwarding to remote host

But I can't see any new parameters in the `AWS-StartPortForwardingSession` document. Is everything in place for this? How do we use it?

**Comment by followben** [comment]
@damonmaria see #389 for a discussion. In short: updated code has been released but is not yet distributed to System Manager's s3 buckets. Until that happens you still need to build and deploy version 3.1.1188.0 from source.

Once you've done that (or waited until the release propagates), you then create a custom document as per @magJ's original PR description and connect in the manner he describes. I can confirm this all works having done the same last night :)

**Comment by tbugfinder** [comment]
Today I noticed that SSM 3.1.1188 can be installed and a new SSM document AWS-StartPortForwardingSessionToRemoteHost.
Unfortunately it doesn't work, yet - maybe it's just a matter of days, until some AWS internal config is rolled out?

**Comment by chrismazanec** [comment]
anyone had luck getting `AWS-StartPortForwardingSessionToRemoteHost` to work? I'm getting this:

`An error occurred (BadRequest) when calling the StartSession operation: Currently, port forwarding sessions to remote hosts are not supported.`

**Comment by NicolajKN** [comment]
@chrismazanec I'm getting the same thing with v3.1.1188 (latest version according to Yum). This is frustrating since [the docs](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-sessions-start.html#sessions-remote-port-forwarding) say you just need 3.x. The [agent changelog](https://github.com/aws/amazon-ssm-agent/blob/mainline/RELEASENOTES.md) has newer versions but doesn't seem to mention this at all. 

I don't know how SSM Documents work but this one (AWS-StartPortForwardingSessionToRemoteHost) seems to have been publish May 12th and has no updates. Could something be wrong with the document?

**Comment by allenatdecisiv** [comment]
Looks like the SSM Agent version needs to be 3.1.1374.0 or higher:
https://aws.amazon.com/about-aws/whats-new/2022/05/aws-systems-manager-support-port-forwarding-remote-hosts-using-session-manager/

**Comment by NicolajKN** [comment]
I can confirm that this works with newer versions of the SSM Agent (for me v3.1.1446.0). Just don't rely on `yum upgrade` to get the newest version, instead I had to run:

`sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm`

As per [this part](https://docs.aws.amazon.com/systems-manager/latest/userguide/agent-install-al2.html#quick-install-al2) of the documentation.
