### ISSUE TITLE
Enabling fast-fail on health check

### ISSUE THREAD

**Issue by davisford** [aws/amazon-ssm-agent#210]
Hi, we're testing monitoring RPi devices through a lambda function that tests the managed instance state of `offline` / `online`.  We want to know as fast as possible if a device has changed its state, but it seems there is some considerable delay in our real-world testing of unplugging a device from the network and waiting for it to go offline in System Manager console....like several minutes before it detects it is offline.

Is there a way we can configure the agent to fail immediately or as quickly as possible?

**Comment by shihuazhang** [comment]
Thanks for your interest about amazon ssm agent. We’ll work on this feature request.
