### ISSUE TITLE
Add support for assuming role via Web Identity Token

### ISSUE THREAD

**Issue by alexei-led** [aws/amazon-ssm-agent#211]
Update to latest `aws-sdk-go` to support assuming role via Web Identity Token. Essential when running SSM agent in Docker container on EKS or another K8s cluster.

**Comment by shihuazhang** [comment]
Thanks for your interest about amazon ssm agent. We’ll work on this feature request.

**Comment by nithu0115** [comment]
@shihuazhang Is this issue resolved ?

**Comment by Thor-Bjorgvinsson** [comment]
We've updated to aws-sdk-go v1.41.4 in this commit: https://github.com/aws/amazon-ssm-agent/commit/e5c6aa8ba7734b78c0b168203d9f9960da381927
