### ISSUE TITLE
Fix startup delay on managed instances

### ISSUE THREAD

**Issue by Cyberax** [aws/amazon-ssm-agent#215]
Right now there's a 50 second registration delay on managed on-premises instances, as SSM tries to reach the metadata endpoint (which doesn't exist on on-premises instances).

There's a 2-line patch to fix it: https://github.com/aws/amazon-ssm-agent/pull/206

Please, merge it into the next release so we can stop building it ourselves.

**Comment by hiimtu** [comment]
Hi @Cyberax, we merge your changes and released in 2.3.722.0.

Thanks for this contribution!
