### ISSUE TITLE
How can I get managed instance ID?

### ISSUE THREAD

**Issue by naoty** [aws/amazon-ssm-agent#216]
Hi, contributors,

I'm trying to register a ECS task as a managed instance with amazon-ssm-agent. When deregistering the ECS task from managed instances, I will need the managed instance ID. But I'm not sure how to get a managed instance ID.

I found that `aws ssm describe-instance-information` returns managed instance IDs, but I want to know the managed instance ID registered by a specific amazon-ssm-agent, not all IDs.

How can I get the managed instance ID registered by amazon-ssm-agent?

**Comment by hiimtu** [comment]
Hi,

On the instance, the managed instance id is store in the following file on unix systems:
 **/var/lib/amazon/ssm/registration** 

You can get the managed instance ID from there.

**Comment by naoty** [comment]
Sorry for late response. Thanks!

**Comment by bendavidpaz** [comment]
This folder, /var/lib/amazon/ssm/registration, does not exist on the instance that I would like to deregister.  Please advise how to deregister the managed instance.

**Comment by shihuazhang** [comment]
@bendavidpaz 

Could you please see if you can find the /var/log/amazon/ssm/amazon-ssm-agent.log, you should be able to find the managed instance id there.

**Comment by kevwargo** [comment]
The `/var/lib/amazon/ssm/registration` folder exists only on Hybrid instances (with `mi-*` IDs), EC2's have different IDs - `i-*` which are the same as EC2 instance ID and can be retrieved from the instance metadata: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html
