### ISSUE TITLE
Are there reference cloudformation implementations available anywhere?

### ISSUE THREAD

**Issue by ajhool** [aws/amazon-ssm-agent#218]
There are a handful of tutorials for setting up an ssm agent and they can involve a significant number of moving parts. Specifically, I would like to create an instance in a private subnet and access it via SSM. That requires an IAM role, a handful of VPC endpoints, maybe an S3 bucket, and various other steps.

Is there a cloudformation template demonstrating the correct networking, vpc endpoints, and IAM roles required for spinning up an EC2 instance in a private subnet that can be controlled using SSM (run command + port forwarding/tunneling)?

**Comment by shihuazhang** [comment]
Hi @ajhool 
I think the tutorials you are asking is pretty much about setting up EC2. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-vpce-bucketnames.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-endpoints.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-iam-template.html

https://docs.aws.amazon.com/codebuild/latest/userguide/cloudformation-vpc-template.html

Once you have the EC2 setup properly, onboarding SSM is easy
