### ISSUE TITLE
Documentation for the directives in the amazon-ssm-agent.json.template file

### ISSUE THREAD

**Issue by ChrisPr1** [aws/amazon-ssm-agent#220]
I'm looking for documentation on the various directives in amazon-ssm-agent.json.template, and specifically the 'Profile' section.

**Comment by hiimtu** [comment]
#182 Hi this existing issue may help you.

For the Profile section, I believe that is used to create the a shared credential file from the managed instance credentials that delivered by SSM.

You can confirm and trace the logic if you want to explore further: https://github.com/aws/amazon-ssm-agent/blob/master/agent/appconfig/appconfig.go

**Comment by ChrisPr1** [comment]
Ive traced the logic as best as I'm able (not that familiar with go) and am really no further along.

I'm specifically wanting information on the valid settings for the 'ShareProfile' setting in the 'Profile' stanza

```
"Profile":{
        "ShareCreds" : true,
        **"ShareProfile" : ""**
    },
```

section.

**Comment by hiimtu** [comment]
For the ShareProfile section, it will copy the managed instance credentials that the agent is getting when you register as a hybrid instances to a shared credential file (~/.aws/credentials). The ShareProfile is the name of the profile [default] is the default.

I believe you can also change the file location of the store credential by setting env variable: AWS_SHARED_CREDENTIALS_FILE

https://github.com/aws/amazon-ssm-agent/blob/9c45ca6b51a69ed16f58d96f960d86e6490a6d6d/vendor/src/github.com/aws/aws-sdk-go/aws/credentials/shared_credentials_provider.go#L117-L136

Documentation on shared credential file.
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/create-shared-credentials-file.html
