### ISSUE TITLE
SSM `AWS-StartPortForwardingSession` error with Elasticsearch behind Nginx proxy

### ISSUE THREAD

**Issue by macedogm** [aws/amazon-ssm-agent#221]
I have configured an EC2 instance with Amazon Linux 2 (4.14.123-111.109.amzn2.x86_64), Nginx (1:1.12.2-2.amzn2.0.2) and amazon-ssm-agent-2.3.714.0-1.x86_64. This Nginx is working as a proxy to an AWS Elasticsearch inside my VPC.
I tried to connect using the AWS-StartPortForwardingSession document from AWS SSM (1.1.33.0) running on Mac, but it does not works. I tested with Safari, Firefox and Chrome and the Kibana dashboard keeps loading indefinitely and sometimes the connection just brake and is interrupted.
I exposed this Nginx through a public port and the proxy to Elasticsearch works as expected.
Please let me know what kind of logs can I provide, because from the current logs there is no clear error.

**Comment by bradkwadsworth** [comment]
I'm seeing this as well with http connections that has to load javascript files

**Comment by kgrodzicki** [comment]
I have the same issue. It just loads indefinitely. The webpage has some js files to load. There is no errors in session-manager-plugin logs. 

Command:
`aws ssm start-session --target i-...! --document-name AWS-StartPortForwardingSession --parameters '{"portNumber":["80"],"localPortNumber":["9999"]}'`

Session-manager-plugin is 1.1.54.0.

**Comment by ranjrish** [comment]
@macedogm Could you update to the latest agent version and check if the issue persists?

**Comment by macedogm** [comment]
@ranjrish Sorry, but I'm not using this setup anymore, so I can't test it.

**Comment by mwakerman** [comment]
Adding this comment for people that get here from Google: This is an issue caused by StartPordForwardingSession only allowing a single http connection to be forwarded. We got around this with nginx and configuring it to use the http2 protocol (also requires ssl/tls, I think) which multiplexes many connections over a single connection. I'm on mobile now but I saw an update to ssm-agent that looked like it now supported multiple connections but haven't tested it.

**Comment by nitikaaws** [comment]
Port Forwarding feature now supports multiple simultaneous connections over the session. Please upgrade to latest version of Session Manager Plugin and SSM Agent to use this enhancement. Let us know in case of further issues.

https://aws.amazon.com/about-aws/whats-new/2020/10/port-forwarding-sessions-created-sessions-manager-support-multiple-simultaneous-connections/
