### ISSUE TITLE
Agent does not auto-start on raspbian

### ISSUE THREAD

**Issue by rudpot** [aws/amazon-ssm-agent#222]
amazon-ssm-agent (2.3.714.0-1) installed on raspbian buster works but will not auto-start. The issue is that raspbian does not have a `network-online.target`. Remediation (as root): 

```
sed -i 's/network-online.target/network.target/' /lib/systemd/system/amazon-ssm-agent.service
systemctl reenable amazon-ssm-agent
reboot
```

**Comment by shihuazhang** [comment]
Thanks for your feedback, https://docs.aws.amazon.com/systems-manager/latest/userguide/prereqs-operating-systems.html
SSM Agent doesn't support raspbian buster at the moment.
