### ISSUE TITLE
Change SSM Endpoint

### ISSUE THREAD

**Issue by imcoltanmay** [aws/amazon-ssm-agent#223]
Currently I am trying to do cross region SSM to manage EC2 instance.
By investigating on google I got an information that I can do cross region SSM by using Hybrid instance however I am trying to change SSM endpoints in EC2 forcefully to manage by other region SSM.

Example :- My EC2 is running on US-East-1 so SSM agent will point on US-East-1 but is there any way to change SSM endpoint. I have tried to change in JSON file which is present in program files but no luck.

**Comment by hiimtu** [comment]
Hi, have you tried creating an activation in the other region?

Also, when you run the register command, you pass in a region which will determine the endpoint the agent will call to register.

**Comment by imcoltanmay** [comment]
@hiimtu, With the hybrid activation it can be done but i am looking for other ways to do this.

**Comment by imcoltanmay** [comment]
I want to know how we can make changes in agent json file to explicitly call other region ssm endpoint

**Comment by hiimtu** [comment]
For EC2 instances, the agent uses the instance metadata to retrieve the instance id. The EC2 instance ID are region specific, so I do not think this is possible.
