### ISSUE TITLE
Slow SCP transfer speeds

### ISSUE THREAD

**Issue by awiddersheim** [aws/amazon-ssm-agent#227]
I am seeing slow SCP transfer speeds. Specifically when transferring files `1MB` or more. Anyone else seeing these issues? I'm using the latest `session-manager-plugin` and SSM agent.

```
$ session-manager-plugin --version
1.1.33.0
```

```
2019-10-14 12:01:25 INFO amazon-ssm-agent updated successfully to 2.3.722.0
```

I have a case open with AWS but hoping I'm not the only one on this and can get some traction on fixing this or maybe it is just me.

**Comment by hutchiko** [comment]
I am seeing similar issues - SCP transfer speeds are very slow and we also see very slow speeds through SSH tunnels using the SSM agent.

**Comment by awiddersheim** [comment]
@hutchiko Thanks for posting. What speeds are you seeing? I'm getting double digit `KB/s`.

**Comment by hutchiko** [comment]
We see the transfer start out at around 30KB/s but then quickly drop down to 4KB/s as the steady state.

**Comment by hutchiko** [comment]
If we do `scp` over a direct SSH connection (no SSM proxy) we are seeing 2MB/s to the same instance.

**Comment by awiddersheim** [comment]
I had a convo with AWS support. Apparently there was an issue on their end limiting speeds for whatever reason that has not been fixed to a degree.
