### ISSUE TITLE
aws SSM 

### ISSUE THREAD

**Issue by itamarka9** [aws/amazon-ssm-agent#230]
Hello,

I am using TFS to release my program to my EC2 instances.
In order to do that I use AWS addons to TFS.
At one point I use SSM to start a remote script on my EC2 instance.
I some cases my deployment process failed because the SSM agent was stopped for some reason.
I have used  AWS SSM get-connection-status --target "i-12345676789" --query  "Status" to get the connection status but this command does not  return a standard return code (%errorlevel%) but a text "connected" or  "notconnected".

I have written a batch file to test the issue and it works but the problem is that I need to hard code
All the AWS connection parameters 
There is a option to use AWS shell script  
Can this script be written in AWS BASH ?
The Target ID will provided via a parameter   
================================================================
For /F "Tokens=1" %%I in ('aws ssm get-connection-status --target "i-1234567890" --query  "Status"') Do Set constat=%%I
set excode=99
if  %constat%=="notconnected" set excode=1
if  %constat%=="connected" set excode=0
exit /b %excode%
=============================================================

Thanks

Itamar

**Comment by shihuazhang** [comment]
Hi 

aws ssm get-connection-status --target "i-1234567890" --query "Status"' is an API call, it return Status String such as "connected" or "notconnected"

Yes, you can use Bash for this

**Comment by hiimtu** [comment]
Hi, closing issue. Please reopen or open a new issue if you have anymore questions.

Thanks!
