### ISSUE TITLE
Support for Fargate Credential Provider

### ISSUE THREAD

**Issue by andrewkrug** [aws/amazon-ssm-agent#231]
It would be great to see the credential provider chain leverage the TaskRole creds available at: 
`http://169.254.170.2/v2/credentials/<GUID>`.  This would enable the ssm-agent to register from inside of Fargate.  K8s already can be made to work using metadata proxy sidecars.

**Comment by shihuazhang** [comment]
Thanks for your interest about amazon ssm agent. We’ll work on this feature request.
