### ISSUE TITLE
session logs not pushed to s3 in case of ec2 stop/termination

### ISSUE THREAD

**Issue by amit-handda** [aws/amazon-ssm-agent#232]
we wanted to adopt ssm service for compliance perspective. we ran a few tests for the same. we are looking to save session logs to s3 bucket.
ssm-agent pushes logs successfully on clean session exit. however, if a instance is stopped/terminated during active session, logs are not pushed.
As per our understanding, the ssm-agent service should have gracefully handled the instance stoppage, and pushed out the session logs to s3 bucket.

**Comment by eriksw** [comment]
Issue #153 is mostly the same as this.

Given the lack of response to that almost year-old bug and disregard for other issues relating to session logs upload (#197, #178), it's pretty clear that session logs are a non-priority for Amazon, which is extremely disappointing.

**Comment by Baalakay** [comment]
Just saw that the PFR for streaming from console to Cloudwatch was released yesterday (11/18/20)

**Comment by nitikaaws** [comment]
Thanks for your feedback! We have noted this request. Session Manager now supports continuous streaming of logs to CloudWatch which should potentially address the concern raised for S3 logging. More details can be found in below documentation. Please let us know in case of further queries.

https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-logging.html#session-manager-logging-cwl-streaming
