### ISSUE TITLE
IMDSv2 support

### ISSUE THREAD

**Issue by mtanda** [aws/amazon-ssm-agent#238]
I'm interested about the schedule when ssm-agent migrate to IMDSv2.
https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/

The ssm-agent shouldn't have SSRF, but it could be blocker if user opt in to require that IMDSv2.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html
```
aws ec2 modify-instance-metadata-options --instance-id i-1234567898abcdef0 --http-tokens required
```

**Comment by shihuazhang** [comment]
Thanks for your interest about amazon ssm agent. We’ll work on this feature request.

**Comment by mtanda** [comment]
Thank you for upgrading AWSSDK!

https://github.com/aws/amazon-ssm-agent/commit/e093a9acf713fc0c7f694091e71e9200e5c79d5a
