### ISSUE TITLE
Feature request: Allow specifying IP for AWS-StartSSHSession

### ISSUE THREAD

**Issue by mtekel** [aws/amazon-ssm-agent#240]
Currently AWS-StartSSHSession document only takes port parameter. This allows specifying different _local_ port for ssh connection. Allowing to specify IP address, it would be possible to connect to other VMs and use ssm target host as jump/proxy. The advantage is that the jump host won't have to have port 22 exposed, or even any ssh daemon running. And you can control user access via IAM.

I believe that after https://github.com/aws/amazon-ssm-agent/issues/208 is implemented, this should be fairly easy to do as well.

**Comment by chefren** [comment]
Looks like this actually duplicates #208 ? What would be the difference?

**Comment by nitikaaws** [comment]
Thanks for your feedback! We have noted your requests.
