### ISSUE TITLE
SSM agent logs sometimes emit format strings verbatim

### ISSUE THREAD

**Issue by nonspecialist** [aws/amazon-ssm-agent#242]
There are some locations in the SSM agent where, instead of using the `f` function call (`Debugf`, `Infof`, `Warnf` etc) the "plain" call is used even though there are format strings and arguments in the function call. This leads to error messages which contain actual `%v` and `%s` strings, and badly-formatted and harder to read errors.

This is present at least from v2.3.760.0 and probably earlier too

**Comment by ferkhat-aws** [comment]
This has since been fixed. 
Closing.
