### ISSUE TITLE
Snap auto-refresh overrides amazon-ssm-agent AWS-UpdateSSMAgent installed version

### ISSUE THREAD

**Issue by luiszimmermann** [aws/amazon-ssm-agent#255]
When using the default Ubuntu 18.04 LTS AMI, the snap auto-refresh overrides amazon-ssm-agent AWS-UpdateSSMAgent installed version.
This happens because the snap is tracking `stable` and the version installed using AWS-UpdateSSMAgent is in the `candidate`.

**Comment by RuoyiZeng** [comment]
Hi,
 
Thank you for reaching out to us.


You could install the latest agent from the candidate channel using:

sudo snap install --channel=candidate amazon-ssm-agent --classic 


Or you could also consider changing the channel on current agent using:

sudo snap switch --channel=candidate amazon-ssm-agent


Then you can manually perform refresh or wait for the auto refresh.

sudo snap refresh amazon-ssm-agent


As for the stable channel, there is no clearly defined schedule at this moment.

For more information, please visit https://snapcraft.io/docs/channels.

**Comment by luiszimmermann** [comment]
I used the System Manager Run Command `AWS-RunShellScript` to execute in the affected resources:
```
sudo snap switch --channel=candidate amazon-ssm-agent
sudo snap refresh amazon-ssm-agent
```

Thanks for your help.

**Comment by rromanchuk** [comment]
so is `AWS-UpdateSSMAgent`  actually using the the recommended install method for ubuntu 20 arm64  (snap) or trying to execute a run command that goes around the package manager all together? 

https://docs.aws.amazon.com/systems-manager/latest/userguide/agent-install-ubuntu.html
https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-agent-automatic-updates.html
