### ISSUE TITLE
Windows AD DomainJoin ignoring OU parameter

### ISSUE THREAD

**Issue by mikepugh** [aws/amazon-ssm-agent#26]
I've recently tried to use SSM to join two Win 2016 Servers to our domain. In both instances I specified a specific target OU but in both cases the servers ended up in the default "Computers" OU for the domain.

We are using an AD Connector domain and the public "AWS-JoinDirectoryServiceDomain" SSM document.

**Comment by chanjeon** [comment]
Hi mikepugh,
Thank you for posting here. This is a known bug in SSMAgent and our team is currently investigating the issue. Our team will fix this as soon as possible and update here once we have the fix or ETA.

**Comment by chanjeon** [comment]
Our team has fixed the issue and it'll be included in the next release. Thank you!

**Comment by mikepugh** [comment]
That's great, thanks for the update!

**Comment by shihuazhang** [comment]
This issue has been addressed in the latest build
Feel free to reopen the issue if you have more question
