### ISSUE TITLE
Configurable timeout for Session Manager sessions on the CLI

### ISSUE THREAD

**Issue by tdmalone** [aws/amazon-ssm-agent#261]
Apologies if this is not the right place to request this.

I was wanting to request the ability to configure the Session Manager session timeout when connecting via CLI.

When performing long-running jobs such as database imports - and therefore not actively interacting with the terminal - I'm occasionally seeing this:
```
SessionId: tim.malone-097bc8bd07a0dee95 : Your session timed out due to inactivity and has been terminated.
```
before the job has been completed.

Would it be possible to configure (or even remove) this timeout?

**Comment by ElijahLynn** [comment]
Getting this too and your post is top for a search of `"Your session timed out due to inactivity and has been terminated" aws ssm`. Mine times out after 30 minutes of a long running option and only solution is to use `screen` to background it so it completes. It is a workaround but high friction. It should detect that the terminal isn't idle.

**Comment by analogrithems** [comment]
I can't even find in the code where the session timeout is set.  I think this could be a server side setting.

**Comment by vivek-jain-mt** [comment]
I am also in need of such feature. Is this being addressed? not sure if this is the right portal

**Comment by adamkendall1** [comment]
Yes, please give us the option to select a longer idle timeout. I'm getting tired of recovering files and deleting vim swap files...

**Comment by tdmalone** [comment]
I've had a chat to our SA about this and he's gonna see what he can do to reach out to the Session Manager team.

**Comment by GNOMES** [comment]
@tdmalone did your rep provide you any feedback?

**Comment by tdmalone** [comment]
@GNOMES There's an internal feature request for this and I'm now on the list of customers interested in it, so when there's an update I should hear more. You can probably get yourself added as well via your SA, account manager or possibly Support. If you have an NDA on your account you may also be able to get more information on timelines.

**Comment by harishkashyap** [comment]
+1. ec2 timeout defaults are annoying; what were you thinking when you were developing such a customer focussed tool?

**Comment by crossbam** [comment]
Yes, please add the ability to change the session idle timeout. My machine learning analysts are not happy with the short timeout.

**Comment by khonourhmrc** [comment]
We really should be able to use this as a complete terminal replacement, at the moment you can't run long-running task in this terminal without turning it into a service or some such. Timeout really needs to be configurable we'd really prefer not to have standard ssh access.

**Comment by nitikagoyal87** [comment]
Thanks for your feedback! We will look into this request.

**Comment by leelakrishnachava** [comment]
Good to see that at least the team has identified it and looking forward to seeing a positive response soon.

**Comment by jwagun** [comment]
I am looking forward to this feature too. 👍

**Comment by Johaik** [comment]
Are there any updates about this? I would really appreciate it if it would be

**Comment by kaiw1ng** [comment]
this has been launched:

https://docs.aws.amazon.com/systems-manager/latest/userguide/session-preferences-timeout.html

**Comment by adamkendall1** [comment]
Aaaayyyyyyyyyy!!!! Good job, AWS team!

**Comment by tdmalone** [comment]
Announcement post for the above: https://aws.amazon.com/about-aws/whats-new/2020/11/aws-customize-the-idle-session-timeout-and-stream-session-logs-t/

Next question: how do we configure this programmatically? The new streaming logs enhancement launched at the same time is available via the existing SSM document (https://docs.aws.amazon.com/systems-manager/latest/userguide/getting-started-configure-preferences-cli.html), but the idle timeout does not appear to be represented here.

Update: looks like its `idleSessionTimeout`, with the value provided in whole minutes.

**Comment by robpomeroy** [comment]
I'm using Session Manager to tunnel RDP connections (and also WinRM for Ansible management). Yesterday, two live RDP sessions were forcibly disconnected by a Session Manager timeout. _I was using/interacting with both RDP connections at the time_. So how does Session Manager determine what constitutes 'inactivity'?

Being able to increase the timeout to 60 minutes max is little more than a workaround if SSM kills active sessions without honouring network activity.

**Comment by robpomeroy** [comment]
> Update: Interesting, I went to https://console.amazonaws-us-gov.com/systems-manager/session-manager/sessions to see all open sessions and it has some open from over 12 hours ago that were closed. Maybe this is a bug in the SSM client I am using, I am not using the one AWS published but one that was coded up by someone on our team.

@ElijahLynn - it might not be your client. I'm using the AWS CLI v2 + Session Manager plugin and sometimes I see stale sessions still "active" from days past. The associated activity (SSH/RDP/WinRM) has long since finished.

**Comment by robpomeroy** [comment]
> Update: looks like its `idleSessionTimeout`, with the value provided in whole minutes.

@tdmalone idleSessionTimeout doesn't appear as a parameter in the [AWS-StartPortForwardingSession](https://eu-west-2.console.aws.amazon.com/systems-manager/documents/AWS-StartPortForwardingSession/description?region=eu-west-2) document though. 😕

**Comment by nitikaaws** [comment]
Ability to configure idle session timeout is now supported. Please refer to below documentations for more details.
- https://docs.aws.amazon.com/systems-manager/latest/userguide/session-preferences-timeout.html
- https://docs.aws.amazon.com/systems-manager/latest/userguide/getting-started-configure-preferences-cli.html

In case of issues with active sessions getting disconnected forcibly, please provide us with some more information like sessionId, aws region, ssm agent logs etc to investigate this further. Thanks!

**Comment by DavidAtImpactCubed** [comment]
> > Update: looks like its `idleSessionTimeout`, with the value provided in whole minutes.
> 
> @tdmalone idleSessionTimeout doesn't appear as a parameter in the [AWS-StartPortForwardingSession](https://eu-west-2.console.aws.amazon.com/systems-manager/documents/AWS-StartPortForwardingSession/description?region=eu-west-2) document though. 😕

@robpomeroy , did you work out how to set the session idle timeout for port forwarding sessions? Whilst we have updated the session timeout in the SSM-SessionManagerRunShell document, we are still seeing what appear to be very short inactivity timeouts on port forwarding sessions.

**Comment by robpomeroy** [comment]
@DavidAtImpactCubed - kind of.

In my scenario (working for one of my clients), there was a confounding issue: Windows by default "unloads" the RDP GUI when minimised. My client was running automated testing software on a remote EC2 instance, with the RDP session minimised. Because Windows unloads the GUI, Session Manager saw no interaction (no keepalives) with the remote session and killed it once the timeout was reached. This halted the testing software in its tracks - it needed a live interactive session, to continue.

So part of the fix here was to add a registry key:

* **Path:** HKEY_LOCAL_MACHINE\Software\Microsoft\Terminal Server Client
* **Key:** RemoteDesktop_SuppressWhenMinimized
* **Value:** 2

Additionally, I globally set the session timeout to 60 minutes, per [the documentation](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-preferences-timeout.html).

I don't know if this fixes your problem, but once I had made those two changes, SM stopped killing the port forwarding sessions. If necessary, you might need to use a (no-op) keepalive, to maintain your session? Note that multiple process can now share the same session (they couldn't originally). So you could have two SSH sessions going through the same tunnel, one running a keepalive, the other doing your work.

**Comment by pcpiela** [comment]
I am still seeing short idle timeout behavior for port sessions. We are utilizing the session-manager-plugin code inside a client application that is used to establish port-forwarding connections. I updated the plugin to issue ping messages every 15 sec in an attempt to keep the connection alive; however, after an idle period of 60 sec the session appears to be forcibly closed.

**Comment by robpomeroy** [comment]
> I am still seeing short idle timeout behavior for port sessions. We are utilizing the session-manager-plugin code inside a client application that is used to establish port-forwarding connections. I updated the plugin to issue ping messages every 15 sec in an attempt to keep the connection alive; however, after an idle period of 60 sec the session appears to be forcibly closed.

Could you try something other than ping? Is it possible the ping is being blocked by a firewall rule? Or just ignored?

**Comment by pcpiela** [comment]
Thanks @robpomeroy. The WebSocketChannel is actually send a websocket "ping" message as opposed to an ICMP request.

err := webSocketChannel.Connection.WriteMessage(websocket.PingMessage, []byte("keepalive"))

I could look into adding a pong handler to see if we get acknowledgements.

**Comment by pcpiela** [comment]
When I start the identical ssm port forward session from a Powershell using "aws ssm start-session ..." the session is closed after 20 min of idle which corresponds to the setting in the admin console. For some reason my Go client that utilizes the session-manager-plugin/ssmclicommands package is behaving differently.

**Comment by pcpiela** [comment]
In my client I am using muxPortForwarding. In the code that sets up a connection to the local network listener there is a check as to whether to disable keepalive. In my case keepalive is being disabled. As an experiment I bypassed the check, and there was no longer an issue with the connection being prematurely closed; however, the session idle timeout set in the console was not being honored which is consistent with comments in the code as to why the check was added.

In a separate experiment I logged the initial connection sequence when running aws ssm start-session. In the handshake the server appears to be sending and idleSessionTimeout of 60. Not sure if this is significant.

2023-01-16 14:24:12 DEBUG Processing HandshakeRequest message {%!s(uint32=116) output_stream_data %!s(uint32=1) %!s(uint64=1673897050403) %!s(int64=0) %!s(uint64=1) 084a6ee3-0634-4638-884e-0de79e49615e  0   7	  ] 4 `r  ] -Mw !  P   %!s(uint32=5) %!s(uint32=315) {"AgentVersion":"3.1.1634.0","RequestedClientActions":[{"ActionType":"SessionType","ActionParameters":{"SessionType":"Port","Properties":{"host":"hostname-removed","idleSessionTimeout":"60","localPortNumber":"1433","portNumber":"1433","type":"LocalPortForwarding"}}}]}}
2023-01-16 14:24:12 DEBUG Handshake Complete. Handshake time to complete is: %!s(float64=2.9487522) seconds

**Comment by robpomeroy** [comment]
Looks like an issue with `session-manager-plugin/ssmclicommands`? 🤷‍♂️

**Comment by dhubler** [comment]
I am seeing this as well, so in this commit:
  https://github.com/aws/session-manager-plugin/commit/986e79d69acc1c126c153a32217f435532add18d
it removes keep-alive with the expectation the idle timeout will handle it, but instead my connection doesn't last more than a minute.  If a remove the line that disables keep-alive (effectively enabling keep-alive) then connection survives

**Comment by Stephane-Ag** [comment]
Seems the max you can set is 60 minutes, fyi. Defaults to 20.
Instructions: https://docs.aws.amazon.com/systems-manager/latest/userguide/session-preferences-timeout.html.

And the current link for making this change:
https://us-east-1.console.aws.amazon.com/systems-manager/session-manager/preferences?region=us-east-1
