### ISSUE TITLE
Support adduser on Alpine Linux

### ISSUE THREAD

**Issue by ipmb** [aws/amazon-ssm-agent#267]
While not officially supported, I was able to run `amazon-ssm-agent` on Alpine Linux, register it as a managed instance, and start an interactive session on it.

One issue I did encounter was that the `ssm-user` was not created automatically. I went through the code and noticed it uses `useradd` which is not included in Alpine. Would you consider a PR to detect Alpine or attempt it as a fallback? The command to execute would simply be `adduser -D ssm-user`.

The code in question is here: https://github.com/aws/amazon-ssm-agent/blob/029ce48d3f04d373972fba2bfe80291861c59bd5/agent/session/utility/utility_unix.go#L73-L84

**Comment by shihuazhang** [comment]
Thanks for reaching out. 

We do not have any plan for Alpine Linux. However, we will watch the requests, and reopen this if we see more demands.

I will close this for now, please feel free to re-open this if you have more question.
