### ISSUE TITLE
start-session fails for users starting at our staging server

### ISSUE THREAD

**Issue by TakaraShinya** [aws/amazon-ssm-agent#272]
Starting session with SessionId: XXXXXXXXX-0627c9857b1571d79

SessionId: XXXXXXXXX-0627c9857b1571d79 : 
----------ERROR-------
Setting up data channel with id XXXXXXXXX-0627c9857b1571d79 failed: failed to create websocket for datachannel with error: CreateDataChannel failed with no output or error: createDataChannel request failed: unexpected response from the service <BadRequest xmlns=""><message>964c3550: Request is not authenticated.</message></BadRequest>

**Comment by Haegin** [comment]
@TakaraShinya did you ever solve this? I'm running into the same problem.

**Comment by akashxg** [comment]
@TakaraShinya were you able to resolve this issue? also running into the same problem.

**Comment by nitikaaws** [comment]
Thanks for reaching out! Could you please verify if IAM profile attached to the target instance has permission for ssmmessages:CreateDataChannel? Sample instance profile for Session Manager can be referred in below documentation.
https://docs.aws.amazon.com/systems-manager/latest/userguide/getting-started-create-iam-instance-profile.html

**Comment by thinkst-devdua** [comment]
I have seen a similar SSM error

```
----------ERROR-------
Setting up data channel with id <id> failed: failed to create websocket for datachannel with error: CreateDataChannel failed with no output or error: createDataChannel request failed: unexpected response from the service Server authentication failed: <UnauthorizedRequest><message>Forbidden.</message></UnauthorizedRequest>
```

that @TakaraShinya posted only in cases where the system clock on the EC2 instance is not accurate, i.e. not sync'd with NTP and is off by 5 minutes or more. If this incorrect timestamp is used to sign requests to AWS API and authenticate to an SSM websocket, the request's SigV4 signature [is considered invalid and requests are rejected](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_sigv.html?utm_source=chatgpt.com#:~:text=In%20most%20cases%2C%20a%20request%20must%20reach%20AWS%20within%20five%20minutes%20of%20the%20time%20stamp%20in%20the%20request.%20Otherwise%2C%20AWS%20denies%20the%20request.). As soon as the system clock is corrected, SSM sessions are setup successfully again.
