### ISSUE TITLE
SSM Manager Session API socket messages Issue with On-Prem Instances

### ISSUE THREAD

**Issue by kranthisai** [aws/amazon-ssm-agent#281]
I was trying to connect to SSM on-prem instance from browser shell. I dont see any acknowledgement on input_stream from SSM Manager session api socket messages. I only see message types like pause_publication, start_publication. i dont see any acknowledge messageTypes. However, if I connect to EC2 instance from browser shell, I see acknowledge messages. Am I missing anything?

**Comment by shihuazhang** [comment]
Thanks for reaching out. You need to enable advanced instances before using Session Manager for on-premises instances 

"With advanced on-premises instances, you will also be able to use Systems Manager Session Manager to interactively access your on-premises instances"
https://aws.amazon.com/systems-manager/pricing/
https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-managedinstances-advanced.html

**Comment by kranthisai** [comment]
Yes. We did enable that.

**Comment by kranthisai** [comment]
Just to clarify, using shell from custom application, not with AWS session manager shell.

**Comment by YujiaozhAws** [comment]
Hi, thanks for reaching out. 

pause_publication, start_publication indicates the agent is not connected to MGS. Could you please log into the on-prem instance and fetch the agent log? 

Reference: https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-agent-logs.html
