### ISSUE TITLE
SSM Inventory Plugin attempting to upload to nonexistent s3 bucket

### ISSUE THREAD

**Issue by rdkls** [aws/amazon-ssm-agent#283]
`2020-05-26 00:33:02 ERROR [S3Upload @ s3util.go.105] [ssm-document-worker] [5cbe845f-0f5a-4fd5-b39c-9fa44f1db943.2020-05-26T00-32-29.017Z] [DataBackend] [pluginName=aws:softwareInventory] Failed uploading /var/lib/amazon/ssm/i-070b1aebd1b39fcdc/document/orchestration/5cbe845f-0f5a-4fd5-b39c-9fa44f1db943/2020-05-26T00-32-29.017Z/awssoftwareInventory/collectSoftwareInventoryItems/stdout to s3://ssminventorytest/i-070b1aebd1b39fcdc/5cbe845f-0f5a-4fd5-b39c-9fa44f1db943/2020-05-26T00-32-29.017Z/awssoftwareInventory/collectSoftwareInventoryItems/stdout err:NoSuchBucket: The specified bucket does not exist`

**Comment by shihuazhang** [comment]
It's most likely because you have enabled "Enable writing output to S3"

The bucket you provided most likely doesn't exist

**Comment by rdkls** [comment]
> It's most likely because you have enabled "Enable writing output to S3"
> 
> The bucket you provided most likely doesn't exist

Thanks, I checked and that option isn't enabled:
```
aws ssm describe-association --association-id dc7f5ee5-90ee-4166-b87e-72a0d06a9dbd     Wed 27 May 16:32:35 2020
{
    "AssociationDescription": {
        "Name": "AWS-GatherSoftwareInventory",
        "AssociationVersion": "1",
        "Date": "2019-02-14T11:16:28.214000+11:00",
        "LastUpdateAssociationDate": "2019-02-14T11:16:28.214000+11:00",
        "Overview": {
            "Status": "Success",
            "AssociationStatusAggregatedCount": {
                "Success": 1
            }
        },
        "DocumentVersion": "$DEFAULT",
        "Parameters": {
            "applications": [
                "Enabled"
            ],
            "awsComponents": [
                "Enabled"
            ],
            "customInventory": [
                "Enabled"
            ],
            "instanceDetailedInformation": [
                "Enabled"
            ],
            "networkConfig": [
                "Enabled"
            ],
            "services": [
                "Enabled"
            ],
            "windowsRoles": [
                "Enabled"
            ],
            "windowsUpdates": [
                "Enabled"
            ]
        },
        "AssociationId": "dc7f5ee5-90ee-4166-b87e-72a0d06a9dbd",
        "Targets": [
            {
                "Key": "InstanceIds",
                "Values": [
                    "*"
                ]
            }
        ],
        "ScheduleExpression": "rate(30 minutes)",
        "LastExecutionDate": "2020-05-27T16:16:23+10:00",
        "LastSuccessfulExecutionDate": "2020-05-27T16:16:23+10:00"
    }
}
```

**Comment by shihuazhang** [comment]
Agent will upload log to s3 only when s3 location is enabled. Could you please confirm the region?

I will need to read the full agent log to have a better understanding of your use case. Could you please cut a support ticket to AWS support team and include the full Agent log (ideally the Debug log)?
