### ISSUE TITLE
Hard-coded paths for DefaultDocumentWorker value.

### ISSUE THREAD

**Issue by medined** [aws/amazon-ssm-agent#285]
In constants_unix.go, there are three values set using hard-coded paths. The /usr/bin directory on Fedora CoreOS is read-only. However, /usr/local/bin is not. Can a method be provided so that the base directory can be changed without changing the source code files?

```
var DefaultDocumentWorker = "/usr/bin/ssm-document-worker"
var DefaultSessionWorker = "/usr/bin/ssm-session-worker"
var DefaultSessionLogger = "/usr/bin/ssm-session-logger"
```

**Comment by ferkhat-amz** [comment]
Thank you for bringing this to our attention. We have taken a note of this.
