### ISSUE TITLE
Update the snap latest version

### ISSUE THREAD

**Issue by MattzFiber** [aws/amazon-ssm-agent#288]
Greetings SSM Wizards 

Could you consider moving the latest SSM version from candidate to stable? 
https://snapcraft.io/amazon-ssm-agent

Its currently still on version **_2.3.714.0_**

Currently, the isLatestVersion flags are setting off alarms for all of my systems running on the stable branch, and the idea of changing to the candidate branch on a wide cluster of systems doesn't excite the security enthusiast inside of me. 

Thanks!

**Comment by Thor-Bjorgvinsson** [comment]
Hi MattzFiber. Thanks for reporting this issue. We are currently working on upgrading the candidate version. I'll update this ticket when we have done so.

**Comment by Thor-Bjorgvinsson** [comment]
The latest version on stable has been update to 2.3.978.0
