### ISSUE TITLE
Latest version mismatch

### ISSUE THREAD

**Issue by smarlowucf** [aws/amazon-ssm-agent#29]
The latest version for amazon-ssm-agent on GitHub is v1.2.290.0. However, downloading and installing the rpm from Amazon (https://amazon-ssm-us-west-1.s3.amazonaws.com/latest/linux_amd64/amazon-ssm-agent.rpm) yields a version of 2.0.558.0-1.

Is there a location where the source code for version 2+ can be downloaded? Or a reason for the version mismatch? My goal is to package the latest release source for SUSE.

**Comment by shihuazhang** [comment]
Hi smarlowucf

Thanks for your comment, we are working on the github release and likely will have it ready early next year.

**Comment by smarlowucf** [comment]
Hi shihuazhang,

That's great to hear! Thanks for the update.
