### ISSUE TITLE
Unable to terminate ssm start-session AWS-StartPortForwardingSession 

### ISSUE THREAD

**Issue by SuchismitaGoswami** [aws/amazon-ssm-agent#290]
I tried to close the current session with ctrl + c, bit it's not getting terminated. It just logs the message "Terminate signal received, exiting." and hangs there. Could you please assist me if I'm missing something here?

**Comment by YujiaozhAws** [comment]
Thanks for reaching out. Could you please provide a sample sessionId, region, and/or a time range when you performed this action?
