### ISSUE TITLE
Port forwarding freeze (AWS-StartPortForwardingSession)

### ISSUE THREAD

**Issue by m1keil** [aws/amazon-ssm-agent#294]
Hello,

I'm using Ubuntu 16.04 (eu-west-1 ami-1f83aa79) with SSM agent manually installed from the deb package (v2.3.1509.0).

I'm testing out **AWS-StartPortForwardingSession** document and trying to forward ports to a "complex" application Web UI such as Hashicorp's consul.

In the network tab of the inspect console (Chrome) I can see that the first few requests are passing fine but at some point (about 5-6 HTTP requests in), the requests freeze and data stream stops. Any attempts to issue requests in parallel yield no response from the tunnel:
![image](https://user-images.githubusercontent.com/1589008/88356776-5279bb80-cdac-11ea-9e2c-309cc01691d3.png)

Restarting the session helps to "unblock" but this happens again when the webpage tries to load the other assets. 

I'm able to replicate this over multiple instances and different applications. No error in `amazon-ssm-agent` unit logs.
This does not happen with a regular tunnel over SSH.

`session-manager-plugin` version 1.1.61.0.

**Comment by m1keil** [comment]
Update:

I'm able to reproduce the issue with Latest ubuntu 20.04 (eu-west-1 ami-0127d62154efde733) and the default `amazon-ssm-manager` snap that came pre-installed (2.3.978.0).

Seems like this functionality is able to push very small amount of data before getting into a deadlock.

**Comment by nitikagoyal87** [comment]
Thanks for your feedback. We will look into this!

**Comment by Menahem1** [comment]
Hello,

Are there any evolutions ?

Thanks

**Comment by m1keil** [comment]
After more digging, this seem to be the same issue as reported by #259 & #273

SSM will only allow a single connection. When more than one connection is open, they will get into a deadlock.

The only workaround I found for this is to avoid AWS-StartPortForwardingSession and use AWS-StartSSHSession with native ssh client port forwarding instead.

**Comment by riteshchaman** [comment]
AWS has released a new feature in SM which may solve this issue. Upgrade your ssm-agent to 3.0.222.0 or later and Session Manager plugin to 1.2 or later.
https://aws.amazon.com/about-aws/whats-new/2020/10/port-forwarding-sessions-created-sessions-manager-support-multiple-simultaneous-connections/

**Comment by m1keil** [comment]
@riteshchaman thanks for the FYI. 
I will test it and see if it helps.

**Comment by m1keil** [comment]
Can confirm this does seem to fix the issues I was having.

Going to close this issue now.
