### ISSUE TITLE
AWS.CloudWatch.exe can't send metrics using TLS 1.2 or higher

### ISSUE THREAD

**Issue by sebarosales** [aws/amazon-ssm-agent#295]
**STEPS TO REPRODUCE:**

1. Launch a Windows Server 2019 Base or Windows Server 2016 Base instance.
2. OPTIONAL: Update SSM Agent (tested with SSM version 2.3.1509.0)
3. Disable TLS 1.0 client (https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings#tls-10).
4. Disable TLS 1.1 client (https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings#tls-11).
5. Create a custom CloudWatch metric using AWS.EC2.Windows.CloudWatch.json
6. Restart SSM Agent service

**CURRENT BEHAVIOR**

SSM agent fails to send metrics to CloudWatch. These are the logs:
> WARN  [aws:cloudWatch] - Call CloudWatch API failed when uploading metric data, retrying. A WebException with status SendFailure was thrown.
> WARN  [aws:cloudWatch] - Call CloudWatch API failed when uploading metric data, retrying. A WebException with status SendFailure was thrown.
> WARN  [aws:cloudWatch] - Call CloudWatch API failed when uploading metric data, retrying. A WebException with status SendFailure was thrown.
> ERROR [aws:cloudWatch] - Failed to upload metric to CloudWatch.

	
**EXPECTED BEHAVIOR**
SSM agent should use TLS System Default Versions and send the metrics using TLS 1.2 or higher.

**WORKAROUND**
As AWS.CloudWatch.exe targets an old .NET Framework version (v3.5) that hardcodes TLS version, this line could be added inside the `<runtime>` section in AWS.CloudWatch.exe.config to use Windows TLS System Default Versions:

`<AppContextSwitchOverrides value="Switch.System.Net.DontEnableSystemDefaultTlsVersions=false"/>`

However, this fix only works on instances with .NET Framework 4.6 runtime or higher installed.

**Comment by donovan-middleton** [comment]
Does this help...
https://support.microsoft.com/en-us/help/3154520/support-for-tls-system-default-versions-included-in-the-net-framework
