### ISSUE TITLE
Health check failed with error:: ERROR Health ping failed with error - EC2RoleRequestError: no EC2 instance role found EC2MetadataError: failed to make EC2Metadata request

### ISSUE THREAD

**Issue by lambate** [aws/amazon-ssm-agent#298]

**Comment by lambate** [comment]
The AWS instance faced a downtime, and as per syslog got the error:
ERROR Health ping failed with error - EC2RoleRequestError: no EC2 instance role found
EC2MetadataError: failed to make EC2Metadata request

Need assistance.

**Comment by VishnuKarthikRavindran** [comment]
Hi @lambate,

Thanks for reaching out. SSM Agent requires access to the instance Metadata Service and instance profile to work properly.
https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-agent.html.
