### ISSUE TITLE
Updating amazon-ssm-agent not working for debian instances

### ISSUE THREAD

**Issue by valiente98** [aws/amazon-ssm-agent#300]
The issue #233 has not been solved. Debian instances running on AWS can not be added to system manager as AWS-UpdateSSMAgent document fails. For further details, check issue #233

**Comment by ferkhat-amz** [comment]
Hello. What version of the agent are you using?

**Comment by valiente98** [comment]
Hello,

amazon-ssm-agent version  2.3.1569.0, close to the latest one.

**Comment by danr-amz** [comment]
We tried to reproduce this issue on Debian 10 with Agent version 2.3.1569.0, but update worked as expected.

To help us reproduce this issue, can you please let us know which version of Debian you are using?  If you could supply the contents of the file `/etc/os-release`, that would also be helpful.
