### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by jhmartin** [aws/amazon-ssm-agent#31]
The build instructions seem to be missing a step.   The README says to run 'make build', but the build itself requires that the code be checked out into a specific directory:

Scenario:
git checkout into the current directory
docker run --rm -ti -v "$PWD":/usr/src/myapp -w /usr/src/myapp golang:1.6 make build

Fails with:
```
go run /usr/src/myapp/agent/version/versiongenerator/version-gen.go
agent/version/versiongenerator/version-gen.go:26:2: cannot find package "github.com/aws/amazon-ssm-agent/agent/appconfig" in any of:
	/usr/local/go/src/github.com/aws/amazon-ssm-agent/agent/appconfig (from $GOROOT)
	/usr/src/myapp/vendor/src/github.com/aws/amazon-ssm-agent/agent/appconfig (from $GOPATH)
	/src/github.com/aws/amazon-ssm-agent/agent/appconfig
	/go/src/github.com/aws/amazon-ssm-agent/agent/appconfig
makefile:54: recipe for target 'pre-build' failed
make: *** [pre-build] Error 1
```

I see some directory manipulations happening in the Travis build (https://travis-ci.org/aws/amazon-ssm-agent/builds/146477591), but the requirement should be spelled out in the documentation intead of assumed  to follow one particular CI tools conventions.

**Comment by CrazySherman** [comment]
Good observation. 
The build doesn’t require to “check in the code to a specific directory”, rather, it complies with go project’s standard workspace structure.
The docker command you used is absolutely right, except for mapping container’s directory of the volume — you need to create a standard
go workspace directory tree, in this case, “workspace/src/github.com/aws/amazon-ssm-agent”
so the correct docker command to use is: 
 docker run --rm -ti -v "$PWD":/workspace/src/github.com/aws/amazon-ssm-agent -w /workspace/src/github.com/aws/amazon-ssm-agent  golfing:1.6

But yah, we definitely need to make the build script smart enough in the future to adopt arbitrary workspaces.

Cheers
Sherman
