### ISSUE TITLE
Support environment variables for seelog file

### ISSUE THREAD

**Issue by kenchan0130** [aws/amazon-ssm-agent#313]
Currently, the amazon-ssm-agent uses `seelog.xml` to control the behavior of log.
We may want to set the file path and `data-log-group` dynamically depending.

We think this can be accomplished via an arbitrary template engine to allow the environment variables to be read.

**Comment by danr-amz** [comment]
Adding a feature request to our backlog for this.

For reference, it looks like there was a feature request to add support for environment variables to seelog back in 2015:
https://github.com/cihub/seelog/issues/90
