### ISSUE TITLE
Package amazon-ssm-agent.rpm is not signed

### ISSUE THREAD

**Issue by shepster** [aws/amazon-ssm-agent#314]
Per your instructions at [Manually install SSM Agent](https://docs.aws.amazon.com/systems-manager/latest/userguide/agent-install-rhel.html) the command 

`sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm` 

will not install and produces the error

**Package amazon-ssm-agent.rpm is not signed**

**Comment by Thor-Bjorgvinsson** [comment]
Thanks for reaching out, latest rpm and deb packages are now signed.
Please refer to these docs: https://docs.aws.amazon.com/systems-manager/latest/userguide/verify-agent-signature.html
