### ISSUE TITLE
The upload encrypted S3 bucket is not using the header ServerSideEncryption 

### ISSUE THREAD

**Issue by neelaruban** [aws/amazon-ssm-agent#315]
https://github.com/aws/amazon-ssm-agent/blob/5061338e1b0ec1baa0d3419bdcf846c573309c7d/agent/s3util/s3util.go#L93

when we have a bucket policy or a Service control policy which mandates all the S3 uploads should use the SSE header for the uploads which is part of a good security practice , the upload fails . The upload function to the encrypted S3 bucket is not using the header `ServerSideEncryption` currently according to the reference code . 

Could we please ensure the option is handled to enable secure uploads to the session manager audit buckets

**Comment by ranjrish** [comment]
Related #311
