### ISSUE TITLE
Add run dependency of network-online.target

### ISSUE THREAD

**Issue by neko-neko** [aws/amazon-ssm-agent#32]
Run of SSM-agent depends on network communication.
But, startup fails because it does not depend on network-online.target at systemd startup.
For example, startup fails in the following cases.
1. The case when you build ami, ssm-agent has been installed and is enabled on systemd
2. Startup EC2 using created AMI
3. Then I got an error.
```
connect: network is unreachable 169.254.169.254
```

Shoud be add dependency of network-online.target.
Here is my changes.
https://github.com/aws/amazon-ssm-agent/pull/33

**Comment by shihuazhang** [comment]
Thank you for your contribution, your code has been merged.

**Comment by getSurreal** [comment]
when will the change be incorporated in the latest release?
https://amazon-ssm-us-west-2.s3.amazonaws.com/latest/linux_amd64/amazon-ssm-agent.rpm
