### ISSUE TITLE
Error from cronjob 

### ISSUE THREAD

**Issue by leonblueconic** [aws/amazon-ssm-agent#333]
During the last few releases the cronjob which gets installed in /etc/cron.d/awsagent-update contains the following:
`rm /var/log/awsagent-update.log`

On startup with a new instance this gives us the following error message in a mail from cron:
`rm: cannot remove '/var/log/awsagent-update.log': No such file or directory`

Can the command be changed to `rm -f ..` so it no longer errors on the missing file?

**Comment by VishnuKarthikRavindran** [comment]
Thanks for reaching us. We have assigned this issue to the concerned team. Will post in this thread if we have an update.

**Comment by ferkhat-aws** [comment]
Closing as this is not related to SSM Agent.
