### ISSUE TITLE
Failing to start SSM Session with 3.0.732.0

### ISSUE THREAD

**Issue by autero1** [aws/amazon-ssm-agent#355]
After SSM agent upgrade to 3.0.732.0, cannot start SSM session to instance. AWS Console reports:

> The version of SSM Agent on the instance supports Session Manager, but the instance is not configured for use with AWS Systems Manager. Verify that the IAM instance profile attached to the instance includes the required permissions.

AMI: amzn2-ami-hvm-2.0.20210126.0-x86_64-gp2
SSM Agent Version: 3.0.732.0

After running `AWS-UpdateSSMAgent` - `allowDowngrade=true` - `version=3.0.161.0`, successfully established session with Session Manager.

**Comment by danr-amz** [comment]
Thank you for bringing this to our attention.  This issue is fixed in today's release of version 3.0.755.0.

**Comment by AmosElitzur1** [comment]
I have this issue on 3.2.2303.0 version
