### ISSUE TITLE
not clean /var/lib/amazon/ssm/i-*/session/orchestration/*

### ISSUE THREAD

**Issue by okovallevi9** [aws/amazon-ssm-agent#356]
foldes  with sesseon logs in /var/lib/amazon/ssm/i-*/session/orchestration/* not clean up
I can't remove this foldes manualy
rm: cannot remove '<username>-*/Standard_Stream/ipcTempFile.log': Operation not permitted
Version 3.0.529.0
Somebody  can help?

**Comment by ferkhat-aws** [comment]
You can configure the session log retention time by following these directions: 
https://github.com/aws/amazon-ssm-agent/blob/mainline/README.md#runtime-configuration
You can set it to 0 to remove the logs immediately after a session is terminated. 
Closing.
