### ISSUE TITLE
ssm-cli is emitting all level of logs

### ISSUE THREAD

**Issue by xxvinciaxx** [aws/amazon-ssm-agent#359]
Previously the ssm-cli works like a charm, after a recent upgrade, I found the ssm-cli is emitting all level of logs

Debugf: Checking if agent has OnPrem identity
Debugf: 'OnPrem' identity is not available on this instance
Debugf: Checking if agent has EC2 identity
Infof: Agent will take identity from EC2

Which are all not needed.

Please check and fix.

**Comment by ferkhat-aws** [comment]
Thank you for raising this issue. We are working on this and will have a fix out soon.
