### ISSUE TITLE
Guidelines for writing plugins

### ISSUE THREAD

**Issue by copumpkin** [aws/amazon-ssm-agent#36]
I'd like to write a plugin to tell [NixOS](https://nixos.org) to reconverge itself to a particular declarative configuration. It seems pretty straightforward to write the Go code, but I'm not sure what the design is for namespacing them or bundling them externally. Given that I don't think there's a clear mechanism for dynamic loading of Go code, should everything be bundled in this repository? I can dynamically add my plugin to my NixOS-specific build but that feels a bit messy.

Is there any public guidance about this?

**Comment by CrazySherman** [comment]
> I can dynamically add my plugin to my NixOS-specific build but that feels a bit messy.
Im afraid it’s not messy, it’s impossible. We don’t build plugins into dynamic libraries so it’s impossible to link your binaries to the amazon, for now.
So yeah you do need a PR to do this, and the team will have to review it. We’re still actively working on putting up namespacing & packaging standards for plugins.

**Comment by copumpkin** [comment]
@CrazySherman that makes sense. What I meant by messy is that Nix allows for extremely easy ad-hoc "patching" of upstream sources (it's a source release, a bit like Gentoo), so I could easily splice my plugin into the official AWS source tree we build prior to building it. But we generally try to refrain from that sort of hackery if possible, which is why I'm posting here to find out what the right way to do it would be.

Anyway, I'll experiment with writing such a plugin and then if things go well submit a PR here. I'm a little concerned about "notability", since NixOS is a small (but quickly) growing distro and community.

**Comment by copumpkin** [comment]
I also hesitate to put anything I'd submit in a PR under the `aws:` namespace. Would you recommend that for consistency or should we branch out and do something like `nixos:`?

**Comment by CrazySherman** [comment]
Please do this under the aws namespace, thx!

**Comment by copumpkin** [comment]
Hmm, does the AWS API perform eager plugin name checks on SSM documents? I'm attempting to register a document to talk to the plugin I'm writing and the API is telling me:

```
An error occurred (InvalidDocumentContent) when calling the CreateDocument operation: Unknown plugin name: aws:nixosConfigure
```

Which is going to make it very difficult to experiment with plugins 😄

**Comment by CrazySherman** [comment]
Well, actually sorry I should have mentioned earlier. Because adding plugins needs document update, the team will need to discuss on it. So let’s keep on the discussion here before you actually implement it. We’re always happy to receive feedbacks & contributions from developers for the agent.

**Comment by copumpkin** [comment]
Sure, that's fine, but I'm just wondering what my development cycle will look like if you do agree to consider it, since I can't run an end-to-end test without touching the error checks on your API servers 😄

I suppose I could do much of what I need for NixOS using the traditional `RunCommand` stuff, but that involves a lot of shell splicing and escaping that gets pretty ugly today.

My use cases:
1. NixOS is a distro that's managed fully declaratively, so you can add packages and services by adding them to the central config file then reconverging, and remove them by deleting them from the config file and reconverging. I'd like to use SSM to ask my NixOS box to reconverge to a config provided over SSM. I can do this with `runCommand` today, but I want to provide the entire system config as a document parameter and don't know how to escape that properly when talking about it in the SSM document. I basically have a multiline string parameter that could contain anything (printable) and don't know how to escape it to feed it into `runCommand`.
2. NixOS can also roll back system configuration really easily, so I can ask it to roll itself back to a prior configuration if something goes wrong, and I'd like to tell it to do that over SSM. This would be a pretty easy `runCommand` invocation today, so doesn't need its own plugin.
3. NixOS has a simple patching story based on _channels_, which are mutable (but reproducible) universes of packages that get updated upstream by our CI system. I'd like to be able to update (or even repoint) the channel as a one-off command (which I can do easily with `runCommand` today), but also perhaps set a policy for the system to update the channel regularly for me.

**Comment by copumpkin** [comment]
So in short I was planning to write two nixos-specific plugins: the first to reconfigure the system based on a multiline string that contains a blob of declarative configuration (which might be unnecessary if I can escape it properly for `runCommand`), and the second would be a periodic policy to ensure that NixOS channel updates are applied.

**Comment by shihuazhang** [comment]
Hi copumpkin,
Thanks for your feedback and contribution to the project.
The plugin that you are intent to write looks a lot like a core plugin to me. 

We have two types of plugins, core and document (we will find better names in the future). The document plugin (such like runCommand)  runs on demand of the document execution (such as messages). Adding a new plugin require service change and you will have trouble with developing remotely. 

However, the core plugin executes during agent starts. I believe it fixes better with your case.
Here is one of the core plugin you may want to take a look 

https://github.com/aws/amazon-ssm-agent/blob/master/agent/startup/startup.go

Please let me know if you have any question.

Thanks
Shihua

**Comment by shihuazhang** [comment]
Feel free to reopen this if you have more question
