### ISSUE TITLE
Latest tag's year is wrong > Amazon SSM Agent - Release 3.0.882.0 - 2020-03-16

### ISSUE THREAD

**Issue by ElijahLynn** [aws/amazon-ssm-agent#369]
https://github.com/aws/amazon-ssm-agent/releases

I think the year is wrong on the latest tag > Amazon SSM Agent - Release 3.0.882.0 - 2020-03-16

https://github.com/aws/amazon-ssm-agent/releases/tag/3.0.882.0

**Comment by ferkhat-aws** [comment]
Thank you for the catch. I have updated the tag.
