### ISSUE TITLE
Guidelines for adding support for other Linux distributions

### ISSUE THREAD

**Issue by copumpkin** [aws/amazon-ssm-agent#37]
I see that the inventory plugin currently supports `dpkg` and `rpm`. If I'd like SSM agent to work nicely on my distribution, is there a clear story on how to teach it about its packaging system? I could obviously submit a PR but it's unclear to me if we'd want distro-specific knowledge to be in the central repository or otherwise plugged into the agent in other "less official" ways. Any guidance here?

**Comment by copumpkin** [comment]
This is probably also relevant to #34, which adds packages for the agent but doesn't (yet?) teach the SSM agent how to query installed SUSE packages at runtime.

**Comment by smarlowucf** [comment]
@copumpkin What package types does the distribution use? SUSE, for example, uses rpm packages. So it is already covered by the existing code.

See [here](https://github.com/aws/amazon-ssm-agent/blob/7638cb11679416d6ca3c3827e275593575aa72c1/agent/plugins/inventory/gatherers/application/dataProvider_unix.go#L74) where the inventory plugin attempts to get the applications via dpkg and falls back to rpm.

It does not use the systems command line package manager. I.e. zypper on SUSE, apt-get on Debian, yum on RHEL etc.

**Comment by copumpkin** [comment]
@smarlowucf it's a completely separate packaging system, called Nix, completely unrelated to `dpkg` or `rpm`. At the same time, the notion of "installed packages" makes less sense in Nix land so perhaps this isn't as pressing.

Curious about that custom inventory JSON stuff, which might allow me to express concepts that do make more sense for NixOS. Is there an example of that anywhere?

**Comment by smarlowucf** [comment]
Not sure about custom inventory, the docs do have a couple examples and specify the location where the json files should reside http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sysman-inventory-about.html#sysman-inventory-custom.

**Comment by copumpkin** [comment]
Cool, I missed that, thanks! I'll close this until I have something more specific to ask
