### ISSUE TITLE
AWS SSM documentation states it supports ARM-64 bit, but this error indicates otherwise

### ISSUE THREAD

**Issue by altjx** [aws/amazon-ssm-agent#377]
I'm using a Raspberry Pi 4 Model B and for some reason I cannot get the `amazon-ssm-agent` to actually install.

Here's my CPU info:

```
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           3
Model name:                      Cortex-A72
Stepping:                        r0p3
CPU max MHz:                     1500.0000
CPU min MHz:                     600.0000
BogoMIPS:                        108.00
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm crc32 cpuid
```

I've got Ubuntu Server 20.04 installed, as this article suggests that ARM 64-bit is supported: https://docs.aws.amazon.com/systems-manager/latest/userguide/prereqs-operating-systems.html#prereqs-os-linux.

The reason I didn't install Raspbian is because Raspbian is only available in 32-bit, and the AWS CLI version 2 isn't supported on ARM 32-bit, as mentioned [here](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html) and [here](https://github.com/aws/aws-cli/issues/6131).

I am looking to install the following two tools on my Raspberry Pi 4 Model B.

* amazon-ssm-agent
* AWS CLI version 2

I'm confused on which operating system to actually use so that both are supported. The only thing that seems to work thus far is Raspbian OS (32-bit), but, again, according to the GitHub referenced link above, AWS CLI version 2 isn't planned to be supported on 32-bit operating systems, so that leaves me with pretty much Ubuntu, which doesn't seem to work with amazon-ssm-agent.

I tried to take a peak at [this](https://aws.amazon.com/blogs/mt/manage-raspberry-pi-devices-using-aws-systems-manager/) as well, but how does anyone know if https://s3.us-east-2.amazonaws.com/amazon-ssm-us-east-2/latest/debian_arm/amazon-ssm-agent.deb is for an ARM 32-bit or ARM 64-bit architecture? I've tried installing this on Ubuntu Server 20.04 on my Raspberry PI, and retrieved this:

```
root@myuser-desktop:~# curl https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb -s -o /tmp/amazon-ssm-agent.deb
root@myuser-desktop:~# dpkg -i /tmp/amazon-ssm-agent.deb
dpkg: error processing archive /tmp/amazon-ssm-agent.deb (--install):
 package architecture (amd64) does not match system (arm64)
Errors were encountered while processing:
 /tmp/amazon-ssm-agent.deb
root@myuser-desktop:~# curl https://s3.us-east-2.amazonaws.com/amazon-ssm-us-east-2/latest/debian_arm/amazon-ssm-agent.deb -s -o /tmp/amazon-ssm-agent.deb
root@myuser-desktop:~# dpkg -i /tmp/amazon-ssm-agent.deb
dpkg: error processing archive /tmp/amazon-ssm-agent.deb (--install):
 package architecture (armhf) does not match system (arm64)
Errors were encountered while processing:
 /tmp/amazon-ssm-agent.deb
```

Any help would be greatly appreciated.

_**EDIT**_

I just discovered that this is an actual working URL:

https://s3.us-east-2.amazonaws.com/amazon-ssm-us-east-2/latest/debian_arm64/amazon-ssm-agent.deb 

However, this URL isn't even mentioned anywhere on this page: https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-install-managed-linux.html

**Comment by VishnuKarthikRavindran** [comment]
Hi @altjx, Thanks for reaching us. We have submitted your feedback to the documentation team. Thanks
