### ISSUE TITLE
Check /etc/os-release for release information

### ISSUE THREAD

**Issue by copumpkin** [aws/amazon-ssm-agent#38]
See [here](https://www.freedesktop.org/software/systemd/man/os-release.html) and [here](http://0pointer.de/blog/projects/os-release) for a longer spiel about why this is a good place to check. It also addresses the `lsb_release` tool and other things like that. 

Distributions using `systemd` (err, most of the major ones) will soon (if not already) have that file, due to [this announcement](https://lists.freedesktop.org/archives/systemd-devel/2012-February/004475.html) which made it effectively a requirement for running `systemd`.

**Comment by shihuazhang** [comment]
Thanks for your feedback.

The os-release appears to be the standard way, I will let the team know.

**Comment by mmendonca3** [comment]
Thank you for your feedback. This has been fixed in version  2.0.796.0

**Comment by copumpkin** [comment]
Thanks!
