### ISSUE TITLE
Support Ubuntu Core

### ISSUE THREAD

**Issue by stuart-warren** [aws/amazon-ssm-agent#385]
### Summary

Cannot currently make this work on Ubuntu Core within a strictly confined snap

### Description

I've been trying to get ecs anywhere running on Ubuntu Core for a few days and have managed it.
Is there any appetite for accepting a merge request to support a strictly confined snap?

### Expected Behavior

Should be able to run on Ubuntu Core

### Observed Behavior

* Some paths do not exist outside of a strictly confined snaps context
* The existing snap is only classically confined so is unusable on Ubuntu Core

### Environment Details

Ubuntu Core 20.04

**Comment by ferkhat-aws** [comment]
Hello. We currently do not support Ubuntu Core. We will note this as a feature request, though.
