### ISSUE TITLE
Add snapcraft.yaml file to source code

### ISSUE THREAD

**Issue by toabctl** [aws/amazon-ssm-agent#386]
There is a snap released on the snapstore (see https://snapcraft.io/amazon-ssm-agent ) for amazon-ssm-agent. But there is not `.snapcraft.yaml` in the git source tree. So if I want to make changes to the snap build process, that's not possible. Please provide the `.snapcraft.yaml` file in this git tree.

**Comment by ferkhat-aws** [comment]
Hello. We have published the file: https://github.com/aws/amazon-ssm-agent/blob/mainline/packaging/snap/snapcraft.yml
