### ISSUE TITLE
Installation fails on Debian Squeeze

### ISSUE THREAD

**Issue by robmoss2k** [aws/amazon-ssm-agent#388]
The Ubuntu prerm and postinst scripts are missing "#!/bin/bash" on the first line of the script, although this is present in the preinst script. Attempting to install on Debian Squeeze fails with "Exec format error". Pull request #383 fixes this issue.

**Comment by ferkhat-aws** [comment]
Hello. We do not support Debian Squeeze. You can find the list of operating systems we support in the link below: 
https://docs.aws.amazon.com/systems-manager/latest/userguide/prereqs-operating-systems.html

**Comment by chadbrewbaker** [comment]
Megacorp needs Debian 11 support ASAP - are there any known isssues?. Apple M1 breaks on Debian10/Ubuntu20.04 containers and needs Debian11/Ubuntu21 - like to remote attach to AWS CodeBuild with the same image which requires ssm support. Should be binary drop-in for Gravition2.
