### ISSUE TITLE
Inventory gatherer for running Linux services/units (under systemd)

### ISSUE THREAD

**Issue by copumpkin** [aws/amazon-ssm-agent#39]
More interesting (to me at least) than the list of installed applications on a box is an overview of the services on the box, similar to the output of `systemctl` when run locally. It would tell me which units `systemd` knows about, whether they're running, and so on.

On non-systemd systems, I suppose we could enumerate /etc/init.d or do something similar? Or perhaps even just dump the output of `ps` periodically, although that might be less stable.

**Comment by CrazySherman** [comment]
Which OS you're targeting here?

**Comment by copumpkin** [comment]
Linux, sorry. More specifically, I was thinking of any Linux distro running `systemd`, which is [most of the big ones](https://en.wikipedia.org/wiki/Systemd#Adoption_and_reception).

**Comment by CrazySherman** [comment]
hmm, to get the running status you would prolly need “ps”. Alternatively I usually do “service” first and then “status” to check the running status. Does it help?

**Comment by copumpkin** [comment]
Well, `systemd` has its own mechanism to do that called `systemctl`, which can check up on running services and various interesting parts of their configurations. Of course falling back on `ps` seems like fine behavior, but the key thing I want here would be to integrate it automatically with my inventory. I see some code in there for a "custom inventory" that outputs JSON, but I can't see how to inject my own code (e.g., invoke `systemctl` or `ps`) into it.

**Comment by hwqin** [comment]
@copumpkin, for how does "custom inventory" work end to end for aws customer, please refer to http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sysman-inventory-about.html. In short, dump the information (ps outpu or systemctl) with a specific JSON format into the predefined custom inventory directory, then it will be automatically be collected by custom gather of inventory plugin. The collection schedule will be determined by the association object created using CreateAssociation API (http://docs.aws.amazon.com/ssm/latest/APIReference/API_CreateAssociation.html). Please see the previous link for the JSON format and custom inventory directory.

**Comment by copumpkin** [comment]
Yeah found that later, thanks!

**Comment by rajeshgautamphd** [comment]
A cron job/script would do the job.
