### ISSUE TITLE
Updating amazon-ssm-agent not working on Kali GNU/Linux

### ISSUE THREAD

**Issue by rajaraa** [aws/amazon-ssm-agent#390]
Hi,

I have already installed the ssm agent manually on the machine. Version is 3.0.1295.0. But when updating, it errors out with the below error.

Step execution skipped due to unsatisfied preconditions: '"StringEquals": [platformType, Windows]'. Step name: createUpdateFolder

cannot find the amazon-ssm-agent-windows-amd64.tar.gz information in the Manifest file

**Comment by gianniLesl** [comment]
There may have been a problem getting your platform details using wmic. Please look through your amazon-ssm-agent logs for a message like "There was an error running wmic" or any other relevant failures.

**Comment by danr-amz** [comment]
Kali GNU/Linux is not currently officially supported:
https://docs.aws.amazon.com/systems-manager/latest/userguide/prereqs-operating-systems.html

The amazon-ssm-agent updater has some platform detection logic that would likely need to be updated to properly recognize Kali GNU/Linux.  We will add an item to our backlog to add this support.
