### ISSUE TITLE
Linux commands wrapping back to same line

### ISSUE THREAD

**Issue by lee-clements-rft** [aws/amazon-ssm-agent#391]
Linux commands or text entered into the terminal that contains around 50 characters wrap back to the same line and distort the command/text that has been inputted. This appears to happen when using SSM via the AWSCLI or via web browser and with different AMIs (Amazon Linux 2 and RHEL AMIs have been tested).

If I enter the below text into the terminal for example:
`This is an example of the line wrapping issue after many characters have been entered`

The output of the above typed text is as below where some text has wrapped to the beginning of same line:
`been enteredis an example of the line wrapping issue after many characters have`

Obviously this is not a genuine Linux command and is just text entered into the terminal but hopefully this is a clear example of the issue.

**Comment by VishnuKarthikRavindran** [comment]
Hi @lee-clements-rft, 

Do you see this issue with the latest SSM Agent version? If so, are trying this in the session manager terminal?

Thanks,
Vishnu Karthik. R

**Comment by lee-clements-rft** [comment]
Hi,

Apologies for raising this. I'm not normally in charge of installation and upkeep of the software in our images but just as a test I removed the SSM agent and installed the latest version and it is working fine now. 

Thanks,
