### ISSUE TITLE
Automate AWS SSM Agent registration for Hybrid Activations

### ISSUE THREAD

**Issue by PeterBarczi** [aws/amazon-ssm-agent#401]
Hi folks,

I'd like to ask you for a help.

Our use Case is to Automate AWS SSM agent registration on On-Prem VMs.

Simply speaking: if new machine running On-prem is installed with ssm agent, it should be automatically registered into AWS SSM.
You can generate Activation ID & Activation Code once and register on-prem VM using such ID & Code. That is working fine, it can be easily automated, hardcoded into VM.
But stuck point is Registration of new VMs later on, since Activation credentials is max 30 days..

Any idea/experience how to achieve such kind of Automation?

Many thanks in advance
Peter

**Comment by ferkhat-aws** [comment]
Hello Peter. Thanks for reaching out. We cannot provide suggestions for the Hybrid Activations service here. Please cut a support ticket through the AWS Console for further assistance.
