### ISSUE TITLE
Include full commit messages

### ISSUE THREAD

**Issue by copumpkin** [aws/amazon-ssm-agent#41]
I think @cperciva already asked for this in another issue, but it's very awkward (for a non-Amazon employee) to figure out what's happening in this repo when the only thing in every commit message is a link to a URL that we can't access. Here's an example:

```
remove max worker limit for MDS processor
cr https://cr.amazon.com/r/6678848/
```

I'm not asking the SSM team to reveal internal details, but good commit messages go a long way towards making a project more accessible, especially if they describe _why_ things are being done.

**Comment by mmendonca3** [comment]
Hello copumpkin, 

We understand your concern. There is no easy way to filter out the cr link on the commit message. However, we have made it a policy to write better commit messages so that it is more comprehensible, and we will continue doing so. 

Apologies for the inconvenience caused.

**Comment by copumpkin** [comment]
@mmendonca3 oh, thanks. I'm not asking for the link to be filtered out, just for at least _some_ of the information contained behind that link to make it out here. Commit messages often contain valuable information on _why_ things were done, so being able to see commit message details beyond just a link we can't access would be very helpful to the open source community. If you're going to try to include more information in the commit message from now on, that seems fine to me.
