### ISSUE TITLE
aws:runDockerAction doesn't seem to allow : in image names

### ISSUE THREAD

**Issue by andyshinn** [aws/amazon-ssm-agent#410]
Per https://github.com/aws/amazon-ssm-agent/blob/1f2e826b7b1400a13916dca71d6272c684b610ef/agent/plugins/dockercontainer/dockercontainer.go#L313-L316 it doesn't seem to allow colons (`:`) in image names. This prevents use of tagged images. Is this by design or an oversight?

**Comment by mmcgovs** [comment]
Hi Andyshinn, we do not allow colons in an image file name by design because of how our text processing is set up. There are no current plans to support this.
