### ISSUE TITLE
Add Support for CentOS 8.3, 8.4 and 8.5

### ISSUE THREAD

**Issue by mjnowen** [aws/amazon-ssm-agent#413]
As per: https://docs.aws.amazon.com/systems-manager/latest/userguide/prereqs-operating-systems.html

Add Support for CentOS 8.3, 8.4 and 8.5

https://wiki.centos.org/Cloud/AWS

**Comment by Thor-Bjorgvinsson** [comment]
We've added CentOS 8.3, 8.4 and 8.5 to our "Supported operating systems" page
