### ISSUE TITLE
Add Support for Rocky Linux 8.4 and 8.5

### ISSUE THREAD

**Issue by mjnowen** [aws/amazon-ssm-agent#414]
As per: https://docs.aws.amazon.com/systems-manager/latest/userguide/prereqs-operating-systems.html

AWS is an official, "Principal Sponsor" of Rocky Linux but SSM does not work: https://rockylinux.org/sponsors/

Add Support for Rocky Linux 8.4 and 8.5, available via official AWS Marketplace AMIs: https://aws.amazon.com/marketplace/pp/prodview-2otariyxb3mqu

Cross-referencing this open issue: https://github.com/aws/amazon-ssm-agent/issues/405

**Comment by Thor-Bjorgvinsson** [comment]
Support for Rocky linux was added in agent version [3.1.941.0](https://github.com/aws/amazon-ssm-agent/blob/mainline/RELEASENOTES.md#319410). Documentation update is in progress
