### ISSUE TITLE
AWS API call to run EC2 command on multiple instances not working

### ISSUE THREAD

**Issue by vaibhav16apr** [aws/amazon-ssm-agent#42]
After executing following - 

```
aSSM.setRegion(RegionUtils.getRegion("us-east-1"));aSSM.setEndpoint("ssm.us-east-1.amazonaws.com");
SendCommandRequest sComReq = new SendCommandRequest();
sComReq.withInstanceIds("i-XXXXXX6","i-0XXXXXXXXX9dbe2").withDocumentName("XXXX-xxxx-DockerPS").withOutputS3BucketName("k2-bucket1").withOutputS3KeyPrefix("XXXX-CR123-XXXXCI/DevTest/").withComment(" Multi instances Test From Eclipse").withParameters(parameters);
SendCommandResult result = aSSM.sendCommand(sComReq);
```

When I check command status from AWS console, I find that the output tab of either one or both of the 2 command Ids corresponding to 2 instances don't have the S3bucket/S3KeyPrefix. Sometimes I see correct output for both(all) the instances. This is so random that sometimes it shows no output, sometimes only one, sometimes both. 

Any help would be much appreciated.

**Comment by mmendonca3** [comment]
Hello vaibhav16apr, 

Thank you for posting here. We will investigate this issue and get back to you here. In the meanwhile, please use the latest version of the agent and confirm if you still see this issue.

**Comment by mmendonca3** [comment]
Hi vaibhav16apr, 

We were unable to reproduce this issue. Since there was no response on this, we are assuming that this issue was resolved for you and will be closing this issue. If you think the issue still persists, please feel free to reopen this issue and  provide us with the command id to be able to assist you further.
