### ISSUE TITLE
SSM unable to read environment variable on EC2

### ISSUE THREAD

**Issue by phbissiwu** [aws/amazon-ssm-agent#427]
I am working on something and I am trying to call some environment variables with SSM run command using AWS-RunShellScript.
but for some reason, this returns nothing. Please how can I call environment variables with SSM AWS-RunShellScript?

Thank you.

**Comment by Thor-Bjorgvinsson** [comment]
Thanks for reaching out @phbissiwu, Agent does not propagate process environment variables to aws:runshellscript. Here is example output from print environment variables within AWS-RunShellScript execution:
```
AWS_SSM_INSTANCE_ID=<InstanceId>
_=/usr/bin/env
LANG=en_US.UTF-8
AWS_SSM_PLATFORM_NAME=<PlatformName>
INVOCATION_ID=<InvocationId>
AWS_SSM_PLATFORM_VERSION=<PlatformVersion>
PWD=/usr/bin
JOURNAL_STREAM=<JournalStream>
SSM_COMMAND_ID=<commandId>
SHLVL=2
AWS_SSM_REGION_NAME=us-east-1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
```

You can see what variables are available in your script by running `env` in AWS-RunShellScript.

**Comment by ngist** [comment]
I ran into this issue and thought i'd put my resolution up for posterity. The workaround is to source your environment variables at the beginning of whatever script is being called script in my case `source /etc/environment`
