### ISSUE TITLE
AWS.EC2.Windows.CloudWatch.json does not support Unicode files

### ISSUE THREAD

**Issue by TheRealBenForce** [aws/amazon-ssm-agent#43]
I wrote a small utility that will take two of these AWS.EC2.Windows.CloudWatch.json files and combines them together since the service only supports one. This is so we can provide our clients with a modified base AMI that includes some essential monitoring of the OS and they can add to it to include application monitoring. The utility ends with Out-File $destination.

Using this new file was not working even if I combined my platform file with a second empty file. Through troubleshooting, I found it was because of the encoding of the file. The same file resaved with a different encoding format (ANSI) works fine.

Given that powershell is the OS's native scripting language, and the default output of commonly used Out-File command is Unicode, I thought it was worthy of raising an incident to this or at least requesting the dev team publicly document the encoding requirements somewhere. I have not encountered them yet.

**Comment by mmendonca3** [comment]
Hello TheRealBenForce, 

Thank you for your feedback. We will work on updating the docs. 

In the meanwhile you can use the "-encoding" option to make your script work fine.
