### ISSUE TITLE
cloudwatch log endpoint

### ISSUE THREAD

**Issue by bcg62** [aws/amazon-ssm-agent#432]
is there a way to change config to use a vpc private endpoint for cloud-watch logs?  I see all the other endpoint settings but nothing for logs.*amazonaws.com

```
[DataBackend] [pluginName=Standard_Stream] Error Calling DescribeLogGroups:RequestError: send request failed
caused by: Post "https://logs.us-east-1.amazonaws.com/": dial tcp 52.94.231.162:443: i/o timeout
```

**Comment by danr-amz** [comment]
Unfortunately, it is not currently possible to change the endpoint that amazon-ssm-agent uses for communication with CloudWatch.  I will log a feature request to add this capability.
