### ISSUE TITLE
[hybrid] on-premise server has many IPs

### ISSUE THREAD

**Issue by Hokwang** [aws/amazon-ssm-agent#440]
Hi,

I was enabling Advanced tier in Fleet Manager and add on-premise server.

I can access on-premise server using session manager.

But for me, server's IP is very important.
Because I will create ansible's dynamic inventory.

<img width="615" alt="스크린샷 2022-04-08 02 00 01" src="https://user-images.githubusercontent.com/1247030/162257468-7aa50ef0-af9a-4f8d-9b46-ffc8bab6cea8.png">

actually on-premise server can have many IPs like,
![스크린샷 2022-04-08 02 02 49](https://user-images.githubusercontent.com/1247030/162258386-abbe98fb-0950-4e0e-a16d-80b102da1f48.png)

in my case, bond0 is real IP. (what I want to use)

I don't know ssm agent how to pick one IP
and if I can't use picked IP, how to change server IP information.

Thanks,

**Comment by sluggard76** [comment]
Right now, SSM Agent is unable to pick a designated IP address when there are multiple IP addresses. I have entered a feature request accordingly.
