### ISSUE TITLE
Add Support for AlmaLinux OS

### ISSUE THREAD

**Issue by LKHN** [aws/amazon-ssm-agent#447]
The Amazon SSM Agent is installed and enabled on `x86_64` and `AArch64` of AlmaLinux OS 8 and 9 [Community](https://wiki.almalinux.org/cloud/AWS.html) and [Marketplace](https://aws.amazon.com/marketplace/seller-profile?id=529d1014-352c-4bed-8b63-6120e4bd3342) AMIs. It would be nice to have the complete integration. The support also needed for some OS specific documents i.e. `AWS-RunPatchBaseline`(`patch-baseline-operations-1.86`) and `AWS-UpdateSSMAgent`

https://bugs.almalinux.org/view.php?id=234

**Comment by sluggard76** [comment]
I have entered a feature request accordingly
