### ISSUE TITLE
Hardcoded paths

### ISSUE THREAD

**Issue by evandandrea** [aws/amazon-ssm-agent#45]
The agent hardcodes a number of paths that may need to vary from system to system:
https://github.com/aws/amazon-ssm-agent/blob/master/agent/appconfig/constants_unix.go

Can these be made configurable?

**Comment by mattford-amazon** [comment]
What type of changes do you anticipate needing?  Are they platform specific or do they need to be user-configurable?  I can certainly see making log paths user-configurable, but some of the other paths have security and continuity implications (they're where we manage in-progress documents or track which packages the agent has installed for example).

**Comment by mattford-amazon** [comment]
We're tracking this internally as a feature request - to support install via Snap.
