### ISSUE TITLE
Session Manager AWS-StartPortForwardingSessionToRemoteHost session timeout

### ISSUE THREAD

**Issue by npassaro** [aws/amazon-ssm-agent#450]
# Description

When **port forwarding to a remote host** session manager is closing the connection in approximately 1 minute even when there are active connections. 

# Expected behavior

Connections are closed due to idleness when there no active connections.

# Actual behavior

Connection is always closed after 1 minute

**Comment by yuting-fan** [comment]
Hi npassaro@, 

Thank you for reporting the issue. There was an issue introduced in SSM agent version 3.1.1446.0 and SSM Session Manager plugin 1.2.323.0. Please upgrade SSM agent to version 3.1.1476.0 and Session Manager plugin to 1.2.331.0 that have this issue fixed, and try again. 

Regards,
Yuting

**Comment by npassaro** [comment]
Hi @yuting-fan thank you for the quick response! I can confirm that the issue is fixed and the session is kept open.
