### ISSUE TITLE
Releasing the latest to snap store

### ISSUE THREAD

**Issue by shayonj** [aws/amazon-ssm-agent#451]
Currently, this is what we get

```
snap refresh amazon-ssm-agent

snap "amazon-ssm-agent" has no updates available
```

Getting the latest version would be great so we can start using `StartPortForwardingSessionToRemoteHost`
https://aws.amazon.com/about-aws/whats-new/2022/05/aws-systems-manager-support-port-forwarding-remote-hosts-using-session-manager/

**Comment by Thor-Bjorgvinsson** [comment]
The current version on the snap `stable` channel is 3.1.1188.0, to get the latest version available you need to switch to the `candidate` channel which contains the latest agent version and is updated every agent release:

```
sudo snap switch --channel=candidate amazon-ssm-agent
```

docs: https://docs.aws.amazon.com/systems-manager/latest/userguide/agent-install-ubuntu-64-snap.html
