### ISSUE TITLE
Configuring CloudWatch 

### ISSUE THREAD

**Issue by al786999** [aws/amazon-ssm-agent#454]
Hello, I have tried a few options under "Additional Arguments" to point Cloudwatch towards our document in the Parameter store which is appropriately named as AmazonCloudWatch-xyz but cannot find the correct format. Tried calling via parameter but error states "cannot use paramters in additional arguments" - is there anyway to install Cloudwatch and configure it  (not using defaults) only using the AWS-ConfigureAWSPackage run command in SSM?

**Comment by danr-amz** [comment]
What customizations do you require?

Generally speaking, if you want to extend an existing document by adding custom pre- and/or post-processing steps, you might consider creating a new document and invoking the original document from your new one using the `aws:runDocument` plugin.  (Or you could just copy the contents of the original document into a new document, then adjust the contents to suit your needs.)

Relevant doc pages:
* https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-ssm-docs.html
* https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-plugins.html#aws-rundocument
