### ISSUE TITLE
add SSM agent to Ubuntu 22 AMI

### ISSUE THREAD

**Issue by L00k3r** [aws/amazon-ssm-agent#485]
according to AWS documentation shows Ubuntu 16, 18, and 20 have SSM agent installed.  Ubuntu 22 does not.
https://docs.aws.amazon.com/systems-manager/latest/userguide/prereqs-operating-systems.html

ami-08c40ec9ead489470

**Comment by sluggard76** [comment]
We are working to support Ubuntu 22.04 LTS

**Comment by jeanguirro** [comment]
@sluggard76 There're any updates on such support? I'm also having issues with the lack of support for ubuntu 22 on Patch Manager

**Comment by sluggard76** [comment]
@jeanguirro Patch Manager will be supported as part of this effort. We don't have an ETA yet. But I'll post the ETA here as soon as we have it.

**Comment by jeanguirro** [comment]
Thank you, @sluggard76.
Looking forward to the ETA

**Comment by codeguy** [comment]
Also looking forward to ETA. Would love to be able to run patch management on my Ubuntu 22.04 servers.

**Comment by horst5000** [comment]
@sluggard76 Any news on this topic?

**Comment by sluggard76** [comment]
As of now, you should be able to use SSM Agent on Ubuntu 22.04. Please note that Patching functionality is still not available.

**Comment by horst5000** [comment]
Is the SSM version to support  22.04 yet to be released or is support already included with current 3.2.582.0 released on Feb 7?

**Comment by sluggard76** [comment]
Yes, the current version 3.2.582.0 support Ubuntu 22.04

**Comment by rvodden** [comment]
Could the documentation be updated to reflect this please? https://docs.aws.amazon.com/systems-manager/latest/userguide/prereqs-operating-systems.html

**Comment by bac** [comment]
Thank you for the progress on this issue. Is there an issue tracking the work for patching support in 22.04 LTS?

Could you comment briefly on why 22.04 is more difficult to support than previous LTS releases of Ubuntu?

**Comment by rpocase** [comment]
@sluggard76 Is there an ETA on a snap release? Looking at the snapstore, its been awhile since candidate or stable have been updated. We need a snap supporting 22.04 in stable to properly bundle support in the 22.04 AMIs.

**Comment by sluggard76** [comment]
rvodden,

We are updating the documentation https://docs.aws.amazon.com/systems-manager/latest/userguide/prereqs-operating-systems.html. You will see updates in a short while.

**Comment by sluggard76** [comment]
bac,

We didn't observe any difficulty in supporting this Ubuntu 22.04. There are a bit scheduling issue as we are releasing 3.2 SSM Agent that supports Default Host Configuration Management capability: https://docs.aws.amazon.com/systems-manager/latest/userguide/managed-instances-default-host-management.html

**Comment by sluggard76** [comment]
@rpocase We are updating a new Stable release and will update the snap release as part of this effort by the end of March, 2023

**Comment by aarongundel** [comment]
@sluggard76 is there any ETA on a timeframe for supporting Patch Manger on Ubuntu 22 yet?

**Comment by sluggard76** [comment]
@aarongundel Unfortunately no.

**Comment by noelmcgrath** [comment]
Best practise is to use latest OS etc and patch, 22.04 is out a long time now, surely this should be supported a long time ago, the least is to give N ETA please

**Comment by aarongundel** [comment]
For anybody watching this issue for patch manager support, this was released today.  https://aws.amazon.com/about-aws/whats-new/2023/05/aws-systems-manager-patch-manager-ubuntu-22-04/
