### ISSUE TITLE
add SSM agent to Almalinux

### ISSUE THREAD

**Issue by jchavezj** [aws/amazon-ssm-agent#488]
according to AWS documentation show RHEL, Oracle, CentOS Stream, and Rocky 8.x are supported however Almalinux 8.x  and 9.x is not shown.
https://docs.aws.amazon.com/systems-manager/latest/userguide/prereqs-operating-systems.html

**Comment by sluggard76** [comment]
We are working to support both AlmaLinux 8.x and 9.x. We are expecting to complete the work in Q2, 2023
