### ISSUE TITLE
set endpoint url in amazon-ssm-agent.json file

### ISSUE THREAD

**Issue by Rajagopal2000** [aws/amazon-ssm-agent#494]
Hi! I wanted to emulate the **--endpoint-url** which is present in the aws cli in the amazon-ssm-agent.json file. Is it possible to do so? 

The aim is to change the query url from {bucket_name}.s3.{region}.amazonaws.com to s3.{region}.amazonaws.com. I was able to do so when using the aws cli by adding the **--endpoint-url** option when copying files to/from a S3 bucket.

The ssm-agent level modification is to put the SSM Session Logs.

**Comment by sluggard76** [comment]
@Rajagopal2000 We have created a feature request. Please note that we have a backlog of feature requests. We'll prioritize and work on those requests as they come in.
