### ISSUE TITLE
SSM Agent Document the -register subcommand -tags switch

### ISSUE THREAD

**Issue by alanwevans** [aws/amazon-ssm-agent#502]
I was looking at the output of `amazon-ssm-agent -help` and was excided to see a `-tags` option that I assumed (hoped) would add tags to hybrid managed instances during registration.  The lack of documentation had me wondering if it was some kind of private/"employees only" feature but I thought I'd try it anyway.

```
[root@a-qqqqqqqqqqqq ~]# amazon-ssm-agent -version
SSM Agent version: 3.1.1732.0
[root@a-qqqqqqqqqqqq ~]# amazon-ssm-agent -help
Usage of amazon-ssm-agent:
REMOVED FOR BREVITY
  -register
REMOVED FOR BREVITY
  -tags string
```

The usage does not explain what format to use so I tried a few w/ no luck.  I thought I'd look into the repo but I am not a golang dev so I'm a bit out of my depth.  But I _think_ the `-tags` switch accepts a serialized JSON like `{"Key": "Name", "Value": "Foo"}` but that does not seem to work either.  If I read the function correctly it's silently ignoring bad values for `-tags` so I am not sure if the problem is the `-tags` input or if it is that the functionality of the API is not public/supported.

(Again, not golang dev) I think it comes down to [RegisterManagedInstance](https://github.com/aws/amazon-ssm-agent/blob/a6135ec1c596d0b94f870e91eaa24b3fa9e8a8be/agent/ssm/authregister/authregister_client.go#L93) which I think is calling an undocumented (at least not publically) SSM API of the same name.  Note: I did find a mention of `ssm:RegisterManagedInstance` in [Reference: ec2messages, ssmmessages, and other API operations](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-setting-up-messageAPIs.html), but it doesn't help much.

Anyway.  Please document the `-tags` switch.

Side note: If `-tags` isn't a reserved option, it might be nice to use an input that is more "shell friendly". Embedding subshells `$()` or string substitutions `${}` inside serialized JSON objects on the CLI is quoting hell and could lead to errors.  Simplifying it a bit by doing something like `Key=Name,Value=Foo Key=Username,Value=Bar` (like`aws` CLI does in a few places) would make things a lot nicer.

Thanks,
-Alan

**Comment by kd-issa** [comment]
I also agree as im finding hard time to understand how to provide tags during agent registration

**Comment by sluggard76** [comment]
@alanwevans Please find the detailed information from our public documentation: https://docs.aws.amazon.com/systems-manager/latest/userguide/tagging-managed-instances.html
