### ISSUE TITLE
Powershell Throw Exception Has Successful Status

### ISSUE THREAD

**Issue by getSurreal** [aws/amazon-ssm-agent#51]
When executing a powershell script the SSM status is successful when throw is used, but correctly reports as failed if Exit 1 is used.

**Comment by mmendonca3** [comment]
Hello getSurreal,

Thank you for posting here. Our team will investigate this issue and get back to you when we have a fix or ETA.

**Comment by mmendonca3** [comment]
This is a known issue with Powershell. Powershell does not return the right exit code and so we cannot determine the status of the output: 
http://chrisoldwood.blogspot.com/2011/05/powershell-throwing-exceptions-exit.html

**Comment by getSurreal** [comment]
I don't understand.  The link you provided shows a method for being able to get a non zero exit code with a throw.  Yes, there were some inconsistencies, but it is possible.

**Comment by greyvugrin** [comment]
@getSurreal were you ever able to get an answer to this?

**Comment by greyvugrin** [comment]
I'm using exit 1 in a trap - no dice. Seems like a known issue though: #69
