### ISSUE TITLE
Update Snap version to at least 3.2.582.0

### ISSUE THREAD

**Issue by matuzalemmuller** [aws/amazon-ssm-agent#511]
Hi all,

Please update the ssm-agent version available in the snap store to at least 3.2.582.0. Otherwise, I cannot use the new feature for [Default Host Management Configuration](https://docs.aws.amazon.com/systems-manager/latest/userguide/managed-instances-default-host-management.html).

Please note I have numerous instances, and switching to the `candidate` channel is not an option (https://github.com/aws/amazon-ssm-agent/issues/451) - this would defeat the purpose of using an automated feature by performing manual action in each instance.

(If I were to take manual action, I would probably add the policy allowing Systems Manager to access each instance instead of SSH into each device and manually updating the ssm-agent via the candidate channel (or automating it via a script, which in itself has some issues due to my heterogeneous setup).)

**Comment by et304383** [comment]
This should have been done months ago!

Come on AWS, the latest version I'm seeing in Snap is 3.1.1732.0:
https://github.com/aws/amazon-ssm-agent/releases/tag/3.1.1732.0

This was released in AUGUST 2022.  If you aren't going to provide proper deb packages then you need to keep the snap package updated.

Please get this published asap so I too can use DHM.

PS - switching to candidate channel isn't even an option as the latest version there is only 3.1.1927.0

**Comment by rweirtbg** [comment]
Yeah, we find this a bit odd especially since Ubuntu 22.04 support has been added.

**Comment by sluggard76** [comment]
We are still in the process to determine a stable 3.2 version. Once it's determined, we'll update SNAP.

**Comment by et304383** [comment]
> We are still in the process to determine a stable 3.2 version. Once it's determined, we'll update SNAP.

What does this mean?  You're advertising new features for SSM yet we can't use those because you haven't published a stable agent?

**Comment by rpocase** [comment]
@sluggard76 Could we keep this issue open until 3.2.x is in the stable channel? Checking through the snapstore/CLI is a bit cumbersome to periodically poke.

**Comment by sluggard76** [comment]
Reopen based on rpocase's request. will post a update as soon as 3.2 agent is in SNAP

**Comment by rweirtbg** [comment]
SSM keeps cycling between 3.2.582.0 and 3.1.1927.0 and 3.1.1732.0. Snap seems to be downgrading SSM Upgrades it.

**Comment by rpocase** [comment]
@rweirtbg It looks like `3.2.582.0` is now in the snapstore under the candidate channel. I'm not extremely familiar with SSM, but it could have some automation conflicts with default snap policies.

**Comment by et304383** [comment]
@sluggard76 can we please get an update on this?

**Comment by rweirtbg** [comment]
> @rweirtbg It looks like `3.2.582.0` is now in the snapstore under the candidate channel. I'm not extremely familiar with SSM, but it could have some automation conflicts with default snap policies.

I think you're right. Whenever I run the Update SSM command, everything updates to 3.2.x...but then Snap downgrades the installation back to 3.1.1732.0

**Comment by VishnuKarthikRavindran** [comment]
Hi all, Thanks for reaching us. We have updated our stable channel to 3.2.1377.0 already. https://snapcraft.io/amazon-ssm-agent.
