### ISSUE TITLE
Impossible to install amazon-ssm-agent* RPM on RHEL 9

### ISSUE THREAD

**Issue by kkeane** [aws/amazon-ssm-agent#517]
The agent-ssm-agent* is signed using the insecure and long-deprecated SHA1 algorithm.

RHEL 9/AlmaLinux 9/Rocky 9 removed the SHA1 algorithm for signing packages and refuses to install the RPM even if GPG checking is disabled. Any FIPS-secured system is also affected.

Also see item #235 for some related issues (including the exact error message you get when trying to install the RPM on RHEL 9).

There is a workaround, but it seriously compromises security:

You can re-enable SHA1 by switching the whole system back to cipher-mode LEGACY (not providing the command here since this really, really shouldn't be done!)

**Comment by sluggard76** [comment]
@kkeane We are aware of the issue with SHA1 signing algorithm and actively working to resign agent package with more secure hash algorithm. Estimated delivery is about then end of Q2, 2023. 

A separate note: SSM Agent is not officially supporting RHEL9/Rocky Linux 9/AlmaLinux 9. Please refer to this link for more details: https://docs.aws.amazon.com/systems-manager/latest/userguide/prereqs-operating-systems.html

**Comment by kkeane** [comment]
Unfortunately, the problem still seems to exist.

With a freshly downloaded amazon-ssm-agent.rpm on RHEL 9.5:

```
# dnf update amazon-ssm-agent.rpm
Updating Subscription Management repositories.
subscription-manager plugin disabled 0 system repositories with respect of configuration in /etc/dnf/plugins/subscription-manager.conf
<snip irrelevant stuff>
Dependencies resolved.
========================================================================================================================================== Package                              Architecture               Version                           Repository                        Size
==========================================================================================================================================Upgrading:
 amazon-ssm-agent                     x86_64                     3.3.1345.0-1                      @commandline                      24 M

Transaction Summary
==========================================================================================================================================Upgrade  1 Package

Total size: 24 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
warning: Signature not supported. Hash algorithm SHA1 not available.
error: rpmdbNextIterator: skipping h#    1110
Header V4 RSA/SHA1 Signature, key ID 56baa549: BAD
Header SHA256 digest: OK
Header SHA1 digest: OK
warning: Signature not supported. Hash algorithm SHA1 not available.
error: rpmdbNextIterator: skipping h#    1110
Header V4 RSA/SHA1 Signature, key ID 56baa549: BAD
Header SHA256 digest: OK
Header SHA1 digest: OK
Error: An rpm exception occurred: package not installed
```

**Comment by kkeane** [comment]
As a note for anybody who sees this in the future: in order to successfully install the SSM agent, old SHA1 keys must be deleted from the RPM database:

rpm -e gpg-pubkey-56baa549
rpm -e gpg-pubkey-97dd04ed
