### ISSUE TITLE
Feature Request: Releases Should Contain Precompiled Binaries

### ISSUE THREAD

**Issue by remil1000** [aws/amazon-ssm-agent#520]
Hi, and sorry for opening a new issue on top of the already closed https://github.com/aws/amazon-ssm-agent/issues/50

would you consider the release of precompiled binaries so that we could use ssm-agent without going through the process of extracting the executables from the AWS maintained rpm or deb packages ?

I've tested some basic integration with Github actions and matrix build to push a subset of binaries to Github releases but I obviously be happier if this was integrated upstream

For example
https://github.com/remil1000/amazon-ssm-agent/releases/tag/3.2.183.0-gh2

with the following change set/commit
https://github.com/aws/amazon-ssm-agent/commit/bf9975715948a2edd370bf11474e29e48f6a94ac

**Comment by sluggard76** [comment]
We don't have a plan because you can already access Agent binary. Please follow this public documentation: https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-manual-agent-install.html
