### ISSUE TITLE
High CPU usage on platform version: "64bit Windows Server 2016 running IIS 10.0 2.11.5"

### ISSUE THREAD

**Issue by dazbradbury** [aws/amazon-ssm-agent#525]
We seem to have run into an issue where on the latest platform version, the amazon-ssm-agent process consumes an unreasonably large amount of CPU. This happens intermittently, but when it does it causes service degradation on the web worker it's happening to:

![image](https://github.com/aws/amazon-ssm-agent/assets/1332601/eff2bcc5-fa4e-4d4f-ab40-b36c5c8ec441)

![image](https://github.com/aws/amazon-ssm-agent/assets/1332601/ff129871-17fc-47ed-9dc2-7ce3bbd69a53)

We have rolled back to "64bit Windows Server 2016 running IIS 10.0 2.11.4", and the issue hasn't re-surfaced (yet). This is a production application, so providing further information is non-trivial, but it does seem there is an issue with this process in conjunction with the latest platform version. If this isn't something AWS are already aware of, and do need further debug data, let me know and I'll do my best to supply it.

**Comment by armnejad** [comment]
What is the AMI ID that was being used before you rollled back? Are you able to provide the logs from the time the spike is happening? https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-agent-logs.html

**Comment by dazbradbury** [comment]
The AMI is: ami-0f0a57933c23aec26

However, we've now rebuilt the entire environment and rolled forward to the latest platform version (AMI matching above), and the issue seems to have stopped for now. I'll have to keep an eye on it and see if this re-surfaces, but without knowing exactly how amazon-ssm-agent interacts with the rest of the Elastic Beanstalk stack, it's going to be hard to know the exact cause. 

I'm afraid I don't have the agent logs, as the instances were terminated to prevent disruption in our production environment. I'll close this issue for now and re-open if / when it re-occurs.
