### ISSUE TITLE
Tag version 3.2.1377.0 as Latest

### ISSUE THREAD

**Issue by nzauabraham** [aws/amazon-ssm-agent#528]
Trying to install ssm-agent on Debian using: `wget https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb`
Installs version 3.2.1297.0 as the latest version as opposed to version 3.2.1377.0

**Comment by rhaoran-aws** [comment]
3.2.1377.0 is still in release, will be available in the bucket by the end of this week
