### ISSUE TITLE
Copying file content without displaying it?

### ISSUE THREAD

**Issue by mikkoc** [aws/amazon-ssm-agent#530]
Hi there,

I'm not sure this can be addressed by SSM Agent, but it's worth a shot ;)

The goal is to copy some secret file content from an EC2 instance to the clipboard. In OSX, there is `pbcopy`:

```
cat secret.txt | pbcopy
```

And then paste it as needed from the clipboard. I can't find a good way to achieve this on AmazonLinux2 server, no X.

I would like to avoid having to copy the file to S3 and download from there, if possible.

Alternative question: is it possible to prevent some commands outputs from being logged by SSM Session manager? For example:
```
cat secret.txt
```
 
Thanks
Mikko

**Comment by sluggard76** [comment]
mikkoc,

We have created a feature request accordingly. Please note that we have a backlog of feature requests. We'll prioritize and work on those requests as they come in.
