### ISSUE TITLE
Public key expiring soon

### ISSUE THREAD

**Issue by SuperBaobab** [aws/amazon-ssm-agent#531]
Hi,

The public key for SSM Agent packages is expiring very soon, on September 5, 2023.
We need a new public key fast and not with SHA-1 or another obsolete algorithm to be able to install the agent on RHEL 9 (and EL-like distributions) without workarounds.
Do you have a release date for the new key ?

Thanks,

**Comment by sluggard76** [comment]
SuperBaobab. 

Thanks, We are aware of the expiration. We have rotated our signing key. You will soon observe a new public key. We have an ongoing project to move to SHA2 and longer RSA key length. Will provide a date as soon as possible.
