### ISSUE TITLE
armv7 Support

### ISSUE THREAD

**Issue by qoomon** [aws/amazon-ssm-agent#539]
I'd like to use the ssm agent Greengrass component, however currently only **armv8** is supported I need to run it on **armv7**.

From my understanding it is just a matter of component configuration https://github.com/aws/amazon-ssm-agent/blob/b4be7db513737054b239ddcd3d29ca379d38dd96/packaging/greengrass/component.json#L65 

Could you add armv7 as well to supported architectures in this component config?

**Comment by qoomon** [comment]
@ziwangj any news on that? Is there any reason that armv7 is not supported?

**Comment by sluggard76** [comment]
We have created a feature request accordingly. Please note that we have a backlog of feature requests. We'll prioritize and work on those requests as they come in.

**Comment by qoomon** [comment]
any news?
