### ISSUE TITLE
ssm-setup-cli.exe fails - "Please run as root/admin. Err:  failed to check permissions: exit status 1"

### ISSUE THREAD

**Issue by Mapel88** [aws/amazon-ssm-agent#560]
Hi,

When running ssm-setup-cli.exe with hybrid activation it fails sporadically.
some servers were able to install and some failed with the following error:
"Please run as root/admin. Err:  failed to check permissions: exit status 1"

all installations on all servers are executed by same user which is domain admin & local admin.
Also tested with administrator itself.

OS: windows 2016

Any advise or fix planned for this?

**Comment by VishnuKarthikRavindran** [comment]
Hi @Mapel88, Thanks for reaching out to us. Could you please share more details on the OS version? Is there any difference between the working ones and non working ones?

**Comment by Nookyx** [comment]
Facing the same issue on Windows Server 2022. It does fail intermittently. Calling the ssm-setup-cli.exe multiple times in exactly the same way will eventually work, usually after about 5 tries.

**Comment by VishnuKarthikRavindran** [comment]
Thanks for reaching us @Nookyx. We will look into this

**Comment by Mapel88** [comment]
Hi @VishnuKarthikRavindran,
Sorry, I missed your question.
No difference between servers. All running windows 2016 and installed from same image. I started having this issue about 3 weeks ago. I retried to install 3 times but no success. maybe 5th time is a a charm?

EC2 nodes running same OS with ami created from same image usually pass successfully. don't think i encountered this issue with ec2 even though running same command and same configuration.

thanks

**Comment by VishnuKarthikRavindran** [comment]
Thanks @Mapel88. We were able to repro this issue and will be pushing out the fix in upcoming release.

**Comment by nervermore2** [comment]
I faced the same issue while executing `ssm-setup-cli.exe`

**Comment by nervermore2** [comment]
Some additional logs: I tried to run ssm-setup-cli.exe during instance startup script. I verify that: 
```
Write-Output "Current user: $env:USERNAME"
``` 
has output 
`Current user: Administrator`
This still fails. 
If I log into the instance and run the ssm installer executable. Then it's working.

**Comment by VishnuKarthikRavindran** [comment]
We have fixed the issue in ssm-setup-cli version - https://github.com/aws/amazon-ssm-agent/releases/tag/3.3.418.0. Please let us know if this issue still persists
