### ISSUE TITLE
Issue Configuring EC2 Instance to use Session Manager

### ISSUE THREAD

**Issue by hayydeeeeen** [aws/amazon-ssm-agent#577]
I am having issues getting my first EC2 instance to work with session manager. 

I have configured Systems Manger to automatically convert new EC2 Instances to managed nodes, per [this documentation](https://docs.aws.amazon.com/systems-manager/latest/userguide/managed-instances-default-host-management.html) but it isn't working. I've come over from issue #544, but even after following the suggested steps there, no luck. See attached for a screenshot of the ssm log obtained via ssh connection into the instance (that's as far as it got). I've attached AmazonSSMServiceRolePolicy to the IAM role associated with my instance, and unsured that the role does not allow the UpdateInstanceInformation permission (applicable instructions found [here](https://docs.aws.amazon.com/systems-manager/latest/userguide/setup-instance-permissions.html)).

What else do I need to do to be able to connect with Session Manager?

My instance is a t2.micro running Amazon Linux 2023 AMI.

P.S. If it's relevant, Instance Connect Isn't working either, only SSH.

![image](https://github.com/aws/amazon-ssm-agent/assets/77031413/0ce76d06-c12c-4277-8f43-dbdb8cc748cd)

**Comment by taitaitai1777** [comment]
### Title: Troubleshooting EC2 Instance Connection via Session Manager

---

### Summary:
To resolve EC2 instance connectivity issues via Session Manager, ensure correct IAM role configuration, review SSM agent logs and settings, verify VPC endpoints, and confirm instance connectivity status. Check permissions in IAM role, ensure the SSM agent is running, and update the instance to the latest SSM agent version. Additionally, validate networking and endpoint setups. This guidance helps establish a successful connection to your Amazon Linux 2023 AMI t2.micro instance using Session Manager.

---

### Step-by-Step Guide:

#### 1. **Verify IAM Role Configuration:**
   - Confirm that the instance has an IAM role attached with the `AmazonSSMManagedInstanceCore` policy.
   - Ensure that the role does not deny `UpdateInstanceInformation` permission.
     ```plaintext
     IAM > Roles > YourRole > Attach policies 
     Ensure AmazonSSMManagedInstanceCore is attached.
     ```
   
#### 2. **Review SSM Agent Logs:**
   - SSH into your instance and check the SSM agent logs.
     ```bash
     sudo cat /var/log/amazon/ssm/amazon-ssm-agent.log
     ```
   - Look for any error messages or warnings that might indicate the issue.

#### 3. **Check SSM Agent Status:**
   - Ensure the SSM agent is running:
     ```bash
     sudo systemctl status amazon-ssm-agent
     ```
   - If not running, start it:
     ```bash
     sudo systemctl start amazon-ssm-agent
     ```

#### 4. **Update SSM Agent Version:**
   - Update to the latest SSM agent version:
     ```bash
     sudo yum install amazon-ssm-agent
     sudo systemctl restart amazon-ssm-agent
     ```

#### 5. **Verify VPC Endpoints:**
   - Ensure the instance has connectivity to the necessary endpoints:
     ```plaintext
     VPC > Endpoints > Check if com.amazonaws.<region>.ssm and com.amazonaws.<region>.ec2messages endpoints exist.
     ```
   - If not, create the required VPC endpoints for SSM.

#### 6. **Check Instance Connectivity:**
   - Ensure your instance is listed as "Managed" in the Systems Manager console:
     ```plaintext
     AWS Systems Manager > Managed Instances > Check for your instance ID.
     ```
   - Verify the instance has outbound internet access, required for certain SSM functionalities.

#### 7. **Validate IAM Permissions:**
   - Verify correct IAM permissions:
     ```plaintext
     IAM > Roles > YourRole > Inline policies > Ensure no conflicting statements blocking SSM
     ```

#### 8. **Confirm Network Configuration:**
   - Ensure the instance has proper security group configurations allowing necessary outbound traffic:
     ```plaintext
     EC2 > Instances > YourInstance > Security Group > Edit Inbound/Outbound Rules
     Allow all outbound traffic or specific ports for SSM if restricted.
     ```

---

By performing these checks and adjustments, you can resolve issues related to connecting your Amazon Linux 2023 AMI t2.micro instance to AWS Session Manager. This ensures the instance can be managed effectively using Systems Manager Session Manager.

**Comment by yuting-fan** [comment]
Hi @hayydeeeeen , 

I'm trying to confirm some details in the setup here - 

1. Your instance profile role uses AmazonSSMServiceRolePolicy, which does not have UpdateInstanceInformation permission? 
2. You have enabled Default Host Management Configuration following https://docs.aws.amazon.com/systems-manager/latest/userguide/managed-instances-default-host-management.html, which includes setting up Service Setting that sets a default role? 
3. Then after you launch / reboot the instance, you saw the above logs in SSM agent logs. 
4. Did you check whether this instance is now connected to SSM under Fleet Manager console? 

Once you've shared the above info I'd be happy to help next, because based on the info so far I don't think the issue is with Session Manager usage, but whether the instance is connected to SSM / whether Default Host Management Configuration is correctly set up. 

Regards,
Yuting
