### ISSUE TITLE
Can we use this to SSH into a Kubernetes dev pod?

### ISSUE THREAD

**Issue by alex-treebeard** [aws/amazon-ssm-agent#578]
Hi there - I haven't seen any docs on this use case, but we'd like to migrate some dev EC2 instances to using Kubernetes pods instead.

I'm assuming it will be something like:
- Give the pod a role for registering with ssm (`AmazonSSMManagedInstanceCore`?)
- [Install and start](https://docs.aws.amazon.com/systems-manager/latest/userguide/agent-install-ubuntu-64-deb.html) the SSM Agent
  - As this is not an EC2 instance we would need a [hybrid activation](https://mng.workshop.aws/ssm/capability_hands-on_labs/hybridactivations.html)
- Give the developers a role for accessing their agent

Are there any issues/considerations we should make when running `amazon-ssm-agent` in an (Ubuntu) pod so that we can allow SSH tunneling from a developer laptop into the pod?

Thanks!

**Comment by sluggard76** [comment]
alex-treebeard,

You will need a hybrid activation and run your agent as on-prem mode. Please follow [this link](https://docs.aws.amazon.com/systems-manager/latest/userguide/operating-systems-and-machine-types.html) to confirm whether your Ubuntu OS is supported. If you run into any issues, please feel free to open an AWS support case.
