### ISSUE TITLE
Is there any way to suppress messages

### ISSUE THREAD

**Issue by macktab** [aws/amazon-ssm-agent#59]
Is there any way to suppress messages in syslog, in dir /var/log/amazon/ssm (both amazon-ssm-agent.log and errors.log) and in /var/lib/amazon/ssm/%instanceid%/document/orchestration/* dir.
There is too much debug for me.
And I am surely do not want to appear all output which I have from aws ec2 runcommand in syslog.

**Comment by macktab** [comment]
Please, guys, advice some way to supress it at least in syslog.

**Comment by mmendonca3** [comment]
Hello macktab, 

The default log level for SSM Agent is INFO. This level has the least number of logs required for regular debug of the agent. More information about logging can be found here - https://github.com/cihub/seelog/wiki/Log-levels. 

Logging for /var/log/amazon/ssm/amazon-ssm-agent.log can be disabled by using the log level 'off'. Note that if you use the log level 'off', there will not be any logs for debug purposes. The logs within the orchestration directory are meant for bookkeeping and are used by the agent for purposes of sending output, executing scripts etc.

In case it is still required to disable logging, log into an instance and locate the following file:

1 a. On Windows: %PROGRAMFILES%\Amazon\SSM\seelog.xml.template

1 b. On Linux: /etc/amazon/ssm/seelog.xml.template

2. Change the file name from seelog.xml.template to seelog.xml

3. Update seelog type minlevel to 'off' and restart the agent. 

Without logs, any agent issue is impossible to debug. I will be closing this issue. Please reopen it if you need further assistance.

**Comment by macktab** [comment]
But I am really need only to disable logging in syslog, how to do that?
