### ISSUE TITLE
[Bug] - Self-update updates when already current on a fresh install.

### ISSUE THREAD

**Issue by rrehbein** [aws/amazon-ssm-agent#593]
**Describe the bug**
Self-update will update the agent when the agent is already the same version as latest version.

**To Reproduce**
1. Enable SSM self-update in AWS Console.
2. Start a new Amazon Linux 2023 EC2 instance with user-data
```
#!/bin/sh
yum install -y https://s3.us-east-1.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
systemctl enable amazon-ssm-agent.service --now
```
3. Check ssm logs around the term `updateSsmAgent`

**Expected behavior**

Update-agent to skip installing a 'newer' version when the current version and the latest version are the same version.

**Actual**

Snippets of `amazon-ssm-agent.log`
```
2024-10-09 08:26:22.3216 INFO [ssm-agent-worker] [StartupProcessor] Write to serial port:
    Amazon SSM Agent v3.3.859.0 is running
... snip ...
2024-10-09 08:26:22.3420 INFO [ssm-agent-worker] ssm-agent-worker - v3.3.859.0
... snip ...
2024-10-09 08:26:32.3227 INFO [ssm-document-worker] [b0382a5d-000d-46d4-abf9-64fd78148ef4]
    [DataBackend] [pluginName=aws:updateSsmAgent] UpdateS3Util Latest updater version is 3.3.859.0
... snip ...
2024-10-09 08:26:32.5475 INFO [ssm-document-worker] [b0382a5d-000d-46d4-abf9-64fd78148ef4]
    [DataBackend] [pluginName=aws:updateSsmAgent] Start Installation
```

Observed this while trying to workaround the issues in https://github.com/amazonlinux/amazon-linux-2023/issues/397

**Comment by gianniLesl** [comment]
SSM Agent is pre-installed on AmazonLinux and you have SSM Agent Auto-Update enabled so no need to add the mentioned user-data. The SSM Agent Updater also resolves the agent version so requesting to update when already on the latest version is a no-op with output like
```
Successfully downloaded manifest

Successfully downloaded updater version 3.3.987.0

Updating amazon-ssm-agent from 3.3.859.0 to 3.3.859.0

amazon-ssm-agent 3.3.859.0 has already been installed

update skipped
```

These logs can also be found in `/var/log/amazon/ssm/AmazonSSMAgent-update.txt`
