### ISSUE TITLE
Amazon SSM Agent - Release 3.3.1311.0 - aws:configurePackage download failed

### ISSUE THREAD

**Issue by etiennejeanneaurevolve** [aws/amazon-ssm-agent#600]
# Amazon SSM Agent - Release 3.3.1311.0
## Description
aws:configurePackage used as part of AWS-ConfigureAWSPackage fails to install AwsVssComponents with SSM agent version 3.3.1311.0
Something has changed in the way the AWS package is downloaded and it now fails in our environment.

## Workaround
Use version 3.3.1230.0 or earlier.

## Logs
SSM Run command output:
error when reading the manifest from cache open C:\Program Files\Amazon\SSM\Manifests\_arnawsssmpackageawsvsscomponents_26_AGRGDRLBIAAGXDGWI24ZWX3HTME43RT6JVD7NBSJDMRR2XRFCBAA====_2.4.0.json: The system cannot find the file specified.

SSM Run command Error:
failed to download the manifest: failed to download manifest - failed to retrieve manifest: ValidationException: Require valid document name.
	status code: 400, request id: 85b56764-800c-4cd3-bc32-9c38918471d8
failed to download manifest - failed to retrieve manifest: ValidationException: Require valid document name.
	status code: 400, request id: 85b56764-800c-4cd3-bc32-9c38918471d8
failed to download the manifest: failed to download manifest - failed to retrieve manifest: ValidationException: Require valid document name.
	status code: 400, request id: 85b56764-800c-4cd3-bc32-9c38918471d8
failed to download the manifest: failed to download manifest - failed to retrieve manifest: ValidationException: Require valid document name.
	status code: 400, request id: 85b56764-800c-4cd3-bc32-9c38918471d8

**Comment by Aperocky** [comment]
Thanks for the report, we are fixing the issue and will be publishing a new version.

**Comment by martin-greyscaleai** [comment]
We have the same issue when installing AmazonCloudWatchAgent package: 
aws ssm send-command \
      --document-name "AWS-ConfigureAWSPackage" \
      --instance-ids "${machine_id}" \
      --parameters '{"action":["Install"],"installationType":["Uninstall and reinstall"],"name":["AmazonCloudWatchAgent"],"version":["1.247360.0b252689"]}'
      
returns:
```
      error when reading the manifest from cache open 
/var/lib/amazon/ssm/manifests/_arnawsssmpackageamazoncloudwatchagent_2B_HP6ASKUGHXDL73H24T7UUUKNWXRDTKWGMMX5YMXLDHWGQE2KUPXA====_1.247360.0b252689.json:
 no such file or directory
 
 failed to download the manifest: failed to download manifest - failed to retrieve manifest: ValidationException: Require valid document name.
	status code: 400, request id: 2825b7c6-a188-4ed8-8ffe-3662f22ac0fb
failed to download manifest - failed to retrieve manifest: ValidationException: Require valid document name.
	status code: 400, request id: 2825b7c6-a188-4ed8-8ffe-3662f22ac0fb
failed to download the manifest: failed to download manifest - failed to retrieve manifest: ValidationException: Require valid document name.
	status code: 400, request id: 2825b7c6-a188-4ed8-8ffe-3662f22ac0fb
failed to download the manifest: failed to download manifest - failed to retrieve manifest: ValidationException: Require valid document name.
	status code: 400, request id: 2825b7c6-a188-4ed8-8ffe-3662f22ac0fb
```

the same happens with the latest version.

Thank you for fixing this.

**Comment by Aperocky** [comment]
We have rolled back the problematic commit and deployed new agent version `3.3.1345.0`, you can now update by simply running `AWS-UpdateSSMAgent`.
