### ISSUE TITLE
Windows Server 2025 Agents disconnecting with MachineFingerprintDoesNotMatch after initial registration

### ISSUE THREAD

**Issue by djcampbell** [aws/amazon-ssm-agent#601]
This was observed in agent version v3.3.1345.0.
 
Affecting only Windows Server 2025 (with wmic feature enabled), the SSM agent disconnects with a MachineFingerprintDoesNotMatch error approximately one hour after initial successful registration.

This is happening on multiple platforms (tested on VMWare and OpenStack) I am continuing to test scenarios, but suspect this to be agent related.

**Comment by djcampbell** [comment]
After further investigation, I found that this error occurred immediately after an agent upgrade from v3.3.1230.0 to v3.3.1345.0.
The error is not encountered when the initial install is 3.3.1345.0. Curious to see if this happens again after the next agent update.

Reinstalling and reregistering the agent (new managed instance ID) solved the issue for now.

**Comment by Aperocky** [comment]
This is unfortunately expected as we did not formally support Windows 2025 with the previous agent version, as `wmic` is not present by default in Windows 2025 and a number of agent feature will not work when it isn't present. Even though custom action can install `wmic` and make it work, we made an update to make it fully compatible with Windows 2025 beginning with current version `3.3.1345.0` and we will reflect that in our documentation.

Unfortunately this also means that processes (e.g. fingerprint) that used to depend on `wmic` has changed for Windows 2025 (and only for Windows 2025), and you may have to re-register your Windows 2025 instance. This is a one time issue affecting only this update, and will not happen in any future version update.

Please let us know if you ran into any further issue during re-registration.
