### ISSUE TITLE
Upgrading to v2.0.879.0 - Parameter substitution not working

### ISSUE THREAD

**Issue by PaulAtkins** [aws/amazon-ssm-agent#61]
Hey,

After updating to `v2.0.879.0` it seems like the Command document parameter substitution has stopped working as expected.

### Steps to Reproduce

Run a Command doc that includes `parameters`, 

e.g. :

```
{
  "schemaVersion": "2.0",
  "description": "Example",
  "parameters": {
    "Message": {
      "type": "String",
      "description": "Example",
      "default": "Hello World"
    }
  },
  "mainSteps": [
    {
      "action": "aws:runPowerShellScript",
      "name": "Example",
      "inputs": {
        "runCommand": [
          "Write-Output {{Message}}"
        ]
      }
    }
  ]
}
```

### Expected Behaviour:

Output should be `Hello World`

### Actual Behaviour:

`v2.0.847.0`: `Hello World`
`v2.0.879.0`: `{{Message}}`   <-- Param not substituted

**Comment by mmendonca3** [comment]
@PaulAtkins  Thank you for bringing this to our notice. 
We are investigating the issue and will fix it in the next release. 

Thanks again!

**Comment by thirkcircus** [comment]
afaict this happens only when you provide a default value for the parameter

**Comment by mmendonca3** [comment]
This issue has been resolved
