### ISSUE TITLE
SSMAgent as non-root user from SystemD

### ISSUE THREAD

**Issue by joequint** [aws/amazon-ssm-agent#63]
I am running SSMAgent as a non-root user (ssmagent) and the "gathersoftwareinventory" plugin seems to fail on me  :(   After going through the code,  I discovered that the permissions in amazon-ssm-agent/agent/appconfig/constants.go are set for user instead of users+group.  

My proposal is to change the defaults to mirror user permissions to group. 
=====BEFORE ===================================
	// Permissions defaults
	//NOTE: Limit READ, WRITE and EXECUTE access to administrators/root.
	ReadWriteAccess        = 0600
	ReadWriteExecuteAccess = 0700
=======AFTER==========================================
	// Permissions defaults
	//NOTE: Limit READ, WRITE and EXECUTE access to administrators/root.
	ReadWriteAccess        = 0660
	ReadWriteExecuteAccess = 0770
====================================================

To reproduce my issue RHEL 7.x . 
`sudo groupadd ssmagent
sudo useradd -g ssmagent ssmagent

sudo visudo
##APPEND THIS LINE TO THE END OF THE FILE IF YOU WANT SSMAGENT TO BE ABLE TO SUDO
ssmagent        ALL=(ALL)       NOPASSWD: ALL

[ec2-user@ip-172-31-18-35 system]$ cat /etc/systemd/system/amazon-ssm-agent.service
[Unit]
Description=amazon-ssm-agent
After=network-online.target

[Service]
Type=simple
WorkingDirectory=/usr/bin/
ExecStart=/usr/bin/amazon-ssm-agent
KillMode=process
Restart=on-failure
RestartSec=15min
User=ssmagent
Group=ssmagent

[Install]
WantedBy=network-online.target

sudo chgrp -hR ssmagent /var/lib/amazon/
sudo chmod -R 775  /var/lib/amazon/

sudo chgrp -hR ssmagent /var/log/amazon/
sudo chmod -R 775  /var/log/amazon/

sudo systemctl restart amazon-ssm-agent

sudo journalctl
`

This yields  a Failed to  "reate orchestrationDir directory" error for log files in the amazon-ssm-agent/agent/fileutil/fileutil.go [mkdirall] command called by amazon-ssm-agent/agent/plugins/inventory/inventory.go module

**Comment by mmendonca3** [comment]
Hi joequint, 

Thank you for your request. Currently, we need SSM Agent to be running with root access. Our team will track this request through this issue and we will get back to you here once we have a solution.

**Comment by stavarotti** [comment]
@mmendonca3, any update on this?

**Comment by mmendonca3** [comment]
Hi stavarotti, 

This request is still in our backlog. We will get back to you once an update has been made to that. Thank you for your patience.

**Comment by nandubatchu** [comment]
@mmendonca3 that means by default, SSM is configured to run the shellScripts as the root user?

**Comment by mmendonca3** [comment]
@nandubatchu Yes. That is correct.

**Comment by nandubatchu** [comment]
@mmendonca3 can this be changed or controlled with some IAM profiles?

**Comment by joequint** [comment]
Thanks Amazon for keeping an eye on this.   Maybe an alternative would be to be able to create a separate user for all the shell/powershell scripts that run when SSM agent is installed.  This would allow finer grain security for the scripts being run.  To me that might be the simplest solution.
