### ISSUE TITLE
Support Association Name

### ISSUE THREAD

**Issue by dhoer** [aws/amazon-ssm-agent#64]
It looks like AWS Console has a new column called `Association Name`.  Can `AssociationName` attribute be added to the CLI?

On a related note; can `Name` be deprecated in favor of `DocumentName`?

**Comment by TheRealBenForce** [comment]
And CloudFormation also please :)

**Comment by mmendonca3** [comment]
Hello, 

CreateAssociation already has the AssociationName attribute as suggested by you. You can find more information on that here - https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CreateAssociation.html. The CLI information for that can be found here - https://docs.aws.amazon.com/cli/latest/reference/ssm/create-association.html. The CLI attribute for that is association-name

Changing 'Name' to 'DocumentName' would break the contract and we cannot make that change, unfortunately. I will be closing this issue. Please reopen it if you have any further comment. 

Thank you!

**Comment by mmendonca3** [comment]
Additionally, please make sure your AWS CLI is up to date using 'pip install awscli --upgrade --user'. You can find more information here - https://docs.aws.amazon.com/cli/latest/userguide/installing.html
