### ISSUE TITLE
AWS-RunPowerShellScript success status

### ISSUE THREAD

**Issue by ruicovelo** [aws/amazon-ssm-agent#69]
I understand PowerShell exit codes are [handled differently than bash](http://chrisoldwood.blogspot.pt/2011/05/powershell-throwing-exceptions-exit.html). However, something like this used to work with EC2 Config agent:

```
trap { Write-Error "Something went wrong!"; Exit 1}
net
```

The "net" command will fail (missing parameters) and the trap code would run.

With SSM Agent this does not work anymore. I think this is related with how SSM Agent runs commands that are not native to powershell. 

Is this an issue you want to solve or are we now left with checking every command output? Like this:

`net; if ($?) { Write-Error "Something went wrong"; Exit 1}`

**Comment by IveGotThePawa** [comment]
If I can add that for me, if the status of the SSM command is Success, I assume it was successful on all account. This definitely looks like a bug to me. 

Maybe capture the Error Output? If its not empty, set the status to partial succes or something similar (like TFS 2017 does). 

Allow us to check that the exit code is in a range of defined value? Most of the time its zero, but not for all commands / programs. 

Just some thoughts

**Comment by ruicovelo** [comment]
Just to add that I'm currently checking $LASTEXITCODE, $? and the $error list for errors (it turns out native vs non powershell commands might dump error outputs to different places). I'm also keeping a trap on the top of the script. I created a function which I call all the time to check for errors. Definitely not a perfect solution but an ugly workaround.

**Comment by mmendonca3** [comment]
Hello ruicovelo, 

We are aware of this issue. This is a known issue with Powershell. Powershell does not return the right exit code and so we cannot determine the status of the output:
http://chrisoldwood.blogspot.com/2011/05/powershell-throwing-exceptions-exit.html

Thank you for providing a workaround for this issue. You can refer to this closed issue - https://github.com/aws/amazon-ssm-agent/issues/51 for alternate solutions as well.

**Comment by thedevopsmachine** [comment]
Little late commenting here, but drawing from the fact that this situation only occurs when running non-powershell commands in powershell, there's something else you can do to keep it more "powershelly"

# Here we're going to redirect the error stream to the output stream and capture it in "output"
$output = net.exe 2>&1
# We then check the $lastexitcode shortcut and, if it's false, throw whatever output was captured.
if (!$?) { throw $output }

This results in a non-zero exit code in PowerShell, plus it will give you the stack trace information to help you find the issue more easily.

Remember, you only need to do this when running non-powershell commands, With native powershell you can just set add $ErrorActionPreference = 'Stop' to the top of your script and any exception that is thrown will cause the script to terminate (with a non-zero exit code).

**Comment by larkost** [comment]
To add a very late answer here: in some cases what you need to do is to add `-ErrorAction Stop` to your command. In my case this was `Get-Content -Path '<bad path here>'`, and without that I would get a return code 0, and the error message stuffed into the "Output" field on the CommandInvocations.

My opinion here is that the AWSRunPowershell action should absolutely catch errors and convert them to failures. That it does not exactly match the unix way of doing things is a poor excuse. This is a bug that is hurting customers.
