### ISSUE TITLE
CloudWatch Multiple Dimensions

### ISSUE THREAD

**Issue by quoc-axiadids** [aws/amazon-ssm-agent#70]
Hello,

I am trying to configure a component in CloudWatch JSON to output metrics with multiple dimensions.

Single dimension works.

    {
        "DimensionName": "<name>",
        "DimensionValue": "<value>"`
    }

The following I would hope to work.
    
    "Dimensions": [
        {
            "Name": "<name1>",
            "Value": "<value1>"
        },
       {
           "Name": "<name2>",
           "Value": "<value2>"
       }
    ]

But receive the following error:

`AWS.EC2.Windows.CloudWatch.CloudwatchConfigurationException: Could not parse the provided JSON, please check the configuration file and make sure it is valid. ---> Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartArray. Path 'EngineConfiguration.Components[2].Parameters.Dimensions', line 35, position 26.`

How is multiple dimensions support with the agent?

**Comment by mmendonca3** [comment]
Thank you for your request. I will send your request to the appropriate team. 

Please note, SSM Agent has discontinued further development for Cloudwatch and any new feature will be undertaken by the new Cloudwatch agent. More information about this agent can be found here - https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Install-CloudWatch-Agent.html

**Comment by zhoufang-joe** [comment]
It can be accomplished via **_append_dimensions_** in the new agent https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html#CloudWatch-Agent-Configuration-File-Metricssection

**Comment by mmendonca3** [comment]
Closing issue since this feature is already supported. Please reopen the issue if you need further assistance.
