### ISSUE TITLE
Amazon SSM agent is using all of my i-nodes

### ISSUE THREAD

**Issue by andrewme2** [aws/amazon-ssm-agent#72]
I was running an older (from May?) version of the SSM agent, and my EC2 instance got into a state where 100% of my i-nodes were in use.  It caused my EC2 instance to effectively lock up.  I tracked the issue down to the SSM agent was not cleaning up files in these two directories:

     /var/lib/amazon/ssm/<instance-ID>/document/state/completed
     /var/lib/amazon/ssm/<instance-ID>/document/orchestration

I saw that this issue was fixed in June by 2.0.834, and I upgraded my SSM agent to 2.0.922.0-1 on August 22.  However, today I see that SSM files are still not being cleaned up (even ones older than 14 days, which I believe is the default value for cleaning up files), and 86% of my 4 million i-nodes are currently in use.

As a temporary workaround, is there a way to force the SSM agent to run its cleanup?  Or troubleshoot why the cleanup is not working?  I don't see any obvious messages in the log file, but I'm not sure what to look for, either.

**Comment by andrewme2** [comment]
This issue appears to be fixed in version 2.2.24.0: https://github.com/aws/amazon-ssm-agent/releases/tag/v2.2.24.0

**Comment by mmendonca3** [comment]
Hello andrewme2, 

Thank you for bringing this to our attention. As you mentioned, this issue has been resolved in agent version 2.2.24.0. 

I'm closing this issue. Please feel free to reopen it if you have questions.
