### ISSUE TITLE
SSM on Raspbian OS

### ISSUE THREAD

**Issue by muthyas** [aws/amazon-ssm-agent#73]
Successfully registered the managed device (in our case Raspberry Pi) into the AWS console. We could see a GREEN light showing connected. However, upon reboot of RPi, we are seeing an error from the agent:

RequestManagedInstanceRoleToken: MachineFingerprintDoesNotMatch

Do I need to re-register the device after every reboot? Thanks for any help.
[errors.log](https://github.com/aws/amazon-ssm-agent/files/1332049/errors.log)
[amazon-ssm-agent.log](https://github.com/aws/amazon-ssm-agent/files/1332050/amazon-ssm-agent.log)

**Comment by blasagna** [comment]
I am having the exact same issue on Raspbian Jessie

**Comment by muthyas** [comment]
Figured it out. The fingerprint is formed as a hash of the following properties:
Machine ID, Processor Info, Memory Info, BIOS Info, System Info, Hostname Info, Primary IP Address, Mac Address, and Disk Info. In the case of Jessie, the machine id changes every time the Pi reboots. 

There are two possible solutions:
Option 1: Install Stretch, or
Option 2: Run the following commands one after the other on Jessie:
"umount /etc/machine-id"
"run systemd-machine-id-setup”
Upon reboot the machine id no longer changes and you should not see above error.
