### ISSUE TITLE
Add tags for managed instances

### ISSUE THREAD

**Issue by blasagna** [aws/amazon-ssm-agent#74]
State Manager Association targets are specified either as one or more InstanceIds and/or using tags. Could a tag be associated with a managed instance when it is registered so that managed instances could be added and an existing Association applied to them automatically?

**Comment by mmendonca3** [comment]
Thank you for your request, blasagna. 

I will forward your request to the concerning team.

**Comment by thedevopsmachine** [comment]
Upvoting this, since the Patch Manager patch group functionality requires tags in order for it to work: https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-patch-patchgroups.html, and being able to assign patch groups to Maintenance Windows is incredibly useful. Much less so when you have to manually assign instances to baselines and windows.

**Comment by swares** [comment]
I need this too.  I use tags for my activations but can not find a way to add tags to on premise instances I have registered... so none of them run on our on premise instances automatically as is desired.

**Comment by mmendonca3** [comment]
Thank you for posting here and your interest in Systems Manager. According to the relevant teams, this feature is supported for both EC2 and on-premise instances. The following are the steps to reproduce this.

1) Tag an EC2 instance A with tag: "test" value :"association"
2) Create an association with the above tag value pair
3) Then tag one "mi-" instance and one more EC2 instance B with same tag value pair
4) Refresh the association. After some time all the three instances are seen as targets 

Please let us know if you have any further queries.

**Comment by racheliurui** [comment]
> 4\. Refresh the association. After some time all the three instances are seen as targets

=======================
@mmendonca3  reading through these steps I still feel confused, to tag the on-premise target, I need 
1)  create a EC2 , and tag the EC2 with desired tag name
2)  create association , associate with EC2 with desired tag and also the on-premise server currently without tag
3) "tag one "mi-" instance" -----> we didn't found this button , is that a feature only available after we finished step 2?

I haven't archived this follow above steps.
Could you share more details on how to tag an on-premise server via above steps ?

Thanks very much !
