### ISSUE TITLE
 Custom cloud watch metrics for memory, load and other metrics

### ISSUE THREAD

**Issue by runningman84** [aws/amazon-ssm-agent#77]
It would be really cool if SSM would provide these metrics by default.

**Comment by mmendonca3** [comment]
Hello runningman84, 

Thank you for your request. Adding memory and other metrics are already supported using SSM documents. This blog has good examples of how you can setup metrics in Windows for the existing agent - http://www.padisetty.com/2015/10/ssm-cloudwatch-configuration-part-4-of-5.html. 

We also have a new agent for Cloudwatch which works on both Linux and Windows instances - https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Install-CloudWatch-Agent.html. 

We leave it to the customer to decide if they want to collect metrics using Cloudwatch. Unfortunately, this cannot be made a default feature. 

I am closing this comment. Please feel free to reopen it if you have any further concerns.

**Comment by riponbanik** [comment]
@mmendonca3 which one do you recommend unified CloudwatchAgent or SSM Agent plugin? Where the future development will happen?Thanks
