### ISSUE TITLE
Agent can not be registered: panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by isfugithub** [aws/amazon-ssm-agent#84]
We try to register the SSM Agent on an OL7 Box:

[root@srv0 ssm]# amazon-ssm-agent -register -code "XXX" -id "XXX" -region "eu-central-1"
Error occurred fetching the seelog config file path:  open /etc/amazon/ssm/seelog.xml: no such file or directory
Initializing new seelog logger
New Seelog Logger Creation Complete
2018-02-09 16:59:31 INFO Start File Watcher On: /etc/amazon/ssm/seelog.xml
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/aws/aws-sdk-go/aws/ec2metadata.(*EC2Metadata).Region(0xc42000e600, 0xc4201b5480, 0x866db5, 0x0, 0x0)
	/local/p4clients/pkgbuild-F0Rtj/workspace/src/Amazon-ssm-agent/vendor/src/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go:122 +0xb7
github.com/aws/amazon-ssm-agent/agent/platform.instanceMetadata.Region(0xc42000e600, 0x0, 0x0, 0x42a5b9, 0xc400000008)
	/local/p4clients/pkgbuild-F0Rtj/workspace/src/Amazon-ssm-agent/build/private/src/github.com/aws/amazon-ssm-agent/agent/platform/instance_info_deps.go:60 +0x2b
github.com/aws/amazon-ssm-agent/agent/platform.fetchRegion(0x8, 0xc66f90, 0x10f8370, 0x1c0)
	/local/p4clients/pkgbuild-F0Rtj/workspace/src/Amazon-ssm-agent/build/private/src/github.com/aws/amazon-ssm-agent/agent/platform/instance_info.go:189 +0x64
github.com/aws/amazon-ssm-agent/agent/platform.Region(0x0, 0x0, 0x0, 0x0)
	/local/p4clients/pkgbuild-F0Rtj/workspace/src/Amazon-ssm-agent/build/private/src/github.com/aws/amazon-ssm-agent/agent/platform/instance_info.go:85 +0x9d
github.com/aws/amazon-ssm-agent/agent/ssm/util.AwsConfig(0xada140)
	/local/p4clients/pkgbuild-F0Rtj/workspace/src/Amazon-ssm-agent/build/private/src/github.com/aws/amazon-ssm-agent/agent/ssm/util/util.go:43 +0x366
github.com/aws/aws-sdk-go/aws.(*Config).WithLogLevel(...)
	/local/p4clients/pkgbuild-F0Rtj/workspace/src/Amazon-ssm-agent/build/private/src/github.com/aws/amazon-ssm-agent/agent/ssm/anonauth/anon_service.go:42
github.com/aws/amazon-ssm-agent/agent/ssm/anonauth.NewAnonymousService(0x7ffd7e4be737, 0xc, 0x0, 0x0)
	/local/p4clients/pkgbuild-F0Rtj/workspace/src/Amazon-ssm-agent/build/private/src/github.com/aws/amazon-ssm-agent/agent/ssm/anonauth/anon_service.go:42 +0xa3
main.registerManagedInstance(0x0, 0x0, 0x0, 0xc4201b5ea8)
	/local/p4clients/pkgbuild-F0Rtj/workspace/src/Amazon-ssm-agent/agent/agent_parser.go:152 +0x328
main.processRegistration(0x10a16a0, 0xc4201ce3a0, 0x1)
	/local/p4clients/pkgbuild-F0Rtj/workspace/src/Amazon-ssm-agent/agent/agent_parser.go:111 +0xce
main.parseFlags(0x10a16a0, 0xc4201ce3a0)
	/local/p4clients/pkgbuild-F0Rtj/workspace/src/Amazon-ssm-agent/agent/agent_parser.go:63 +0x3fa
main.main()
	/local/p4clients/pkgbuild-F0Rtj/workspace/src/Amazon-ssm-agent/agent/agent_unix.go:14 +0x99

**Comment by hiimtu** [comment]
Hi! Closing this issue as it has been a while since anyone has commented. Many agent versions have been release since this issue, so try updating to the latest version. If you are still seeing this issue, feel free to open a new one.
