### ISSUE TITLE
Is there any way to suppress messages in SYSLOG

### ISSUE THREAD

**Issue by macktab** [aws/amazon-ssm-agent#85]
Please, can somebody help me with supressing amazon-ssm-agent messages in syslog, it is writing everything on ec2-run-command right in syslog
We started to discuss this in https://github.com/aws/amazon-ssm-agent/issues/59
But issue was closed.
I changed in /etc/amazon/ssm/seelog.xml minlevel="off", but, of course, it does not changed behavior
I already have this messages in /var/lib/amazon/ssm/%instanceid%/document/orchestration/* and in s3, I definitly do not want to see that in syslog.

**Comment by mmendonca3** [comment]
Hello macktab, 

In order to not produce the log files - c:\ProgramData\Amazon\SSM\Logs\amazon-ssm-agent.log and c:\ProgramData\Amazon\SSM\Logs\errors.log on Windows, or the /var/log/Amazon/ssm/amazon-ssm-agent.log and /var/log/Amazon/ssm/errors.log file you need to follow the same process as my comment in #59 . I will try to make the instructions more clear. 

1 a. On Windows, locate %PROGRAMFILES%\Amazon\SSM\seelog.xml.template
1 b. On Linux, locate /etc/amazon/ssm/seelog.xml.template

2.  Change the file name from seelog.xml.template to seelog.xml. Please ensure that the file has changed from template type to xml type

3. Update the file by locating the line below:
<seelog type="adaptive" mininterval="2000000" maxinterval="100000000" critmsgcount="500" minlevel="info">
and change the "info" to "off". Do not change it in any other location in this file. Save the file. 

4. Restart the agent. 

5. You can now delete the amazon-ssm-agent.log and errors.log files since they will not be written to. 

In case you find that the logs are appearing in any other path, or you have another path that you call syslog, please let us know here.

**Comment by mmendonca3** [comment]
In order for us to help you further, could you please let us know which distribution/version of Linux or Windows you are working on? Also, where do you see the syslog logging that you want to suppress, what is the log level there? 

Thanks!

**Comment by macktab** [comment]
root@ip-172-16-85-128:/var/log# cat /etc/issue
Ubuntu 16.04.3 LTS \n \l

root@ip-172-16-85-128:/var/log# uname -a
Linux ip-172-16-85-128 4.4.0-1047-aws #56-Ubuntu SMP Sat Jan 6 19:39:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@ip-172-16-85-128:/var/log# cat /etc/amazon/ssm/seelog.xml
<!--amazon-ssm-agent uses seelog logging -->
<!--Seelog has github wiki pages, which contain detailed how-tos references: https://github.com/cihub/seelog/wiki -->
<!--Seelog examples can be found here: https://github.com/cihub/seelog-examples -->
<seelog type="adaptive" mininterval="2000000" maxinterval="100000000" critmsgcount="500" minlevel="info">
    <exceptions>
        <exception filepattern="test*" minlevel="off"/>
    </exceptions>
    <outputs formatid="fmtinfo">
        <console formatid="fmtinfo"/>
        <rollingfile type="size" filename="/var/log/amazon/ssm/amazon-ssm-agent.log" maxsize="30000000" maxrolls="5"/>
        <filter levels="error,critical" formatid="fmterror">
            <rollingfile type="size" filename="/var/log/amazon/ssm/errors.log" maxsize="10000000" maxrolls="5"/>
        </filter>
    </outputs>
    <formats>
        <format id="fmterror" format="%Date %Time %LEVEL [%FuncShort @ %File.%Line] %Msg%n"/>
        <format id="fmtdebug" format="%Date %Time %LEVEL [%FuncShort @ %File.%Line] %Msg%n"/>
        <format id="fmtinfo" format="%Date %Time %LEVEL %Msg%n"/>
    </formats>
</seelog>
root@ip-172-16-85-128:/var/log# cat syslog|grep amazon-ssm-agent
Feb 13 06:25:52 ip-172-16-85-128 amazon-ssm-agent[6590]: 2018-02-13 06:25:52 INFO [instanceID=i-01658b12a134ba441] [HealthCheck] HealthCheck reporting agent health.
Feb 13 06:30:40 ip-172-16-85-128 amazon-ssm-agent[6590]: 2018-02-13 06:30:40 INFO [instanceID=i-01658b12a134ba441] [MessagingDeliveryService] [Association] Schedule manager refreshed with 0 associations, 0 new assocations associated
Feb 13 06:30:52 ip-172-16-85-128 amazon-ssm-agent[6590]: 2018-02-13 06:30:52 INFO [instanceID=i-01658b12a134ba441] [HealthCheck] HealthCheck reporting agent health.
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]: 2018-02-13 06:33:38 INFO [instanceID=i-01658b12a134ba441] [MessagingDeliveryService] [messageID=aws.ssm.a27ccf4d-ea7f-43cd-9fe8-3d4effb887c7.i-01658b12a134ba441] Validating SSM parameters
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]: 2018-02-13 06:33:38 INFO [instanceID=i-01658b12a134ba441] [MessagingDeliveryService] Sending reply {
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]:   "additionalInfo": {
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]:     "agent": {
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]:       "lang": "en-US",
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]:       "name": "amazon-ssm-agent",
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]:       "os": "",
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]:       "osver": "1",
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]:       "ver": ""
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]:     },
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]:     "dateTime": "2018-02-13T06:33:38.694Z",
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]:     "runId": "",
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]:     "runtimeStatusCounts": null
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]:   },
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]:   "documentStatus": "InProgress",
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]:   "documentTraceOutput": "",
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]:   "runtimeStatus": null
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]: }
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]: 2018-02-13 06:33:38 INFO [instanceID=i-01658b12a134ba441] [MessagingDeliveryService] SendReply Response{
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]:   Description: "Reply 6dfe581c-c18e-4623-ab12-4034cf5af72b was successfully sent.",
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]:   MessageId: "aws.ssm.a27ccf4d-ea7f-43cd-9fe8-3d4effb887c7.i-01658b12a134ba441",
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]:   ReplyId: "6dfe581c-c18e-4623-ab12-4034cf5af72b",
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]:   ReplyStatus: "QUEUED"
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]: }
Feb 13 06:33:38 ip-172-16-85-128 amazon-ssm-agent[6590]: 2018-02-13 06:33:38 INFO [instanceID=i-01658b12a134ba441] [MessagingDeliveryService] [EngineProcessor] [OutOfProcExecuter] [a27ccf4d-ea7f-43cd-9fe8-3d4effb887c7] channel: a27ccf4d-ea7f-43cd-9fe8-3d4effb887c7 not found, creati
ng a new file channel...
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]: 2018-02-13 06:33:38 INFO [instanceID=i-01658b12a134ba441] [MessagingDeliveryService] [EngineProcessor] [OutOfProcExecuter] [a27ccf4d-ea7f-43cd-9fe8-3d4effb887c7] inter process communication started
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]: 2018-02-13 06:33:38 INFO [instanceID=i-01658b12a134ba441] [MessagingDeliveryService] [EngineProcessor] [OutOfProcExecuter] [a27ccf4d-ea7f-43cd-9fe8-3d4effb887c7] requested terminate messaging worker, destroying the channel
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]: 2018-02-13 06:33:38 INFO [instanceID=i-01658b12a134ba441] [MessagingDeliveryService] [EngineProcessor] [OutOfProcExecuter] [a27ccf4d-ea7f-43cd-9fe8-3d4effb887c7] channel /var/lib/amazon/ssm/i-01658b12a134ba441/channels/a27ccf
4d-ea7f-43cd-9fe8-3d4effb887c7 requested close
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]: 2018-02-13 06:33:38 INFO [instanceID=i-01658b12a134ba441] [MessagingDeliveryService] [EngineProcessor] sending reply for plugin update: aws:runShellScript
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]: 2018-02-13 06:33:38 INFO [instanceID=i-01658b12a134ba441] [MessagingDeliveryService] [EngineProcessor] [OutOfProcExecuter] [a27ccf4d-ea7f-43cd-9fe8-3d4effb887c7] channel /var/lib/amazon/ssm/i-01658b12a134ba441/channels/a27ccf
4d-ea7f-43cd-9fe8-3d4effb887c7 closed
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]: 2018-02-13 06:33:38 INFO [instanceID=i-01658b12a134ba441] [MessagingDeliveryService] [EngineProcessor] [OutOfProcExecuter] [a27ccf4d-ea7f-43cd-9fe8-3d4effb887c7] Executer closed
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]: 2018-02-13 06:33:38 INFO [instanceID=i-01658b12a134ba441] [MessagingDeliveryService] [EngineProcessor] sending document: a27ccf4d-ea7f-43cd-9fe8-3d4effb887c7 complete response
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]: 2018-02-13 06:33:38 INFO [instanceID=i-01658b12a134ba441] [MessagingDeliveryService] received plugin: aws:runShellScript result from Processor
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]: 2018-02-13 06:33:38 INFO [instanceID=i-01658b12a134ba441] [MessagingDeliveryService] Sending reply {
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:   "additionalInfo": {
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:     "agent": {
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:       "lang": "en-US",
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:       "name": "amazon-ssm-agent",
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:       "os": "",
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:       "osver": "1",
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:       "ver": ""
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:     },
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:     "dateTime": "2018-02-13T06:33:38.817Z",
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:     "runId": "",                                                                                                                                                                                                          [1/139]
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:     "runtimeStatusCounts": {
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:       "Success": 1
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:     }
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:   },
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:   "documentStatus": "InProgress",
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:   "documentTraceOutput": "",
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:   "runtimeStatus": {
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:     "aws:runShellScript": {
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:       "status": "Success",
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:       "code": 0,
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:       "name": "aws:runShellScript",
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:       "output": "test\n",
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:       "startDateTime": "2018-02-13T06:33:38.811Z",
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:       "endDateTime": "2018-02-13T06:33:38.815Z",
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:       "outputS3BucketName": "",
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:       "outputS3KeyPrefix": "",
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:       "standardOutput": "test\n",
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:       "standardError": ""
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:     }
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:   }
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]: }
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]: 2018-02-13 06:33:38 INFO [instanceID=i-01658b12a134ba441] [MessagingDeliveryService] SendReply Response{
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:   Description: "Reply 1f6e519e-6f3d-4060-8233-256e2bbcd7a2 was successfully sent.",
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:   MessageId: "aws.ssm.a27ccf4d-ea7f-43cd-9fe8-3d4effb887c7.i-01658b12a134ba441",
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:   ReplyId: "1f6e519e-6f3d-4060-8233-256e2bbcd7a2",
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]:   ReplyStatus: "QUEUED"
Feb 13 06:33:39 ip-172-16-85-128 amazon-ssm-agent[6590]: }
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]: 2018-02-13 06:33:38 INFO [instanceID=i-01658b12a134ba441] [MessagingDeliveryService] command: aws.ssm.a27ccf4d-ea7f-43cd-9fe8-3d4effb887c7.i-01658b12a134ba441 complete
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]: 2018-02-13 06:33:38 INFO [instanceID=i-01658b12a134ba441] [MessagingDeliveryService] [EngineProcessor] execution of aws.ssm.a27ccf4d-ea7f-43cd-9fe8-3d4effb887c7.i-01658b12a134ba441 is over. Removing interimState from current 
folder
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]: 2018-02-13 06:33:38 INFO [instanceID=i-01658b12a134ba441] [MessagingDeliveryService] Sending reply {
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:   "additionalInfo": {
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:     "agent": {
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:       "lang": "en-US",
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:       "name": "amazon-ssm-agent",
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:       "os": "",
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:       "osver": "1",
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:       "ver": ""
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:     },
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:     "dateTime": "2018-02-13T06:33:38.955Z",
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:     "runId": "",
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:     "runtimeStatusCounts": {
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:       "Success": 1
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:     }
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:   },
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:   "documentStatus": "Success",
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:   "documentTraceOutput": "",
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:   "runtimeStatus": {
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:     "aws:runShellScript": {
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:       "status": "Success",
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:       "code": 0,
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:       "name": "aws:runShellScript",
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:       "output": "test\n",
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:       "startDateTime": "2018-02-13T06:33:38.811Z",
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:       "endDateTime": "2018-02-13T06:33:38.815Z",
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:       "outputS3BucketName": "",
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:       "outputS3KeyPrefix": "",
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:       "standardOutput": "test\n",
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:       "standardError": ""
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:     }
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:   }
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]: }
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]: 2018-02-13 06:33:39 INFO [instanceID=i-01658b12a134ba441] [MessagingDeliveryService] SendReply Response{
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:   Description: "Reply 11b825e8-a897-4bcf-b5b4-86b897c40cff was successfully sent.",
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:   MessageId: "aws.ssm.a27ccf4d-ea7f-43cd-9fe8-3d4effb887c7.i-01658b12a134ba441",
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:   ReplyId: "11b825e8-a897-4bcf-b5b4-86b897c40cff",
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]:   ReplyStatus: "QUEUED"
Feb 13 06:33:40 ip-172-16-85-128 amazon-ssm-agent[6590]: }

**Comment by thedevopsmachine** [comment]
Try creating/altering the log configuration file at /etc/amazon/ssm/seelog.xml to be as follows:

<seelog type="adaptive" mininterval="2000000" maxinterval="100000000" critmsgcount="500" minlevel="info">
    <exceptions>
        <exception filepattern="test*" minlevel="error"/>
    </exceptions>
    <outputs formatid="fmtinfo">
        <console formatid="fmtinfo"/>
        <rollingfile type="size" filename="/etc/amazon/ssm/logs/amazon-ssm-agent.log" maxsize="30000000" maxrolls="5"/>
        <filter levels="error,critical" formatid="fmterror">
            <rollingfile type="size" filename="/etc/amazon/ssm/logs/errors.log" maxsize="10000000" maxrolls="5"/>
        </filter>
    </outputs>
    <formats>
        <format id="fmterror" format="%Date %Time %LEVEL [%FuncShort @ %File.%Line] %Msg%n"/>
        <format id="fmtdebug" format="%Date %Time %LEVEL [%FuncShort @ %File.%Line] %Msg%n"/>
        <format id="fmtinfo" format="%Date %Time %LEVEL %Msg%n"/>
    </formats>
</seelog>

The problem you are seeing is likely because you have no logging configuration set, and thus you are using the Linux seelog default settings (i.e. info+ messages to syslog). By creating this config file you're instructing SSM to log to files in the /etc/amazon/ssm/logs directory instead of the seelog defaults, so you should stop seeing any writes to syslog. However, you might want to add another error output section to go to syslog. Probably something like this in the "filter" element in addition to the "rollingfile" entry:

<file path="/var/log/syslog"/>

**Comment by macktab** [comment]
Sorry, same result.

**Comment by macktab** [comment]
I deleted line
<console formatid="fmtinfo"/>
from seelog.xml, and now there is no this entries in syslog.
Thanks everybody.

**Comment by the6thBook** [comment]
Why is this closed?  I have the same issue on centos.  Everything written to message, nothing written to "/etc/amazon/ssm/logs".   I installed ssm per the aws instructions.  I did not modify anything.

**Comment by macktab** [comment]
About logging to syslog all messages, try to delete console formatid="fmtinfo" from /etc/amazon/ssm/seelog.xml
`
sed -i '/console formatid="fmtinfo"/d' /etc/amazon/ssm/seelog.xml.template
mv /etc/amazon/ssm/seelog.xml.template /etc/amazon/ssm/seelog.xml
service amazon-ssm-agent restart
`
