### ISSUE TITLE
downloadcontent s3 plugin does not support bucket urls in the format <bucketname>.s3.amazonaws.com

### ISSUE THREAD

**Issue by reidca** [aws/amazon-ssm-agent#87]
If you use an S3 path in the format [bucketname].s3.amazonaws.com the task fails with no error visible in the automation console other than "returns unexpected invocation result: {Status=[Failed]}" with no further details visible.

It seems that you have to use either s3-region.amazonaws.com/bucketname or s3.amazonaws.com/bucketname

This is a problem, especially since using fn::getAtt returning the domain name of the bucket returns it in the form [bucketname].s3.amazonaws.com.

**Comment by mmendonca3** [comment]
Hello reidca, 

Thank you for bringing this to our attention. Our team will investigate this issue and get back to you when we have a fix or ETA.

**Comment by mmendonca3** [comment]
This fix has been shipped in the most recent version of the agent v2.2.355.0
