### ISSUE TITLE
Amazon SSM agent is using all of my i-nodes

### ISSUE THREAD

**Issue by andrewme2** [aws/amazon-ssm-agent#94]
The SSM agent (v2.2.93 and v2.2.120) does not seem to be cleaning up files in the orchestration directory. The issue is reproducible on many EC2 instances that I have.

I have several EC2 instances where i-node usage is 90%+ and one where it is 100%.  Once 100% is reached, the system effectively locks up and the ssm log files show many "no space left on device" errors.

I tracked the issue down to the SSM agent not cleaning up files in this directory:

     /var/lib/amazon/ssm/<instance-ID>/document/orchestration

For example, one of my EC2 instances has files in the orchestration directory going back to Dec. 5.

A similar issue was fixed in 2.2.24.0:

     https://github.com/aws/amazon-ssm-agent/issues/72

**Comment by wael-amz** [comment]
Can you please update your agent to the latest version?

**Comment by vjt** [comment]
Hi @andrewme2,

I am also experiencing this issue. As a workaround, I am using this cron job in root's crontab:

```
0 0 * * * find /var/lib/amazon/ssm/i-*/document/orchestration -mindepth 2 -maxdepth 2 -type d -mtime +3 -print0 | xargs -0 rm -rf
```

This will be executed every day at midnight and delete all orchestration documents older than 3 days.

**Comment by kapilt** [comment]
has this been resolved in a release?

**Comment by ldm810** [comment]
@wael-amz Is there a workaround or updates on this issue?

**Comment by wael-amz** [comment]
The issue has been addressed in the latest release [2.2.800.0](https://github.com/aws/amazon-ssm-agent/releases/tag/2.2.800.0)

**Comment by andrewme2** [comment]
Hi @wael-amz , I'm trying to verify that this bug is fixed. I upgraded to 2.2.800.0. How long do I need to wait before the SSM agent will clean up old files?  I do not know how often the agent runs its clean-up routine (every hour, once-per-day, etc?).  After running for ~2 hours, I still have directories in the orchestration directory from May:

root@ip-X-X-X-X:~# ls -ltr /var/lib/amazon/ssm/<REDACTED>/document/orchestration | head
total 774160
drwx------ 3 root root 4096 May  1 17:59 9b1a8ca8-REDACTED
drw------- 3 root root 4096 May  1 17:59 8c7ca5d1-REDACTED
drw------- 3 root root 4096 May  1 18:02 a7a2756a-REDACTED
drwx------ 3 root root 4096 May  1 18:03 6dd8855e-REDACTED
drwx------ 3 root root 4096 May  1 18:07 28445cc3-REDACTED
drwx------ 3 root root 4096 May  1 18:07 dca845eb-REDACTED
drw------- 3 root root 4096 May  1 18:10 e2bd2589-REDACTED
drwx------ 3 root root 4096 May  1 18:10 a4e4b5e3-REDACTED
drw------- 3 root root 4096 May  1 18:11 cd02fb83-REDACTED

**Comment by wael-amz** [comment]
The cleanup logic will be triggered every time you run a command and it is not time based.
