### ISSUE TITLE
OSX build?

### ISSUE THREAD

**Issue by jhaynie** [aws/amazon-ssm-agent#95]
Is it possible to get this to build on OSX? It looks like the Makefile has targets. But when I check `go get` i get errors even with `-d`.

When I try and run the makefile from source download, I get a ton of check style errors such as:

`/Users/xyz/go/src/github.com/aws/amazon-ssm-agent/agent/longrunning/plugin/cloudwatch/test_cloudwatch.go:42: call of cw.On copies lock value: github.com/aws/amazon-ssm-agent/agent/task.MockCancelFlag contains github.com/stretchr/testify/mock.Mock contains sync.Mutex`

I'm wondering if you're dependent on an older version of Golang?  I'm using go 1.10.

**Comment by mmendonca3** [comment]
Hello jhaynie, 

Currently, we do not support the agent on OSX. We apologize for the inconvenience. 

I will be closing this issue. Please feel free to reopen it if you have any concerns.

**Comment by mathewmoon** [comment]
Plus one for this

**Comment by reecejmarkowsky** [comment]
please support osx :)
