### ISSUE TITLE
Do you have any plans to bring managed instances under resource Group/Tag Editor support ? 

### ISSUE THREAD

**Issue by rajeshuppuluri** [aws/amazon-ssm-agent#96]
we can add new tags to on-prem servers. but what is the point, if we can't use these tags while using run documents?

**Comment by rajeshuppuluri** [comment]
I can use group resources/Tagging only for cloud servers. I am wondering if we can expect same even for managed instances.

**Comment by thedevopsmachine** [comment]
What exactly are you trying to do? If you're talking about consuming Tags inside of RunCommand Documents, you can do that, you just need to retrieve them differently. For example:

```
# If it's a managed instance, the instance ID will start with "mi"
if ($instanceId.StartsWith('mi-'))
{
    $tags = Get-SSMResourceTag -ResourceId $instanceId -ResourceType ManagedInstance
}
else
{
    $tags = (Get-EC2Instance -InstanceId "$instanceId").Instances[0].Tags
}
```

**Comment by manfromdownunder** [comment]
I am trying to create resource groups for onprem managed instances based on tags.  This doesn't seem to be possible and an unnecessary restriction.

**Comment by djulian-amzn** [comment]
We're working on expanding Resource Groups to other tag-capable AWS resources including managed instances within AWS Systems Manager.

In the meantime, one can group managed instances using tags. One may then run documents, commands, and other tasks against combinations of these assigned tags and values. Our customers rely extensively on tagging for all sorts of management scenarios.

Thanks for your interest in AWS Systems Manager!
